<script>
function submit()
{
    $title = $("#title1").val();
    $remark = $("#remark").val();
    
    if($title=="")
    {
        alert("请提供文件名信息，其他信息可稍后提交");
    }    
    else
    {
        $("#archiveform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/archive/manage";        
}

function redirect(url) {
    window.location = url;
}
</script>
<?php

$id = 0;
$mode = "Create";
$title="";
$remark="";
$type = "doc";

if($this->mode == "Edit")
{
$id = $this->archive->getId();
$mode = "Edit";
$title = $this->archive->getTitle();
$remark = $this->archive->getRemark();
$type = $this->archive->getType();
}
     
?>
<h3>文件添加与编辑</h3>
<form id="archiveform" method="post" action="/archive/manage/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<div data-role="fieldcontain">
	<label for="type" class="select">文件类别:</label>
	<select name="type" id="type">
    <?php
    $types = array("doc"=>"文档", "sw"=>"软件");
    foreach($types as $key=>$value)
    {
        if($type == $key)
        {
            echo '<option value="' . $key . '" selected>' . $value . "</option>";
        }
        else
        {
            echo '<option value="' . $key . '" >' . $value . "</option>";
        }
    }
    ?>
	</select>
</div>

<div data-role="fieldcontain">
    <label for="title1">文件名称:</label>
    <!-- do not use title, which will drive jqm crazy :P -->
    <input type="text" name="title1" id="title1" value="<?php echo $title; ?>"  />
</div>

<div data-role="fieldcontain">
    <label for="remark">文件说明:</label>
    <textarea cols="40" rows="8" name="remark" id="remark" ><?php echo $remark; ?></textarea>
</div>

<div data-role="fieldcontain">
    <label for="file" class="ui-input-text">选择文件:</label>
    <input type="file" name="file" id="file">
</div>
</form> <!--archive form -->
<fieldset class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><button type="submit" data-theme="d" onclick="cancel()">取消</button></div>
</fieldset>
