<style>
/*#swdiv { display:none;}*/
</style>

<div class="ui-grid-b">
	<div class="ui-block-a"><button>文档列表</button></div>
	<div class="ui-block-b"><button>软件列表</button></div>
	<div class="ui-block-c"><button>上传文件</button></div>
</div><!-- /grid-b -->

<div id="docdiv">
<?
/* id, update, title, path, size, remark, type*/
echo $this->grid("Documents", true)
          ->field('update','更新日期')
          ->field('title', '名称')
          ->field('remark', '注释')
          ->actionField(':action', null, '&nbsp;|&nbsp;')
          ->itemCountPerPage(5)
          ->paginatorEnabled(false) // disable internal paginator, use dataTable's
          ->helper(new GridHelper_Archive())
          ->data($this->documents)
          ->action(':action', 'Edit', array( 'url'=>array('action'=>'pageedit')))
          ->action(':action', 'Preview', array( 'url'=>array('action'=>'preview')))
          ->action(':action', 'Publish', array( 'url'=>array('action'=>'publishpage')))
        ->action(':action', 'Delete', array('url'=>array('action'=>'deletepage')));
?>

</div>

<div id="swdiv">
<?
/* id, update, title, path, size, remark, type*/
echo $this->grid("Softwares", true)
          ->field('update','更新日期')
          ->field('title', '名称')
          ->field('remark', '注释')
          ->actionField(':action', null, '&nbsp;|&nbsp;')
          ->itemCountPerPage(50)
          ->paginatorEnabled(false) // disable internal paginator, use dataTable's
          ->helper(new GridHelper_Archive())
          ->data($this->softwares)
          ->action(':action', 'Edit', array( 'url'=>array('action'=>'pageedit')))
          ->action(':action', 'Preview', array( 'url'=>array('action'=>'preview')))
          ->action(':action', 'Publish', array( 'url'=>array('action'=>'publishpage')))
      ->action(':action', 'Delete', array('url'=>array('action'=>'deletepage')));
?>
</div>

