<style>
#swdiv { display:none; }
.grid { width:100%; }
#Documents { width:100%; }
#Softwares { width:100%; }
</style>
<script>
function showSw()
{
    $("#docdiv").hide();
    $("#swdiv").show();
    //$("#docbtn").attr("data-theme", "");
    //$("#swbtn").attr("data-theme", "a");     

     $("#swbtn").addClass('ui-state-focus');  
}

function showDoc()
{
    $("#swdiv").hide();
    $("#docdiv").show();
    $("#docbtn").attr("data-theme", "a");
    $("#swbtn").attr("data-theme", "");       
}

</script>

<div data-role="navbar">
	<ul>
		<li><a href="#" onclick="showDoc()" class="ui-btn-active">文档列表</a></li>
		<li><a href="#" onclick="showSw()">软件列表</a></li>
		<li><a href="/archive/manage/add" >上传文件</a></li>
	</ul>
</div><!-- /navbar -->

<div id="docdiv">
<?
/* id, update, title, path, size, remark, type*/
echo $this->grid("Documents", true)
          ->field('path','文档下载')
          ->field('update','更新日期')
          ->field('title', '名称')
          ->field('remark', '说明')
          ->actionField(':action', "文件操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(5)
          ->paginatorEnabled(false) // disable internal paginator, use dataTable's
          ->helper(new GridHelper_Archive())
          ->data($this->documents)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>

</div>

<div id="swdiv">
<?
/* id, update, title, path, size, remark, type*/
echo $this->grid("Softwares", true)
          ->field('path','软件下载')
          ->field('update','更新日期')
          ->field('title', '名称')
          ->field('remark', '注释')
          ->actionField(':action', null, '&nbsp;|&nbsp;')
          ->itemCountPerPage(50)
          ->paginatorEnabled(false) // disable internal paginator, use dataTable's
          ->helper(new GridHelper_Archive())
          ->data($this->softwares)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>

