<style type="text/css">
table {
    width: 100%;
}
td {

    text-align: center;
}
</style>
<div class="wrap">
<div id="room_ctrol">
    <table>
        <tr>
            <td>
            <div id="msg"><FONT SIZE="+3" ><?php echo $this->translate('Choose from Header Menu to Control This Room')?>.</FONT></div>
            </td>
        </tr>
    </table>
</div>
</div>
<?
global $roomindex;
$roompreset="ui-btn-active";
include ('header.phtml');
?>