<style>
    #uploaddiv { display: none; }
    #Maindata { 
        font-size:medium; 
        text-shadow: 0 1px #FFFFFF;               
    }    
</style>
<script>
    $(function() {
        $('#Maindata').dataTable({
            "iDisplayLength": 100,
            "bRetrieve": true,
        });
    });

    function showhideupload()
    {
        var div = $("#uploaddiv");
        var display = div.css("display");
        (display == "none") ? div.show() : div.hide();
    }

    function clearalldata()
    {
                var r = confirm("确认删除数据?");
        if (r == false)
        {
            return false;
        }

        $.post("/material/summary/truncateall", {},
                function(data) {
                    //console.log(data);
                    //$('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month + "&sid="+siteid);
                    alert("删除成功");
                    window.location.reload();
                })
    }

    $('#selsheet').change(function() {
        //alert("selsheet");
        var sheetname = $(this).val();
        var url = "/material/summary?sheet=" + sheetname;
        redirect(url);
    });

    function redirect(url) {
        window.location = url;
    }

</script>
<?php
$sheetarr = $this->sheetarr;
$sheet = $this->sheet;
?>
<div class="ui-grid-a">
    <div class="ui-block-a">
        <button data-mini="true" data-theme="a" onclick="showhideupload()">导入订购材料汇总</button>
    </div>
    <div class="ui-block-b">
        <button data-mini="true" data-theme="a" onclick="clearalldata()">清空订购材料汇总</button>
    </div>
</div><!-- /grid-a -->
<div id="uploaddiv">
    <fieldset>
        <form action="/material/summary/submit" method="post" enctype="multipart/form-data">
            <label for="file" class="ui-input-text">上传材料数据文件(MS Excel file)：</label>
            <input data-mini="true" type="file" name="file" id="file">
            <input type="submit" value="上传" data-mini="true" data-theme="a">
        </form>
    </fieldset>
</div>
<select id="selsheet" name="selsheet" data-mini="true">
    <?php
    $options = "";
    foreach ($sheetarr as $tmp) {
        if ($tmp == $sheet) {
            $option = '<option value="' . $tmp . '" selected>' . $tmp . "</option>";
        } else {
            $option = '<option value="' . $tmp . '" >' . $tmp . "</option>";
        }
        $options .= $option;
    }
    echo $options;
    ?>
</select>
<?
echo $this->grid("Maindata", true)
->field('id','ID')
->field('catalog','Catalog')
->field('itemc','Item-C')
->field('iteme','Item-E')
->field('unit','Unit')
->field('qty','Qty')
->field('price','Price')
->field('orderdate','Order Date')
->field('supplier', 'Supplier')
->field('totalamount', 'Total Amount')  
->field('workerqty', 'Worker Qty')
->field('remark', 'Remark')
->actionField(':action', "", '&nbsp;|&nbsp;')
->paginatorEnabled(false)
->setSorting(false)  
->helper(new GridHelper_Summary())
->data($this->maindata);
?>
<br><br>
