<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<style type="text/css">
	#orderListBack
    {
		display:none;
		position:fixed;
		_position:absolute;
		top:0px;
		left:0px;
		width:100%;
		height:100%;
		background-color:#fff;
		background:-moz-radial-gradient(50% 50%, #fff, #000);/*gradient for firefox*/
		background:-webkit-radial-gradient(50% 50%, #fff, #000);/*new gradient for webkit */
		background:-webkit-gradient(radial, 0 50%, 0 50%, from(#fff), to(#000));/*the old grandient for webkit*/
		opacity:0.9;
		filter:Alpha(opacity=50);
		_display:block;
		_left:-10000px;
		z-index:9999;
    }

    #orderList
    {
		display:none;
		position:fixed;		
		background-color:white;
		top:30%;
		left:42%;
		width:400px;
		min-height:200px;
		margin-left:-250px;
		margin-top:-150px;
		padding:40px;
		line-height:21px;
		box-shadow:0 5px 27px rgba(0,0,0,0.3);
		-webkit-box-shadow:0 5px 27px rgba(0,0,0,0.3);
		-moz-box-shadow:0 5px 27px rgba(0,0,0,0.3);
		_position:absolute;
		_display:block;
		_left:-10000px;
		z-index:10000;
    }

	#msgBody #orderListBack{
		display:block;
		_left:0px;
	}
	#msgBody #orderList{
		display:block;
		_left:50%;
	}
	#msgBody{
		_overflow:hidden;
	}
	
#servicebar-container {
    display:block;
    position:relative;
    color:white;
    height:40px;
    line-height:40px;
    background-color:black;
    padding:2px 10px 2px 10px;
    clear:both;
    margin-top:1em;
}

#servicebar-action-panel, #servicebar-link-panel {
    display:block;
    position:absolute;
    right:0px;
    bottom:0px;
}
#servicebar-action-panel {
    top:15px;
    bottom:10px;
}
#servicebar-link-panel {
    left:0;
    bottom:0;
}
.servicebar, .servicebar-label {
    padding-right:8px;
    padding-left:8px;
    float:left;
}
.servicebar a {
    text-decoration:none;
    text-align:center;
}
.servicebar a:hover {
    text-decoration:underline;
}

.button-view-icon {
    height:16px;
    line-height:16px;
}

</style>

<script language="JavaScript">
var randomnumber;
function popupOrders(){
	document.body.id = 'msgBody';
	//randomnumber=Math.floor(Math.random()*100000);	
	//$("#orders").attr("src","/service/index/orderlist?"+randomnumber);
	var url='/service/index/orderlist/json/';
	$.get(url,function(result){
		var string=result;
		$("#orders2").html(string);
	});	
	
}


function hide()
{
	document.body.id = '';
}
function orderComplete(){
	var url="/service/index/orderlist/cmd/confirm/";
	$.get(url,function(data){
		alert(data);
		document.body.id = '';
		$("#itemcount").html("");
		getOrderlist();
	});	
}
function resort(listType){
	var url ="/service/index/catalog/listType/"+listType;
	$(".service-view").hide();
	$.get(url,function(result){			
		$("#service_listRadio"+listType).show();
	});
}
</script>

<?php if(false):?>
<table width="100%">
	<tr>
		<td  class="service_orderbar_back" style="background:black;">
			<p id="service_orderbar1" style="text-indent:1em">Favorites</p>
		</td>
		<td width="1%"></td>		
		<td class="service_orderbar_back" width="25%">
			<a href="#" onClick=popupOrders() style="text-decoration:none;">
				<img src="/images/service/orders.png" id="service_orderbar2" alt="orders"/> 
				<p id="service_orderbar3" style="float:left;">View orders</p>
			</a>
		</td>
        <td width="1%"></td>	
        <td class="service_orderbar_back" align="center width="15%">
        	<a href="#" onclick='resort()' style="text-decoration:none;">
        		<p id="service_orderbar4">View</p>
            </a>
        </td>
	</tr>
</table>
<?php endif;?>

<div id="servicebar-container"  class="ui-bar ui-bar-c">
    <div id="servicebar-link-panel" data-theme="a">
        <div id="favorites" class="servicebar-label"><?php echo $this->translate("Favorites");?></div>
        <div id="view-order" class="servicebar-label">
    	    <a href="#" onclick="popupOrders()" data-theme="a"><?php echo $this->translate("Orders View");?>
		<span id="itemcount">
		<? if(!empty($this->itemcount)): ?>
		<? echo '('.$this->itemcount.')'; ?>
		<? endif; ?>
		</span></a>
        </div>
    </div>
        
    <div id="servicebar-action-panel">
        <div id="Menu" class="servicebar">
           	<a href="#" onclick='resort(1)'><img src="/tablet/images/icons/button-view-thumbnails.png" class="button-view-icon"/></a>
    	</div>
        <div id="list" class="servicebar" style="display:none">
           	<a href="#" onclick='resort(2)'><img src="/tablet/images/icons/button-view-list.png" class="button-view-icon"/></a>
    	</div>
    	<div id="view" class="servicebar">
           	<a href="#" onclick='resort(3)'><img src="/tablet/images/icons/button-view-detailed.png" class="button-view-icon"/></a>
    	</div>
    </div>
</div>

<div id="orderListBack"></div>
<div id="orderList">
	<h3><?php echo $this->translate("Order list");?></h3>
	<!--<iframe id="orders" name="orders" width = "100%" height = "auto" frameborder="0" scrolling="no"></iframe>-->
	<div id = "orders2"></div>
	<div >
		<div id="appendleft">
			
		</div>
    	<div id="appendright">
			<a href="#" onclick="document.body.id = '';getOrderlist()" data-role="button"><?php echo $this->translate("Go back and add More");?></a>
		</div>
	</div>
	<div >
		<div id="appendleft">
			
		</div>
    	<div id="appendright">
			<a href="#" onclick="orderComplete()" data-role="button"><?php echo $this->translate("Confirm and Finalize Order");?></a>
		</div>
	</div>
	</p>
</div>

