<?php
echo $this->grid("matpodata", true)
        //->field('supplier', '供应商')
        ->field('id', 'ID')        
        ->field('pono', 'PO No.')
        ->field('contact', 'Contact')
        ->field('phone', 'Phone')
        ->actionField(':action', "操作", '&nbsp;|&nbsp;')
        ->itemCountPerPage(30)
        ->paginatorEnabled(false)
        ->setSorting(false)
        //->helper(new GridHelper_Appdetail())
        ->data($this->maindata);
?>