<style>
    #appinfotab { width:100%; }
    #totalprice { width:98%; text-align: right; }
</style>
<script>
    $(document).ready(function() {
        $('#matapps').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
        });
    });

    $('.settings').on("click", function() {
        //alert("settings click");
        var poid = $(this).attr("poid");
        //alert("poid="+poid);
        $("#poid").val(poid);
    });
</script>
<?php
$appobj = $this->application;
$appid = $appobj->getId();
$create = $appobj->getCreatedate()->format("Y-m-d H:i:s");
$update = $appobj->getUpdatedate()->format("Y-m-d H:i:s");
$applicant = $appobj->getApplicant();
$applicantname = "";
$applicantid = 0;
if ($applicant) {
    $applicantname = $applicant->getName();
    $applicantid = $applicant->getId();
}

$sitename = $this->sitename;
$siteid = $this->siteid;

$sites = $this->sites;
$humanres = $this->humanres;

$role = $this->role;
$displayblk = ($role == "manager") ? 1 : 0;

$matapps = $this->matapps;
$totalprice = $this->totalprice ? $this->totalprice : 0;

$company = $this->company;
$cmyname = $this->cmyname;

$suppliers = $this->suppliers;
$poarr = $this->poarr;
?>

<!--<h3>申请单详细信息</h3>-->
<input type="hidden" id="appid" value="<?php echo $appid; ?>">
<table class="" id="appinfotab">
    <tbody>
        <tr>
            <td><strong>申请工地:</strong></td><td><strong><?php echo $sitename; ?></strong></td>
            <td><strong>承包公司:</strong></td><td><strong><?php echo $cmyname; ?></strong></td>
        </tr>
        <tr>
            <td><strong>申请人员:</strong></td><td><strong><?php echo $applicantname; ?></strong></td>
            <td><strong>更新时间:</strong></td><td><strong><?php echo $update; ?></strong></td>
        </tr>
        <tr>
            <td><strong>申请总价:</strong></td><td><strong><?php echo $totalprice; ?></strong></td>
            <td><strong>申请单号:</strong></td><td><strong><?php echo $appid; ?></strong></td>
        </tr>
    </tbody>
</table>
<hr>
<?php
echo $this->grid("matapps", true)
        ->field('supplier', '供应商')
        ->field('longname', '材料名称')
        //->field('spec','型号规格')
        ->field('description', '描述')
        ->field('amount', '申请数量')
        ->field('unit', '单位')
        ->field('rate', '单价')
        ->field('quantity', '数量')
        ->field('total', '总价')
        ->field('sitepart', '工程部位')
        //->field('remark','补充说明')
        ->actionField(':action', "操作", '&nbsp;|&nbsp;')
        ->itemCountPerPage(30)
        ->paginatorEnabled(false)
        ->setSorting(false)
        ->helper(new GridHelper_Appdetail())
        ->data($matapps);
?>
<br><hr>

<table class="grid">
    <thead><tr><th>Supplier</th><th>PO No.</th><th>Contact</th><th>Phone</th><th>Action</th></tr></thead>
    <tbody>
        <?php
        if (count($poarr)) {
            $trs = "";
            foreach ($poarr as $tmp) {
                $supplierid = $tmp->getSupplier()->getId();
                $suppliername = $tmp->getSupplier()->getName();
                $poid = $tmp->getId();
                $appid = $tmp->getApplication()->getId();

                $pono = $tmp->getPono();
                $contact = $tmp->getContact();
                $phone = $tmp->getPhone();
                $tr = "";
                $td = "<td>$suppliername</td>";
                $tr .= $td;
                $td = "<td>$pono</td>";
                $tr .= $td;
                $td = "<td>$contact</td>";
                $tr .= $td;
                $td = "<td>$phone</td>";
                $tr .= $td;

                $btnsettings = '<a href="#popupLogin" data-rel="popup" data-position-to="window" '
                        . 'data-role="button" data-inline="true" data-mini="true"'
                        . 'poid="' . $poid . '" class="settings">Settings</a>';

                $url = '/material/appmanage/previeworder?id=' . $appid
                        . "&supplier=" . $supplierid
                        . "&poid=$poid";
                $btnpreview = '<a href="' . $url . '" target="_blank" '
                        . 'data-mini="true" data-role="button">Preview</a>';
                $btnsdiv = '<div class="ui-grid-a">
                    <div class="ui-block-a">' . $btnsettings . '</div>'
                        . '<div class="ui-block-b">' . $btnpreview . '</div>
                            </div>';


                $td = "<td>$btnsdiv</td>";
                $tr .= $td;

                $trs .= "<tr>" . $tr . "</tr>";
            }
            echo $trs;
        }
        ?>
    </tbody>
</table>

<div data-role="popup" id="popupLogin" data-theme="a" class="ui-corner-all">
    <form method="post" action="/material/po/posettings">
        <input type="hidden" name="poid" id="poid" value="0">

        <div style="padding:10px 20px;">
            <h3>Purchase Order Settings</h3>
            <label for="un" class="ui-hidden-accessible">Username:</label>
            <input type="text" name="pono" id="pono" value="" placeholder="PO No." data-theme="a" />

            <label for="un" class="ui-hidden-accessible">Username:</label>
            <input type="text" name="contact" id="contact" value="" placeholder="Contact" data-theme="a" />            

            <label for="un" class="ui-hidden-accessible">Username:</label>
            <input type="text" name="phone" id="phone" value="" placeholder="Phone" data-theme="a" />            

            <button type="submit" data-theme="b">Submit</button>
        </div>
    </form>
</div>

<br><br>
