<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<style>
</style>
<script>
/*
$('#start').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  

$('#stop').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  
*/

function submit()
{
    $namechs = $("#namechs").val();
    //$remark = $("#remark").val();
    
    if($namechs=="")
    {
        alert("请至少提供名称，其他信息可稍后提交");
    }    
    else
    {
        $("#mainform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/company/info";        
}

function redirect(url) {
    window.location = url;
}
</script>
<?php
$id = 0;
$mode = "Create";
$namechs="";
$nameeng="";
$address="";
$phone="";
$fax="";
$email="";
$coregno="";
$remark="";

$start = "";
$stop = "";
$leader="";
$manager="";
$workerno=0;

$fullnamechs="";
$fullnameeng="";

if($this->mode == "Edit")
{
$data = $this->maindata;
$mode = "Edit";
$id = $data->getId();
$namechs = $data->getNamechs();
$nameeng = $data->getNameeng();
$address = $data->getAddress();
$phone = $data->getPhone();
$email = $data->getEmail();
$fax = $data->getFax();
$coregno= $data->getCoregno();
$remark = $data->getRemark();

$fullnamechs=$data->getFullnamechs();
$fullnameeng=$data->getFullnameeng();

}
     
?>

<?php
if($mode == "Create")
{
    echo "<h3>添加公司信息</h3>";
}
else
{
    echo "<h3>编辑公司信息</h3>";    
}
?>

<form id="mainform" method="post" action="/company/info/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">

<table class="grid">
<thead></thead>
<tbody>
<tr>
<td style="width:20%"><strong>公司中文名:</strong></td>
<td style="width:30%"><input type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" data-mini="true" /></td>
<td style="width:20%"><strong>公司中文全名:</strong></td>
<td style="width:30%"><input type="text" name="fullnamechs" id="fullnamechs" value="<?php echo $fullnamechs; ?>" data-mini="true" /></td>
</tr>

<tr>
<td style="width:20%"><strong>公司英文名:</strong></td>
<td style="width:30%"><input type="text" name="nameeng" id="nameeng" value="<?php echo $nameeng; ?>" data-mini="true" /></td>
<td style="width:20%"><strong>公司英文全名:</strong></td>
<td style="width:30%"><input type="text" name="fullnameeng" id="fullnameeng" value="<?php echo $fullnameeng; ?>" data-mini="true" /></td>
</tr>

<tr>
<td><strong>公司电话:</strong></td>
<td><input type="text" name="phone" id="phone" value="<?php echo $phone; ?>" data-mini="true" /></td>
<td><strong>公司传真:</strong></td>
<td><input type="text" name="fax" id="fax" value="<?php echo $fax; ?>" data-mini="true" /></td>
</tr>

<tr>
<td><strong>公司地址:</strong></td>
<td><input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true" /></td>
<td><strong>公司电邮:</strong></td>
<td><input type="text" name="email" id="email" value="<?php echo $email; ?>" data-mini="true" /></td>
</tr>

<tr>
<td><strong>公司CO REG NO:</strong></td>
<td><input type="text" name="coregno" id="coregno" value="<?php echo $coregno; ?>" data-mini="true" /></td>
<td><strong>公司备注:</strong></td>
<td><input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true" /></td>
</tr>

</tbody>
</table>
</form>

<div class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><input type="button" onclick="cancel()" value="取消"></div>
</div>

