<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<script>
    function submit()
    {
        $namechs = $("#namechs").val();
        //$remark = $("#remark").val();

        if ($namechs == "")
        {
            alert("请至少提供名称，其他信息可稍后提交");
        }
        else
        {
            $("#mainform").submit();
        }

    }

    function cancel()
    {
        var r = confirm("放弃编辑信息，返回列表界面");
        if (r == true)
        {
            gotolist();
        }
    }

    function gotolist()
    {
        window.location = "/company/info";
    }

    function redirect(url) {
        window.location = url;
    }
</script>
<?php
$id = 0;
$mode = "Create";
$namechs = "";
$nameeng = "";
$address = "";
$phone = "";
$fax = "";
$email = "";
$coregno = "";
$remark = "";

$start = "";
$stop = "";
$leader = "";
$manager = "";
$workerno = 0;
$fullnamechs = "";
$fullnameeng = "";
$postring = "";
$logopic = "";

if ($this->mode == "Edit") {
    $data = $this->maindata;
    $mode = "Edit";
    $id = $data->getId();
    $namechs = $data->getNamechs();
    $nameeng = $data->getNameeng();
    $address = $data->getAddress();
    $phone = $data->getPhone();
    $email = $data->getEmail();
    $fax = $data->getFax();
    $coregno = $data->getCoregno();
    $remark = $data->getRemark();

    $fullnamechs = $data->getFullnamechs();
    $fullnameeng = $data->getFullnameeng();

    $postring = $data->getPostring();
    
    $logopic=$data->getLogo();
    $logopath="/uploads/$logopic"; 
    
    $sheetprx=$data->getSheetprx();
}
?>

<?php
if ($mode == "Create") {
    echo "<h3>添加公司信息</h3>";
} else {
    echo "<h3>编辑公司信息</h3>";
}
?>

<form id="mainform" method="post" action="/company/info/submit" enctype="multipart/form-data">
    <input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
    <input type="hidden" id="id" name="id" value="<?php echo $id; ?>">

    <table class="grid">
        <thead></thead>
        <tbody>
            <tr>
                <td><strong>公司logo:</strong></td>
                <td><input data-mini="true" type="file" name="file" id="file"></td>
                <td><img src="<?= $logopath ?>" alt="无照片显示" width="40%"  id="pic" name="pic"></td>
            </tr>
            <tr>
                <td style="width:20%"><strong>公司中文名(短):</strong></td>
                <td style="width:30%">
                    <input type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" data-mini="true" placeholder="用于网页显示，比如华诚，或者华诚发展"/>
                </td>
                <td style="width:20%"><strong>公司中文全名(长):</strong></td>
                <td style="width:30%">
                    <input type="text" name="fullnamechs" id="fullnamechs" value="<?php echo $fullnamechs; ?>" data-mini="true" placeholder="用于打印，比如华诚发展有限公司"/>
                </td>
            </tr>

            <tr>
                <td style="width:20%"><strong>公司英文名(短):</strong></td>
                <td style="width:30%">
                    <input type="text" name="nameeng" id="nameeng" value="<?php echo $nameeng; ?>" data-mini="true" placeholder="用于网页显示，比如Hwa Cheng"/>
                </td>
                <td style="width:20%"><strong>公司英文全名(长):</strong></td>
                <td style="width:30%">
                    <input type="text" name="fullnameeng" id="fullnameeng" value="<?php echo $fullnameeng; ?>" data-mini="true" placeholder="用于打印，比如Hwa Cheng Development Pte Ltd"/>
                </td>
            </tr>

            <tr>
                <td><strong>公司电话:</strong></td>
                <td><input type="text" name="phone" id="phone" value="<?php echo $phone; ?>" data-mini="true" /></td>
                <td><strong>公司传真:</strong></td>
                <td><input type="text" name="fax" id="fax" value="<?php echo $fax; ?>" data-mini="true" /></td>
            </tr>

            <tr>
                <td><strong>公司地址:</strong></td>
                <td><input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true" /></td>
                <td><strong>公司电邮:</strong></td>
                <td><input type="text" name="email" id="email" value="<?php echo $email; ?>" data-mini="true" /></td>
            </tr>

            <tr>
                <td><strong>公司CO REG NO:</strong></td>
                <td><input type="text" name="coregno" id="coregno" value="<?php echo $coregno; ?>" data-mini="true" /></td>
                <td><strong>公司备注:</strong></td>
                <td><input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true" /></td>
            </tr>

            <tr>
                <td><strong>公司PO字串:</strong></td>
                <td><input type="text" name="postring" id="postring" value="<?php echo $postring; ?>" data-mini="true" /></td>
                <td><strong>工人列表前缀:</strong></td>
                <td><input type="text" name="sheetprx" id="sheetprx" value="<?= $sheetprx ?>" data-mini="true" placeholder="HC代表华诚，HT代表华腾，用于区分工人所在列表"/></td>
            </tr>

        </tbody>
    </table>
</form>

<div class="ui-grid-a">
    <div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()" data-mini="true">提交</button></div>
    <div class="ui-block-b"><input type="button" onclick="cancel()" value="取消" data-mini="true"></div>
</div>
<br><br>

