<script>
    $(function() {
    });
</script>
<a href="/company/info/add"><button data-mini="true" data-theme="a">添加公司</button></a>
<?php
echo $this->grid("Companyinfo", true)
        ->field('namechs', '公司中文名')
        ->field('fullnamechs', '公司中文全名')
        ->field('nameeng', '公司英文名')
        ->field('fullnameeng', '公司英文全名')
        ->field('coregno', 'Co Reg No')
        ->field('postring', 'PO字串')
        ->field('phone', '联系电话')
        ->field('address', '地址')
        ->actionField(':action', "", '&nbsp;|&nbsp;')
        ->itemCountPerPage(30)
        ->paginatorEnabled(false)
        ->setSorting(false)
        ->data($this->maindata)
        ->action(':action', '详细信息', array('url' => array('action' => 'infodetail')))
        ->action(':action', '编辑', array('url' => array('action' => 'edit')));
?>

