<?php
// Global Defines for template
$settings = Zend_Registry::get('settings');
// Note these are prepended in reverse order
// to be correct
$this->headScript()->prependFile('/tablet/js/jquery.event.drag-2.2.js');
$this->headScript()->prependFile('/tablet/js/jquery.ui.touch-punch.js');
$this->headScript()->prependFile('/tablet/js/ui.js');
$this->headScript()->prependFile('/common/js/jquery.mobile-1.2.0.min.js');
$this->headScript()->prependScript('
// Disable AJAX jquerymobile handling for now (makes debugging easier)    
$(document).bind("mobileinit", function(){
		     $.mobile.ajaxEnabled = false;
    });
    ', $type = 'text/javascript');
$this->headScript()->prependFile('/common/js/jquery-1.8.2.min.js');

// Reverse order
$this->headLink()->prependStylesheet('/tablet/css/layout-mgmt.css');
$this->headLink()->prependStylesheet('/tablet/css/menu-mgmt.css');
$this->headLink()->prependStylesheet('/tablet/css/style-mgmt.css');
$this->headLink()->prependStylesheet('/common/css/jquery.mobile.structure-1.2.0.min-mgmt.css');
$this->headLink()->prependStylesheet('/common/css/synrgic-hcs-jquerymb-mgmt.css');
?>

<?php echo $this->doctype(); ?>

<html lang="en" xml:lang="en">
    <head>
        <meta charset="utf-8">
        <style type="text/css">
            body {<?php echo $this->layout()->style; ?>;}
        </style>
        <link href="/common/css/layout.css" rel="stylesheet" type="text/css">
        <link href="/common/css/menu-mgmt.css" rel="stylesheet" type="text/css">
        <script src="/common/js/jquery-1.8.2.min.js"></script>
        <?php echo $this->headMeta() ?>
        <title>InfoX</title>
        <!--<?php echo $this->headTitle() ?>-->
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        <link rel="shortcut icon" href="/images/gssvgabstract234.png" type="image/x-icon">
        <link rel="icon" href="/images/gssvgabstract234.png" type="image/x-icon">
    </head>
    <body>
        <div id='header'>
            <?php /* echo $this->partial("_header.phtml"); */ ?>
            <div>
                <?php
                $settings = Zend_Registry::get('settings');
                $path = $settings->General->Logo->Value;
                ?>
                <span id="logo">
                    <a href='/management/dashboard'>
                        <!--<img src='<?php echo $path; ?>'/>-->
                        <img src='/images/gssvgabstract234.png'/>
                    </a>
                </span>
                <span id='title'>
                    <!--<?php echo sprintf($this->translate('%s Hotel Suite Management Portal'), $settings->General->HotelName->Value); ?>-->
                    <a href='/management/dashboard'>
                        InfoX                    
                    </a>                
                </span>
                <span id='logout'>
                    <a href='<?php echo $this->url(array("module" => "management", "controller" => "auth", "action" => "logout")); ?>'>
                        <?php
                        $user = Zend_Auth::getInstance();
                        if (isset($user) && $user->hasIdentity()) {
                            echo $user->getIdentity()->getName();
                            echo '&nbsp;-&nbsp;';
                            echo $user->getIdentity()->getRole();
                            echo '&nbsp;-&nbsp;';
                        }
                        echo $this->translate("Logout");
                        ?>
                    </a>
                </span>
            </div>
        </div>
        <div id="top-header-shadow"></div>
        <div id="container">
            <div id="dashboard" class="column">
                <div id="context-box">
                    <?php echo $this->layout()->content; ?>			
                </div>
            </div>
            <div id="sidebar" class="column">
                <?php echo $this->layout()->sidebar; ?>
            </div>
        </div>
        <div id="footer">
            <?php /* echo $this->partial("_footer.phtml"); */ ?>
        </div>
    </body>
</html>
