<script type="text/javascript" src="/common/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>
<?php
$content=$this->content;
?>
<form method="post" action="/infoxsys/manage/submit">
<textarea name="content" style="width:100%" rows="20">
<?php
echo $content;
?>    
</textarea>
<input type="submit" value="提交" data-mini="true" data-theme="a">
</form>
