<form id="<?php echo $this->element->getFormId();?>" 
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <p>
    	<label for="name" class="required"><?=$this->translate("name:");?></label>
        <?php echo $this->element->name; ?>
    </p>
    <p>
        <label for="Description"><?=$this->translate("description:");?></label>
	    <?php echo $this->element->description; ?>
    </p>
	<p>
        <label for="Type"><?=$this->translate("type:");?></label>
	    <?php echo $this->element->type; ?>
    </p>
	
    <p>
       	<label>&nbsp;</label>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>

