<h1><?php echo $this->translate('View operation log');?></h1>

<!-- <a href="<?php echo $this->url(array('action'=>'clean'));?>">Clean operating record</a> -->

<div class="msg"><?php echo $this->message;?></div>

<?php if(empty($this->data)&&($this->page==0)):?>
<h2><?php echo $this->translate('No operation log data found');?>!</h2>
<?php else:?>
<table border="1">
    <tr><td>#ID</td>
        <td><?php echo $this->translate('User');?> ID</td>
        <td><?php echo $this->translate('User');?><?php echo $this->translate('Name');?></td>
        <td><?php echo $this->translate('Time');?></td>
        <td><?php echo $this->translate('Event');?></td>
    </tr>
<?php foreach($this->data as $r): ?>
    <tr><td><?php echo $r->getId();?></td>
        <td><?php echo $r->getUser_id();?></td>
        <td><?php echo $this->userName[$r->getId()];?></td>
        <td><?php echo $r->getTime()->format('Y-m-d H:i:s');?></td>
        <td><?php echo $r->getEvent();?></td>
    </tr>
<?php endforeach;?>
</table>

<p>
<?php if ($this->page>=1) :?>
<a
		href=" <?php echo $this->url(array('action'=>'index','page'=>$this->page-1));?>"><?php echo $this->translate('Previous');?></a>
&nbsp;
<?php endif;?>
<?php if($this->endpage==0):?>
<a
		href="<?php echo $this->url(array('action'=>'index','page'=>$this->page+1));?>">
		<?php echo $this->translate('Next');?></a>
</p>
<?php endif;?>

<?php endif;?>
