<script>
function submit()
{
    $name = $("#name").val();
    //$remark = $("#remark").val();
    
    if($name=="")
    {
        alert("请至少提供供应商名称，其他信息可稍后提交");
    }    
    else
    {
        $("#mainform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/supplier/manage";        
}

function redirect(url) {
    window.location = url;
}
</script>
<?php

$id = 0;
$mode = "Create";
$name="";
$business="";
$address="";
$officephone = "";
//$contact="";
$remark="";
$email="";
$postring="";
$fullname="";
$fax="";
$attn="";
$attnphone = "";
if($this->mode == "Edit")
{
$mode = "Edit";
$id = $this->maindata->getId();
$name = $this->maindata->getName();
$business = $this->maindata->getBusiness();
$address = $this->maindata->getAddress();
$officephone = $this->maindata->getOfficephone();
//$contact=$this->maindata->getContact();
$remark = $this->maindata->getRemark();
$email = $this->maindata->getEmail();
$postring=$this->maindata->getPostring();
$fullname=$this->maindata->getFullname();
$fax=$this->maindata->getFax();
$attn = $this->maindata->getAttn();
$attnphone = $this->maindata->getAttnphone();
}
     
?>
<h3>供应商添加与编辑</h3>
<form id="mainform" method="post" action="/supplier/manage/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">

<div data-role="fieldcontain">
    <label for="name">供应商名称:</label>
    <input type="text" name="name" id="name" value="<?php echo $name; ?>" data-mini="true" placeholder="用于显示在网页，可以比较短">
</div>
<div data-role="fieldcontain">
    <label for="fullname">供应商全称:</label>
    <input type="text" name="fullname" id="fullname" value="<?php echo $fullname; ?>" data-mini="true" placeholder="用于显示在PO单">
</div>
<!--
<div data-role="fieldcontain">
    <label for="business">主营业务:</label>
    <input type="text" name="business" id="business" value="<?php echo $business; ?>" data-mini="true">
</div>
-->
<div data-role="fieldcontain">
    <label for="officephone">电话:</label>
    <input type="text" name="officephone" id="officephone" value="<?php echo $officephone; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="fax">传真:</label>
    <input type="text" name="fax" id="fax" value="<?php echo $fax; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="email">电子邮件:</label>
    <input type="text" name="email" id="email" value="<?php echo $email; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="address">公司地址:</label>
    <input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="attn">联系人:</label>
    <input type="text" name="attn" id="attn" value="<?php echo $attn; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="attnphone">联系人电话:</label>
    <input type="text" name="attnphone" id="attnphone" value="<?php echo $attnphone; ?>" data-mini="true">
</div>

<div data-role="fieldcontain">
    <label for="postring">PO字串:</label>
    <input type="text" name="postring" id="postring" value="<?php echo $postring; ?>" data-mini="true" placeholder="此字串用于PO单，比如LPM，代表Long Pun Machinery Pte Ltd">
</div>

<div data-role="fieldcontain">
    <label for="remark">其他说明:</label>
    <textarea cols="40" rows="8" name="remark" id="remark" ><?php echo $remark; ?></textarea>
</div>

</form> <!--main form -->
<fieldset class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><button type="submit" data-theme="d" onclick="cancel()">取消</button></div>
</fieldset>
<br><br>
