<script>
    $(document).ready(function() {
        $('#Suppliers').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
        });

    });
</script>

<div class="ui-grid-a">
    <div class="ui-block-a"><a href="/supplier/manage/add"><button data-mini="true" data-theme="a">注册供应商</button></a></div>
    <div class="ui-block-b"><a href="/supplier/manage/truncate"><button data-mini="true" data-theme="a">清空供应商</button></a></div>                    

</div>
<?
echo $this->grid("Suppliers", true)
->field('id', 'id')  
//->field('update','更新日期')
->field('name', '名称')
//->field('business', '主营业务')
->field('officephone', '电话')  
->field('email', '电子邮件')         
//->field('fax', '传真')
->field('attn', '联系人')
->field('attnphone', '联系人电话')
->field('postring', 'PO单字串')
->actionField(':action', "操作", '&nbsp;|&nbsp;')
->itemCountPerPage(30)
->paginatorEnabled(false)
//->helper(new GridHelper_Supplier())
->data($this->suppliers)
->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
<br><br>
