<script>
// http://jsfiddle.net/jaredwilli/tZPg4/4/
$(function() {
var scntDiv = $('#p_scents');
var i = $('#p_scents p').size() + 1;

$('#addScnt').live('click', function() {
        $('<p><label for="p_scnts"><input type="text" id="p_scnt" size="20" name="p_scnt_' + i +'" value="" placeholder="Input Value" /></label> <a href="#" id="remScnt">Remove</a></p>').appendTo(scntDiv);
        i++;
        return false;
});

$('#remScnt').live('click', function() { 
        if( i > 2 ) {
                $(this).parents('p').remove();
                i--;
        }
        return false;
});
});

</script>
<div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="true">
    <h3>添加新的信息类</h3>
    <input type="text" placeholder="中文名称" id="infonamechs">
    <input type="text" placeholder="英文名称" id="infonameeng">
    <button data-mini="true" data-theme="a">提交</button>
    </div>    
</div>    
<hr>
<div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="true">
    <h3>总承包单位/General Contractor</h3>
    <button data-mini="true" data-theme="a">添加一个项</button>
    <input type="text" placeholder="中文名称" id="infonamechs">
    <input type="text" placeholder="英文名称" id="infonameeng">
    <button data-mini="true" data-theme="a">提交</button>
    </div>    
</div>    

