<script>
function addinfo()
{
    var namechs = $('#namechs').val();
    var nameeng = $('#nameeng').val();

    $.post("/miscinfo/manage/addinfo", { namechs:namechs, nameeng:nameeng }, 
    function(data) {
        //console.log(data);
        alert(data);        
        window.location.reload();
    })    
}
</script>
<?php
$infos=$this->infos;
?>
<p><strong>信息列表</strong></p>
<div data-role="collapsible-set" data-mini="true" data-theme="c">
<?php
foreach($infos as $info)
{
    $id = $info->getId();
    $label = $info->getLabel();    
    $namechs=$info->getNamechs();
    $nameeng=$info->getNameeng();
    $values = $info->getValues();
    //echo "values=$values;";

    $infohtml='<div data-role="collapsible" data-collapsed="true">';
    $h3 = "<h3>$namechs/$nameeng</h3>";
    $form = '<form method="post" action="/miscinfo/manage/postinfo">';
    $hiddenid = '<input type="hidden" name="id" id="id" value="'. $id . '">';
    $hiddenlabel = '<input type="hidden" name="label" id="label" value="'. $label . '">';
    $namechshtml = '<input type="text" placeholder="中文名称" name="namechs" value="' . $namechs . '">';
    $nameenghtml = '<input type="text" placeholder="英文名称" name="nameeng" value="' . $nameeng . '"><hr>';

    $inputhtml = "";
    $count = 1;
    if($values)
    {
        $valueArr = explode(";", $values);
        foreach($valueArr as $tmp)
        {
            if($tmp != "")
            {
                $inputhtml .= '<input type="text" placeholder="添加一个字串" name="value' . $count++ . '" value="' . $tmp . '">';
            }
        }
    }
    $inputhtml .= '<input type="text" placeholder="添加一个字串" name="value' . $count . '" value="">';
    $hiddencount = '<input type="hidden" name="count" id="id" value="'. $count . '">';
    $button = '<button data-mini="true" data-theme="a">提交</button>';
    $formend = "</form>";
    $infohtml .= $h3 . $form . $hiddenid . $hiddenlabel. $hiddencount . $namechshtml . $nameenghtml . $inputhtml . $button . $formend;
    $infohtml.="</div>";
    echo $infohtml;
}
?>    

</div>    






