<script>
$(document).ready(function() {
    $('#Applications').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
} );
</script>
<?
echo $this->grid("Applications", true)
          ->field('updatedate','更新时间')
          ->field('site','工地')
          //->field('id','申请单号')
          ->field('applicant','申请人')
          //->field('createdate','创建日期')          
          //->field('status0', '申请状态')
          ->field('status1', '办公人员评估')
          ->field('status2', '负责经理评估')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->setSorting(false) 
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Application())
          ->data($this->maindata)
          ->action(':action', '详情', array( 'url'=>array('action'=>'appdetail')))
          ->action(':action', '更新', array( 'url'=>array('action'=>'appedit')))
          ->action(':action', '删除申请', array( 'url'=>array('action'=>'appdel')));
?>
<br><br>

