<!DOCTYPE html> 
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>MATERIAL REQUEST FORM</title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
</head> 

<body> 
<style>
.previewcontent { text-align: center; }
</style>
<?php
$jmtheme="c";

$cmyfullnameeng=$this->cmyfullnameeng;
$cmyaddr=$this->cmyaddr;
$cmyphone=$this->cmyphone;
$cmyfax=$this->cmyfax;
$cmyemail=$this->cmyemail;

$cmycontact=$this->cmycontact;

$formnameeng="MATERIAL REQUEST FORM";
$formnamechs="材料申请单";

?>
<div data-role="page" data-theme="<?php echo $jmtheme; ?>">
    <!--
	<div data-role="header"  data-theme="<?php echo $jmtheme; ?>">
		<h1><?php echo $cmyfullnameeng; ?></h1>
        <h4><?php echo $cmyaddr; ?></h4>
        <h4><?php echo $cmycontact; ?></h4>
	</div>--><!-- /header -->

	<div data-role="content" class="previewcontent">	
		<h3><?php echo $cmyfullnameeng; ?></h3>
        <p><?php echo $cmyaddr; ?></p>
        <p><?php echo $cmycontact; ?></p>
		<h4><?php echo $formnameeng; ?></h4>
		<h4><?php echo $formnamechs; ?></h4> 
		
	</div><!-- /content -->
	
	<div data-role="footer"  data-theme="<?php echo $jmtheme; ?>">
		<h4>Footer content</h4>
	</div><!-- /footer -->
	
</div><!-- /page -->

</body>
</html>
