<!DOCTYPE html> 
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>PURCHASE ORDER</title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
</head> 

<body> 
<style>
.previewcontent { text-align: center; }
.stayleft { float:left; }
.stayright { float:right; }
/*#previewtab { width: 100%; }*/
#previewtab
{
/*font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;*/
width:100%;
border-collapse:collapse;
}
#previewtab td, #previewtab th 
{
/*font-size:1.2em;*/
border:1px solid #98bf21;
padding:3px 7px 2px 7px;
}
#previewtab th 
{
/*font-size:1.4em;*/
text-align:center;
padding-top:5px;
padding-bottom:4px;
background-color:#A7C942;
color:#fff;
}
#previewtab tr.alt td 
{
color:#000;
background-color:#EAF2D3;
}

</style>
<?php
$jmtheme="c";

$cmyfullnameeng=$this->cmyfullnameeng;
$cmyaddr=$this->cmyaddr;
$cmyphone=$this->cmyphone;
$cmyfax=$this->cmyfax;
$cmyemail=$this->cmyemail;
$cmycontact=$this->cmycontact;
$cmypostring=$this->cmypostring;

$formnameeng="PURCHASE ORDER";
//$formnamechs="材料申请单";
$date=$this->date;
$sitename=$this->sitename;
$matapps=$this->matapps;

$supplier=$this->supplier;
$suppostring=$this->suppostring;
$supfullname=$this->supfullname;
$supofficephone=$this->supofficephone;
$supfax=$this->supfax;
$supattn=$this->supattn;
$supattnphone=$this->supattnphone;

$PONO=$suppostring;
?>
<div data-role="page" data-theme="<?php echo $jmtheme; ?>" style="page-break-after:always">
	<div data-role="content" class="previewcontent">	
		<strong><?php echo $cmyfullnameeng; ?></strong><br>
        <?php echo $cmyaddr; ?><br>
        <?php echo $cmycontact; ?><br><br>
		<strong><?php echo $formnameeng; ?></strong><br>
		
        <div class="stayright">PO NO:&nbsp;<u><?php echo $PONO; ?></u></div><br><br>

<table>
<tr>
<td>TO:&nbsp;<?php echo $supfullname; ?></td><td>Attn:&nbsp;<?php echo $supattn . "&nbsp;".$supattnphone;?></td>
</tr>

</table>
<table id="previewtab">
<tr><th>S/NO<br>序号</th><th>Description<br>材料名称</th><th>Type<br>型号规格</th>
<th>QTY<br>数量</th><th>UNIT<br>单位</th><th>REMARKS<br>备注</th></tr>

</table>
	</div><!-- /content -->
    <br>
    <div class="stayleft">Contact Person:&nbsp;<u><?php echo "XXX"; ?></u></div>
    <div class="stayright">Contact No.:&nbsp;<u><?php echo "XXX"; ?></u></div><br><br>
	
	<!--<div data-role="footer"  data-theme="<?php echo $jmtheme; ?>">
		<h4>Footer content</h4>
	</div>--><!-- /footer -->
	
</div><!-- /page -->

<div>
asdf;ajdsf;asjkdf
</div>
</body>
</html>
