<?
$this->headScript()->prependFile('/common/js/jquery-1.8.2.min.js');
?>
<!doctype html>
<html>
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headLink() ?> 
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript() ?>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Adverts Board</title>
</head>
<body>
<div id="content">
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>

