<form id="<?php echo $this->element->getFormId();?>" 
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <label for="name" class="required">Name:</label>
    <?php echo $this->element->name; ?>
    <label for="contact">Contact:</label>
    <?php echo $this->element->contact; ?>
	
    <label>&nbsp;</label>
    <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
</form>

