<form id="<?php echo $this->element->getFormId();?>" 
oms
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <p>
        <label for="name" class="required"><?=$this->translate("Name:");?></label>
	    <?php echo $this->element->name; ?>
    </p>
	
    <p>
        <label for="rooms" class="required"><?=$this->translate("Available Rooms:");?></label>
	    <?php echo $this->element->room; ?>
    </p>
		
    <p>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>





