<form id="<?php echo $this->element->getFormId();?>" 
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <p>
    	<label for="name" class="required"><?=$this->translate("Name:");?></label>
        <?php echo $this->element->name; ?>
    </p>
    <p>
        <label for="Description"><?=$this->translate("Description:");?></label>
	    <?php echo $this->element->description; ?>
    </p>
    <p>
        <label for="Description"><?=$this->translate("Type:");?></label>
	    <?php echo $this->element->deviceType; ?>
    </p>
    <!--
    <p>
        <label for="Description"><?=$this->translate("Groups:");?></label>
	    <?php echo $this->element->groups; ?>
    </p>
    -->
	
    <p>
       	<label>&nbsp;</label>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>

