<?php
$sheetarr = $this->sheetarr;
$sheet = $this->sheet;
$maindata = $this->workerarr;

$nowdate = new Datetime("now");
$thismonth = $nowdate->format("Y-m");
$thismonth1 = $nowdate->format("Ym");
$lastmonth = date('Y-m', strtotime("last month"));
$lastmonth1 = date('Ym', strtotime("last month"));

$thismonthurl = "/salary/salary/salarybymonth?sheet=$sheet&month=$thismonth";
$lastmonthurl = "/salary/salary/salarybymonth?sheet=$sheet&month=$lastmonth";

$lastmonthpayslipsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$lastmonth";
$thismonthpayslipsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$thismonth";
?>

<link rel="stylesheet"  href="/common/datebox/jqm-datebox-1.1.0.css" /> 
<script src="/common/datebox/jqm-datebox-1.1.0.core.js"></script>
<script src="/common/datebox/jqm-datebox-1.1.0.mode.calbox.js"></script>
<script src="/common/datebox/jqm-datebox-1.1.0.mode.datebox.js"></script>

<script>
    $(function() {
        document.title = "InfoX - 历史工资支出";
        
        $('#Workersdata').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
        });
    });

    $('#salarymonth').bind('datebox', function(e, passed) {
        if (passed.method === 'close') {
            //$('element').datebox('disable');
            var val = $(this).val();
            //alert(val);
            var res = val.substring(0, 7);
            $("#salaryrecords").prev(".ui-btn-inner").children().text('详细工资 ' + res);
        }
    });
    $('#receiptdate').bind('datebox', function(e, passed) {
        if (passed.method === 'close') {
            //$('element').datebox('disable');
            var val = $(this).val();
            //alert(val);
            //var res = val.substring(0, 7);            
            $("#salaryreceipts").prev(".ui-btn-inner").children().text('工资收据 ' + val);
        }
    });

    function opensalaryrecords()
    {
        var date = $('#salarymonth').val();
        if (date == "" || !date)
        {
            $('#salarymonth').datebox('open');
            return;
        }

        var res = date.substring(0, 7);

        var sheet = $("#sheetselect").val();
        var url = "/salary/salary/salarybymonth?sheet=" + sheet;
        url += "&month=" + res;
        OpenInNewTab(url);
    }

    function opensalaryreceipts()
    {
        var date = $('#salarymonth').val();
        if (date == "" || !date)
        {
            alert("请选择工资月份和收据日期");
            return;
        }

        var res = date.substring(0, 7);
        var date = $('#receiptdate').val();
        if (date == "" || !date)
        {
            alert("请选择工资月份和收据日期");
            return;
        }


        var sheet = $("#sheetselect").val();
        var url = "/salary/salary/salaryreceipts?sheet=" + sheet;
        url += "&month=" + res;
        url += "&date=" + date;
        OpenInNewTab(url);
    }

    $("#sheetselect").change(function() {
        var sheetname = $(this).val();
        var url = "/salary/salary?sheet=" + sheetname;
        redirect(url);
    });



    
    function opensitesummary()
    {
        var url = "/salary/history/site";
        OpenInNewTab(url);
    }

    function opencompanysummary()
    {
        var url = "/salary/history/company";
        OpenInNewTab(url);
    }
    
    function OpenInNewTab(url)
    {
        var win = window.open(url, '_blank');
        win.focus();
    }
    
    function redirect(url) {
        window.location = url;
    }
</script>
<input type="button" id="salarysummary" value="工地工资统计" data-mini="true" data-theme="a" 
       onclick="opensitesummary()">
<input type="button" id="salarysummary" value="公司工资统计" data-mini="true" data-theme="a" 
       onclick="opencompanysummary()">
       <?php
//echo $wdtab;
       ?>
<br><br>
