<?php
$username = $this->username;
// sites
$allsites = $this->allsites;
$currentsite = $this->currentsite;
$currentsiteid = ($currentsite != NULL) ? $currentsite->getId() : 0;
$options = "";
foreach ($allsites as $site) {
    $sid = $site->getId();
    $sname = $site->getName();
    if ($sid == $currentsiteid) {
        $option = "<option value=$sid selected>$sname</option>
                ";
    } else {
        $option = "<option value=$sid>$sname</option>
                ";
    }
    $options .= $option;
}
$siteselects = '<select id="site" name="site" data-mini="true" data-theme="b">' . $options . '</select>';

$sitesummary = $this->sitesummary;
$trs = "";
$sumAttend = 0;
$sumSalary = 0;
if (count($sitesummary)) {
    foreach ($sitesummary as $tmp) {
        $name = $tmp->getSite()->getName();
        //echo $name;
        $month = $tmp->getMonth()->format("Y-m-d");
        $attendance = $tmp->getAttendance();
        $totalsalary = $tmp->getTotalsalary();
        $tr = "<tr><td>$month</td><td>$attendance</td><td>$totalsalary</td></tr>";
        $trs .= $tr;

        $sumAttend += $attendance;
        $sumSalary += $totalsalary;
    }
}
$summarytab = "<table><tr><th>月份</th><th>考勤</th><th>工资</th></tr>"
        . "$trs" . "<tr><th>总计</th><th>$sumAttend</th><th>$sumSalary</th></tr>"
        . "</table>";

$monthfrom = $this->monthfrom;
$monthfromstr = $monthfrom ? $monthfrom->format("Y-m-d") : "";
$monthto = $this->monthto;
$monthtostr = $monthto ? $monthto->format("Y-m-d") : "";
?>
<!DOCTYPE html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>InfoX - 工地工资统计</title> 
        <link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
        <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
        <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
        <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet"  href="/common/datebox/jqm-datebox-1.1.0.css" /> 
        <script src="/common/datebox/jqm-datebox-1.1.0.core.js"></script>
        <script src="/common/datebox/jqm-datebox-1.1.0.mode.calbox.js"></script>
        <script src="/common/datebox/jqm-datebox-1.1.0.mode.datebox.js"></script>
        <link rel="shortcut icon" href="/images/gssvgabstract234.png" type="image/x-icon">
        <link rel="icon" href="/images/gssvgabstract234.png" type="image/x-icon">
    </head> 

    <body> 
        <style>
            #headertab { width: 100%; table-layout:fixed; }
            #headertab td, table th { text-align:left; border:0px solid black; text-align: center; }
            table { width: 100%; border-collapse:collapse; table-layout:fixed;}
            table td, table th { text-align:center; border:1px solid black; }
            .sumtab { table-layout: fixed; }
        </style>
        <script>
            $(function() {
                document.title = "InfoX - 工地工资统计";
            });

            function redirect(url) {
                window.location = url;
            }

            function submitsitesummary() {
                //alert("submitsitesummary");
                //console.log($("#sitesummaryform"));
                //$("#sitesummaryform").submit();
                var siteid = $("#site").val();
                var from = $("#monthfrom").val();
                var to = $("#monthto").val();

                var url = "/salary/history/site?";
                url += "&site=" + siteid;
                if (from)
                {
                    url += "&from=" + from;
                }
                if (to)
                {
                    url += "&to=" + to;
                }
                //alert(url);
                redirect(url);
            }
        </script>
        <div data-role="page">

            <div data-role="header" >
                <table id="headertab">
                    <tr>
                        <td>工资统计:工地</td>
                        <td>工资负责人:&nbsp;<?= $username ?></td>
                    </tr>
                </table>
            </div><!-- /header -->

            <form id="sitesummaryform" action="/salary/history/" method="post">
                <div class="ui-grid-b">
                    <div style="" class="ui-block-a">
                        <input id="monthfrom" name="monthfrom" placeholder="<?= "开始月份" ?>" 
                               data-role="datebox" data-options='{"mode":"datebox"}' data-mini="true" 
                               value="<?= $monthfromstr ?>">
                    </div>
                    <div class="ui-block-b"><?= $siteselects ?></div>               

                    <div style="" class="ui-block-c">
                        <input id="monthto" name="monthto" placeholder="<?= "结束月份" ?>" 
                               data-role="datebox" data-options='{"mode":"datebox"}' data-mini="true"
                               value="<?= $monthtostr ?>">
                    </div>               
                    <div style="" class="ui-block-a">
                    </div>
                    <div class="ui-block-b">
                        <input type="button" value="计算工资统计数据" data-mini="true" data-theme="b" onclick="submitsitesummary()">
                    </div>
                </div>

            </form>

            <div data-role="content">
                <div id="error">
                    <?= $this->error ?>
                </div>
                <?= $summarytab ?>
            </div><!-- /content -->

            <div data-role="footer">
                <!--<h4>Footer content</h4>-->
            </div><!-- /footer -->

        </div><!-- /page -->

    </body>
</html>

