<!DOCTYPE html> 
<html>

<?php
$date=$this->date;
$monthstr=$date->format("Y-m");

$site=$this->site;
$sitename=$site->getName();
$siteid=$this->siteid;

$workerarr=$this->workerarr;
$attendancearr=$this->attendancearr;

$workerhtmls=$this->workerhtmls;
?>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>考勤<? echo $monthstr; ?></title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
</head> 

<body> 
<style>
table { width: 100%; border-collapse:collapse; }
table td, table th { text-align:center; border:1px solid gray; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}
</style>
<script>
function quicksubmit()
{
    //alert("quicksubmit");
    var date = $("#date").val();
    //alert("date="+date);
    var r=confirm("日期:"+date+"\n确认提交该天的考勤吗？");
    if (r==false)
    {
        return false;
    }

    $("#quickdate").val(date);

    /*
    $.post("/project/attendance/postsalary", { wid:wid, date:date, salary:salary, remark:remark, month:month }, 
    function(data) {
        console.log(data);
        //alert(data);        
        //window.location.reload();
    });  
    */
    $("#quickform").submit();

    /*
    $( "#quickform" ).submit(function( event ) {
      alert( "Handler for .submit() called." );
      //event.preventDefault();
      //  window.location.reload();
    });
    */
}

/*
$(function() { 
    var date = $("#date").val();
    //alert(date);
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month);
});
*/

function post()
{
    alert("post");
}
</script>
<div data-role="page">

	<div data-role="header">
		<!--<h1>Single page</h1>-->
<table style="table-layout:fixed;">
<tr>
<td><? echo "工地名称: " . $sitename; ?></td>
<td><? echo "月份: " . $monthstr; ?></td>
<td><? echo "工资负责人: " . ""; ?></td>
</tr>
</table>
	</div><!-- /header -->

	<div data-role="content">
<?php
foreach($workerhtmls as $tmp)
{
    //echo $tmp . "<br>";    
    $tab1 = $tmp[0];
    $tab2 = $tmp[1];

    echo $tab1. "<br>" . $tab2;
}
?>


<div style="float:right;">
<?php
$url = "/project/attendance/attendquick?" . "&sid=$siteid&month=$monthstr";   
$ahref= '<a href="' . $url . '" data-rel="dialog" data-role="button" >快速考勤</a>';    
echo $ahref;
?>
</div>

<table>
<tr>
<th rowspan="2">序号</th><th colspan=4>工人信息</th><!--<th rowspan="2">考勤方式</th>--><th colspan=31>日期</th>
<th rowspan="2">考勤</th><th rowspan="2">详细</th></tr>
<tr><th>准证</th><th>姓名</th><th>单价</th><th>工种</th>
<?php
$days=31;
$ths="";
for($i=0; $i<$days; $i++)
{
    $j = $i+1;
    if($j<10)
    {
        $th = "<th>0$j</th>";
    }
    else
    {
        $th = "<th>$j</th>";
    }
    $ths .= $th;
}
echo $ths;
?>
</tr>
<?php
$trs="";
$sn=0;
foreach($workerarr as $tmp)
{
    $tr="";
    $sn++;
    $td="<td>$sn</td>";
    $tr .= $td;

    $wpno=$tmp->getWpno();
    $td="<td>$wpno</td>";
    $tr .= $td;
    
    $name=$tmp->getNamechs();
    if(!$name || $name=="")
    {
        $name = $tmp->getNameeng();
    }
    $td="<td>$name</td>";
    $tr .= $td;

    $price = 75;
    $td="<td>$price</td>";
    $tr .= $td;
    
    $worktype=$tmp->getWorktype();
    $td="<td>$worktype</td>";
    $tr .= $td;

    $workerid = $tmp->getId();
    $attentds = getAttenTds($attendancearr, $workerid);
    $tr .= $attentds;

    //$tds = '<td><button data-mini="true">考勤</button></td>'; 
    $url = "/project/attendance/attendialog?" . "&sid=$siteid&month=$monthstr&wid=$workerid";   
    $tds = '<td><a href="' . $url . '" data-rel="dialog" data-role="button" data-mini="true">考勤</a></td>';    
    $tr .= $tds;

    $tds = '<td><button data-mini="true">详细</button></td>';    
    $tr .= $tds;
    
    $trs .= "<tr>$tr</tr>";        
}

function getAttenTds($attendancearr, $workerid)
{
    $attenobj=null;
    if(count($attendancearr)>0)
    {
        foreach($attendancearr as $atten)
        {
            $worker = $atten->getWorker();
            if($worker->getId() == $workerid)
            {
                $attenobj = $atten;
                break;
            }
        }
    }

    $tds = "";

    if(1 && $attenobj)
    {

    $value = $attenobj->getDay1();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay2();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay3();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay4();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay5();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay6();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay7();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay8();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay9();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay10();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay11();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay12();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay13();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay14();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay15();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay16();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay17();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay18();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay19();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay20();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay21();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay22();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay23();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay24();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay25();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay26();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay27();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay28();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay29();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay30();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay31();
    $tds .= "<td>$value</td>";
    }
    else
    {
        for($i=0; $i<31; $i++)
        {
            $tds .= "<td>&nbsp;</td>";
        }
    }

    return $tds;        
}
echo $trs;
?>
</table>


	</div><!-- /content -->
	
	<div data-role="footer">
		<!--<h4>Footer content</h4>-->
	</div><!-- /footer -->
	
</div><!-- /page -->

</body>
</html>

