<!DOCTYPE html> 
<html>
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>工人考勤</title> 
	<link rel="stylesheet"  href="/common/css/jquery.mobile-1.2.0.css" />  
	<script src="/common/js/jquery-1.8.2.min.js"></script>
	<script src="/common/js/jquery.mobile-1.2.0.min.js"></script>

    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
    </head> 
<body> 

<style>
table {width: 100%; border-collapse:collapse;}
table td, table th { text-align:center; border:1px solid gray; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}
</style>	
<script>
/*
function post()
{
    var date = $("#date").val();
    //alert(date);
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $.post("/project/attendance/postsalary", { wid:wid, date:date, salary:salary, remark:remark, month:month }, 
    function(data) {
        console.log(data);
        //alert(data);        
        //window.location.reload();
    })  
    
}

$(function() { 
    var date = $("#date").val();
    //alert(date);
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month);
});
*/
/*

$("#date").change(function() {
  alert( "Handler for .change() called." );
});


$( "input[type='date']" ).change(function() {
  // Check input( $( this ).val() ) for validity here
    alert("date change");
});

$( ".ui-btn" ).click(function() {
    alert("clicked");
});



$(function() { 
$( ".ui-body-c" ).click(function() {
    var date= $("#date").val();    
    alert(date);    
});

});
*/

</script>
<?php
$site=$this->site;
$sitename=$site->getName();
$siteid=$site->getId();
 
$attendance=$this->attendance;

$date=$this->date;
$monthstr=$this->monthstr;

$workerarr=$this->workerarr;
$attendancearr=$this->attendancearr;

?>

<div data-role="dialog">
    <div data-role="header" data-theme="d">
	    <h1>工地:&nbsp;<? echo "$sitename&nbsp;"; ?>&nbsp;&nbsp;月份:&nbsp;<? echo "$monthstr&nbsp;"; ?></h1>
    </div>

    <div data-role="content" data-theme="c">

    <div style="float:left;max-width:500px;min-width:400px;">
    <input type="date" name="date" id="date" value=""  />	
    </div>
    <div style="float:left;">&nbsp;</div>

    <!--<div style="margin: 10px auto 15px auto; max-width:65%;">-->
    <div style="float:left; width:65%;">
<form action="/project/attendance/quicksubmit" method="post" name="quickform" id="quickform">
<input type="hidden" name="quickdate" id="quickdate" value="">
<input type="hidden" name="sid" id="sid" value="<? echo $siteid; ?>">
<table style="width:100%;margin-top:10px;">
<tr>
<th rowspan="2">序号</th><th colspan=4>工人信息</th><th rowspan=2 class="tdattendfood">工作小时</th><th rowspan=2 class="tdattendfood">伙食</th></tr>
<tr><th>准证</th><th>姓名</th><th>单价</th><th>工种</th></tr>
<?php
$attendoptions="";
$attendoptions=getAttendoptions();
$trs="";
$sn=0;
foreach($workerarr as $tmp)
{
    $tr="";
    $sn++;
    $td="<td>$sn</td>";
    $tr .= $td;

    $wpno=$tmp->getWpno();
    $td="<td>$wpno</td>";
    $tr .= $td;
    
    $name=$tmp->getNamechs();
    if(!$name || $name=="")
    {
        $name = $tmp->getNameeng();
    }
    $td="<td>$name</td>";
    $tr .= $td;

    $price = 75;
    $td="<td>$price</td>";
    $tr .= $td;
    
    $worktype=$tmp->getWorktype();
    $td="<td>$worktype</td>";
    $tr .= $td;

    $workerid = $tmp->getId();
    $attentds = getAttenTds($attendancearr, $workerid, $attendoptions);
    $tr .= $attentds;

    $trs .= "<tr>$tr</tr>";        
}

function getAttendoptions()
{
    $options="";
    for($count=0;$count<29;$count++)
    {
        $hours = 2 + $count * 0.5;
        $option = "<option value=$hours>$hours" . "小时</option>";
        if($hours==8)
        {
            $option = "<option value=$hours selected>$hours" . "小时</option>";
        }
        $options .= $option;
    }

    return $options;
}

function getAttenTds($attendancearr, $workerid, $attendoptions)
{
    //echo $options;
    $attend = '<td><select name="attend' . $workerid .'" id="attend' . $workerid . '" data-theme="b" data-mini="true">'
                . $attendoptions .'</select></td>';

    $food = '<td><select name="food' . $workerid .'" id="food' . $workerid . '" data-role="slider" data-theme="b">
				<option value="1">有</option>
				<option value="0">无</option>
			</select></td>';
    //$food="<td>&nbsp;</td>";
    return $attend . $food ;
}

// static means: just static html
function getStaticAttenTds($attendancearr, $workerid)
{
    $options="";
    for($count=0;$count<29;$count++)
    {
        $hours = 2 + $count * 0.5;
        $option = "<option value=$hours>$hours" . "小时</option>";
        if($hours==8)
        {
            $option = "<option value=$hours selected>$hours" . "小时</option>";
        }
        $options .= $option;
    }
    //echo $options;
    $attend = '<td><select name="attend' . $workerid .'" id="attend' . $workerid . '" data-theme="b" data-mini="true">'
                . $options .'</select></td>';

    $food = '<td><select name="food' . $workerid .'" id="food' . $workerid . '" data-role="slider" data-theme="b">
				<option value="1">有</option>
				<option value="0">无</option>
			</select></td>';
    //$food="<td>&nbsp;</td>";
    return $attend . $food ;
}

echo "$trs";
//$tr= '<tr><td colspan=6><button onclick="quicksubmit()">提交</button></td></tr>';
//echo $tr;
?>
</table>
</form>
<button onclick="quicksubmit()">提交考勤</button>
<br>
<input type="button" value="关闭本页" onclick="attendialogclose()">
    </div>

	</div>
	</div> <!-- dialog -->

</body>
</html>

