<!DOCTYPE html> 
<html>

<?php
$date=$this->date;
$monthstr=$date->format("Y-m");

$site=$this->site;
$sitename=$site->getName();
$siteid=$this->siteid;

$workerarr=$this->workerarr;
$attendancearr=$this->attendancearr;

$workerhtmls=$this->workerhtmls;
?>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>考勤<? echo $monthstr; ?></title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
</head> 

<body> 
<style>
table { width: 100%; border-collapse:collapse; }
table td, table th { text-align:center; border:1px solid black; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}

.attendsum  { background-color:#D0D0D0; }
.fixwidthcol { width:45px; }
.tdattendfood { width:150px; }
</style>
<script>
function quicksubmit()
{
    //alert("quicksubmit");
    var date = $("#date").val();
    //alert("date="+date);
    var r=confirm("日期:"+date+"\n确认提交该天的考勤吗？");
    if (r==false)
    {
        return false;
    }

    $("#quickdate").val(date);

    /*
    $.post("/project/attendance/postsalary", { wid:wid, date:date, salary:salary, remark:remark, month:month }, 
    function(data) {
        console.log(data);
        //alert(data);        
        //window.location.reload();
    });  
    */
    $("#quickform").submit();

    /*
    $( "#quickform" ).submit(function( event ) {
      alert( "Handler for .submit() called." );
      //event.preventDefault();
      //  window.location.reload();
    });
    */
}

/*
$(function() { 
    var date = $("#date").val();
    //alert(date);
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month);
});
*/

function post()
{
    var date = $("#date").val();
    //alert(date); return;    
    var wid = $("#wid").val();
    //console.log(wid); return;
    var attend = $("#attend").val();
    var food = $("#food").val();
    var remark = $("#remark").val();
    var month = $("#month").val();
    var siteid = $("#siteid").val();

    $.post("/project/attendance/postattend", { wid:wid, date:date, attend:attend, remark:remark, month:month, food:food }, 
    function(data) {
        //console.log(data);
        $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month + "&sid="+siteid);
        alert("提交成功，请继续考勤");
        //window.location.reload();
    })  
    
}
</script>
<div data-role="page">

	<div data-role="header">
		<!--<h1>Single page</h1>-->
<table style="table-layout:fixed;">
<tr>
<td><? echo "工地名称: " . $sitename; ?></td>
<td><? echo "月份: " . $monthstr; ?></td>
<td><? echo "工资负责人: " . ""; ?></td>
</tr>
</table>
	</div><!-- /header -->

	<div data-role="content">
<!--<div style="float:right;">-->
<input type="hidden" id="siteid" name="siteid" value="<? echo $siteid; ?>">
<div>
<?php
$url = "/project/attendance/attendquick?" . "&sid=$siteid&month=$monthstr";   
$ahref= '<a href="' . $url . '" data-rel="dialog" data-role="button" data-theme="b" >快速考勤</a>';    
echo $ahref;
?>
</div>

<?php
foreach($workerhtmls as $tmp)
{
    //echo $tmp . "<br>";    
    $tab1 = $tmp[0];
    $tab2 = $tmp[1];

    echo $tab1. $tab2 . "<br>";
}
?>
	</div><!-- /content -->
	
	<div data-role="footer">
		<!--<h4>Footer content</h4>-->
	</div><!-- /footer -->
	
</div><!-- /page -->

</body>
</html>

