<!DOCTYPE html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>工人考勤</title> 
        <link rel="stylesheet"  href="/common/css/jquery.mobile-1.2.0.css" />  
        <script src="/common/js/jquery-1.8.2.min.js"></script>
        <script src="/common/js/jquery.mobile-1.2.0.min.js"></script>

        <!--<link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
        <script src="/common/js/jQuery.ui.datepicker.js"></script>
        <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
        <script>
            //reset type=date inputs to text
            $(document).bind("mobileinit", function() {
                $.mobile.page.prototype.options.degradeInputs.date = true;
            });
        </script>-->
    </head> 
    <body> 

        <style>
            table {width: 100%; border-collapse:collapse;}
            table td, table th { text-align:center; border:1px solid black; }
            .ui-dialog-contain {
                width: 92.5%;
                max-width: 2500px;
                margin: 3% auto 15px auto;
                padding: 0;
                position: relative;
                top: -15px;
            }

            #datetab { table-layout: fixed;
            }
            input{
                text-align:center;
            }

            input.ui-input-text 
            {
                color: red;
            }
        </style>	
        <script>
            /*
             $(function() {
             $(".dayvalue").blur(function() {
             //alert("Handler for .blur() called.");
             // post data to attend
             var wid = $("#wid").val();
             var month = $("#month").val();
             var id = $(this).attr("id");
             var data = $(this).val();
             
             var url = "/project/attendance/savedailyinput";
             $.post(url, {wid:wid, month:month, id:id, data:data}, function(data) {
             console.log(data);
             })
             });
             });
             */
            function post()
            {
                var date = $("#date").val();
                alert(date);
                return;

                var wid = $("#wid").val();
                //console.log(wid);
                var salary = $("#salary").val();
                var remark = $("#remark").val();
                var month = $("#month").val();

                $.post("/project/attendance/postattend", {wid: wid, date: date, salary: salary, remark: remark, month: month},
                function(data) {
                    console.log(data);
                    //alert(data);        
                    //window.location.reload();
                })

            }

            function attendialogpost()
            {
                var form = $('#attendform').serialize();
                console.log(form);
                var wid = $("#wid").val();
                var month = $("#month").val();
                var url = "/project/attendance/postattendmonth";
                $.post(url, form, function(data) {
                    console.log(data);
                    $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month=" + month);
                    alert("提交成功，请继续考勤");
                });
            }

        </script>
        <?php
        $worker = $this->workerdetails;
        $wid = $worker->getId();
        $wpno = $worker->getWpno();
        $wname = $worker->getNamechs();
        if (!$wname || $wname == "") {
            $wname = $worker->getNameeng();
        }

        $site = $this->site;
        $sitename = $site->getName();

        $attendance = $this->attendance;

        $date = $this->date;
        $monthstr = $this->monthstr;

        $workersummarytab = $this->workersummarytab;

        $datetab = $this->datetab;
        ?>

        <div data-role="dialog">
            <div data-role="header" data-theme="d">
                <h1><?= $sitename?>&nbsp;<?= $monthstr ?>&nbsp;考勤</h1>
            </div>

            <div data-role="content" data-theme="c">
                <div id="attensheet">
                    <?=$workersummarytab ?>
                </div>
                <br>
                <div>
                    <form id="attendform">                    
                        <input type="hidden" name="wid" id="wid" value="<?= $wid ?>">
                        <input type="hidden" name="month" id="month" value="<?= $monthstr ?>">
                        <?= $datetab ?>
                    </form>
                    <input type="button" value="提交考勤" onclick="attendialogpost()">
                    <input type="button" value="关闭本页" onclick="attendialogclose()">
                </div>                           

            </div>
        </div> <!-- dialog -->

    </body>
</html>

