<!DOCTYPE html> 
<html>
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>工人考勤</title> 
	<link rel="stylesheet"  href="/common/css/jquery.mobile-1.2.0.css" />  
	<script src="/common/js/jquery-1.8.2.min.js"></script>
	<script src="/common/js/jquery.mobile-1.2.0.min.js"></script>

    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
    </head> 
<body> 

<style>
table {width: 100%; border-collapse:collapse;}
table td, table th { text-align:center; border:1px solid black; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}
</style>	
<script>
function post()
{
    var date = $("#date").val();
    alert(date); return;
    
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $.post("/project/attendance/postattend", { wid:wid, date:date, salary:salary, remark:remark, month:month }, 
    function(data) {
        console.log(data);
        //alert(data);        
        //window.location.reload();
    })  
    
}

/*
$(function() { 
    alert("xxxxx");

    var date = $("#date").val();
    //alert(date);
    var wid = $("#wid").val();
    //console.log(wid);
    var salary = $("#salary").val();
    var remark = $("#remark").val();
    var month = $("#month").val();

    $('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month);
});
*/
</script>
<?php
$worker=$this->workerdetails;
$wid=$worker->getId();
$wpno=$worker->getWpno();
$wname=$worker->getNamechs();
if(!$wname || $wname=="")
{
    $wname = $worker->getNameeng();
}

$site=$this->site;
$sitename=$site->getName();

$attendance=$this->attendance;

$date=$this->date;
$monthstr=$this->monthstr;

$workerattendtabs=$this->workerattendtabs;
?>

<div data-role="dialog">
    <div data-role="header" data-theme="d">
	    <h1><? echo "$sitename&nbsp;"; ?>考勤</h1>
    </div>

    <div data-role="content" data-theme="c">
<div id="attensheet">

</div>
    <div>

<!--<table>
<tr><th colspan=4>工人信息</th><th colspan=31>日期</th></tr>
<tr><th>准证</th><th>姓名</th><th>单价</th><th>工种</th>
<?php

$days=31;
$ths="";
for($i=0; $i<$days; $i++)
{
    $j = $i+1;
    if($j<10)
    {
        $th = "<th>0$j</th>";
    }
    else
    {
        $th = "<th>$j</th>";
    }
    $ths .= $th;
}
echo $ths;
echo "</tr>";

$trs="";
$tmp=$worker;
{
    $tr="";

    $wpno=$tmp->getWpno();
    $td="<td>$wpno</td>";
    $tr .= $td;
    
    $name=$tmp->getNamechs();
    if(!$name || $name=="")
    {
        $name = $tmp->getNameeng();
    }
    $td="<td>$name</td>";
    $tr .= $td;

    $price = 75;
    $td="<td>$price</td>";
    $tr .= $td;
    
    $worktype=$tmp->getWorktype();
    $td="<td>$worktype</td>";
    $tr .= $td;

    $workerid = $tmp->getId();
    $attentds = getAttenTds($attendance);
    $tr .= $attentds;
   
    $trs .= "<tr>$tr</tr>";        
}

function getAttenTds($attenobj)
{
    $tds = "";

    if(0 && $attenobj)
    {
    $value = $attenobj->getDay1();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay2();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay3();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay4();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay5();
    $tds .= "<td>$value</td>";
    $value = $attenobj->getDay6();
    $tds .= "<td>$value</td>";
    }
    else
    {
        for($i=0; $i<31; $i++)
        {
            $tds .= "<td>&nbsp;</td>";
        }
    }

    return $tds;
}
//echo $trs;

?>
</table>-->
<? echo $workerattendtabs[0] . $workerattendtabs[1]; ?>
    </div>

    <div style="float:left;width:43%;">
    <!--<label for="date">Date Input:</label>-->
    <input type="date" name="date" id="date" value=""  />	
    </div>

    <div style="float:right;width:53%;">
	    <div data-role="fieldcontain">
     	    <label for="attend">工时:</label>
            <select name="attend" id="attend" data-theme="b" >
				<option value="2">2小时</option>
                <option value="3">3小时</option>
                <option value="4">4小时</option>
                <option value="5">5小时</option>
                <option value="6">6小时</option>
                <option value="7">7小时</option>
                <option value="8" selected>8小时</option>
                <option value="9">9小时</option>
                <option value="10">10小时</option>
                <option value="11">11小时</option>
                <option value="12">12小时</option>
                <option value="13">13小时</option>
                <option value="14">14小时</option>
                <option value="15">15小时</option>
                <option value="16">16小时</option>
			</select>
	    </div>	
	    <div data-role="fieldcontain">
     	    <label for="food">伙食:</label>
            <!--<select name="food" id="food" data-role="slider" data-theme="b" style="width:100%">-->
            <select name="food" id="food" data-theme="b" >
				<option value="1">有</option>
				<option value="0">无</option>
			</select>	    
        </div>	

	    <div data-role="fieldcontain">
     	    <label for="remark">备注:</label>
     	    <input type="text" name="remark" id="remark" value="" placeholder="请假缺勤信息等" />
	    </div>	
        <input type="hidden" name="wid" id="wid" value="<? echo $wid; ?>">
        <input type="hidden" name="month" id="month" value="<? echo $monthstr; ?>">
        <input type="button" value="提交" onclick="post()">
    </div>

	</div>
	</div> <!-- dialog -->

</body>
</html>

