<!DOCTYPE html> 
<html>

<?php
$date=$this->date;
$monthstr=$date->format("Y-m");

$site=$this->site;
$sitename=$site->getName();

$workerarr=$this->workerarr;
?>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>考勤<? echo $monthstr; ?></title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>
</head> 

<body> 
<style>
table {width: 100%; border-collapse:collapse;}
table td, table th { text-align:center; border:1px solid black; }
</style>
<div data-role="page">

	<div data-role="header">
		<!--<h1>Single page</h1>-->
<table>
<tr>
<td style="width:33%"><? echo "工地名称: " . $sitename; ?></td>
<td style="width:33%"><? echo "月份: " . $monthstr; ?></td>
<td style="width:33%"><? echo "工资负责人: " . ""; ?></td>
</tr>
</table>
	</div><!-- /header -->

	<div data-role="content">
<!--	
<table>
<tr><th rowspan="2">序号</th><th colspan=4>工人信息</th><th colspan=2>正常工作</th><th colspan=3>加班工作</th><th colspan=2>总工作</th><th rowspan="2">考勤天数</th><th colspan=2>缺勤罚款</th><th rowspan=2>总工资</th></tr>
<tr><th>准证</th><th>姓名</th><th>单价</th><th>工种</th><th>小时</th><th>金额</th><th>单价</th><th>小时</th><th>金额</th><th>小时</th><th>金额</th><th>天数</th><th>金额</th></tr>
</table>
-->
<table>
<tr>
<th rowspan="2">序号</th><th colspan=4>工人信息</th><th rowspan="2">考勤方式</th><th colspan=31>日期</th>
<th rowspan="2">考勤</th><th rowspan="2">详细</th></tr>
<tr><th>准证</th><th>姓名</th><th>单价</th><th>工种</th>
<?php
$days=31;
$ths="";
for($i=0; $i<$days; $i++)
{
    $j = $i+1;
    $th = "<th>$j</th>";
    $ths .= $th;
}
echo $ths;
?>
<!--<th><button data-mini="true">考勤</button></th><th><button data-mini="true">详细</button></th>-->
</tr>
<?php
$trs="";
$sn=0;
foreach($workerarr as $tmp)
{
    $tr="";
    $sn++;
    $td="<td>$sn</td>";
    $tr .= $td;

    $wpno=$tmp->getWpno();
    $td="<td>$wpno</td>";
    $tr .= $td;
    
    $name=$tmp->getNamechs();
    if(!$name || $name=="")
    {
        $name = $tmp->getNameeng();
    }
    $td="<td>$name</td>";
    $tr .= $td;

    $price = 75;
    $td="<td>$price</td>";
    $tr .= $td;
    
    $worktype=$tmp->getWorktype();
    $td="<td>$worktype</td>";
    $tr .= $td;

    $trs .= "<tr>$tr</tr>";        
}
echo $trs;
?>
</table>


	</div><!-- /content -->
	
	<div data-role="footer">
		<!--<h4>Footer content</h4>-->
	</div><!-- /footer -->
	
</div><!-- /page -->

</body>
</html>

