<style>
.wizard { text-align:center; }
</style>
<script>
$('#sites').change(siteReload);
function siteReload()
{
    var siteid = $("#sites").val();    

    var url = "/project/attendance?";
    url += "&siteid=" + siteid;
    //alert(url);
    redirect(url);
}

function redirect(url) 
{
	window.location = url;
}

function openpage(datestr)
{
    alert(datestr);
    $siteid = $("#siteid").val();

    var url = "/project/attendance/"
    window.open(datestr);
}
</script>
<?php
$siteid=0;
$siteid=$this->siteid;
$sites=$this->sites;
$workingmonths=$this->workingmonths;
?>

<input id="siteid" value="<? echo $siteid; ?>">
<select id="sites" data-mini="true">
<option value=0>请选择工地</option>
<?php
$options = '';
foreach($sites as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();

    if($siteid == $id)
    {
        echo '<option value="' . $id . '" selected>' . $name . "</option>";
    }
    else
    {
        echo '<option value="' . $id . '" >' . $name . "</option>";
    }
}
echo $options;
?>
</select>

<fieldset>
<legend>选择月份</legend>
<div class="ui-grid-d">
<?php
$count=0;
$grids="";
foreach($workingmonths as $tmp)
{
    //$oncount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $datestr = $tmp->format("Y-m");    
    $datestr1 = $tmp->format("Ym");    
    $button = '<button data-mini="true" onclick="openpage(' . $datestr1 . ')">'. $datestr . "</button>";

    $grid = '<div class="ui-block-' . $block . '">' . $button . "</div>\n";
    $grids .= $grid;      
}
echo $grids;
?>
</div>
</fieldset>
<br>

