<script>
    $(function() {
        $('#Workersonsite').dataTable({
            "iDisplayLength": 100,
            "bRetrieve": true,
             "aaSorting": [[0,'desc']],
        });

        var siteid = $("#sites").val();
        if (siteid == 0)
        {
            $("#contentdiv").hide();
        }
    });

    $('#sites').change(siteReload);
    function siteReload()
    {
        var siteid = $("#sites").val();

        var url = "/project/attendance?";
        url += "&siteid=" + siteid;
        //alert(url);
        redirect(url);
    }

    function redirect(url)
    {
        window.location = url;
    }

    function openpage(datestr)
    {
        $siteid = $("#siteid").val();

        var url = "/project/attendance/attendancepage?";
        url += "&siteid=" + $siteid;
        url += "&month=" + datestr;
        //alert(url);

        window.open(url);
    }
</script>
<?php
$siteid = $this->siteid;
$sites = $this->sites;
$workingmonths = $this->workingmonths;

$style = "";
if ($this->error != "") {
    $style = "display:none;";
}

$workersonsite = $this->workersonsite;
?>

<input type="hidden" id="siteid" value="<? echo $siteid; ?>">

<div id="error">
    <?= $this->error ?>
</div>

<select id="sites" data-mini="true" data-theme="a">
    <option value=0>选择工地进行考勤</option>
    <?php
    $options = '';
    foreach ($sites as $tmp) {
        $id = $tmp->getId();
        $name = $tmp->getName();

        if ($siteid == $id) {
            $option = '<option value="' . $id . '" selected>' . $name . "</option>";
        } else {
            $option = '<option value="' . $id . '" >' . $name . "</option>";
        }
        $options .= $option;
    }
    echo $options;
    ?>
</select>

<div id="contentdiv">
    <fieldset>
        <legend>选择月份</legend>
        <div class="ui-grid-d">
            <?php
            $nowdate = new Datetime("now");
            $currentmonth = $nowdate->format("m");
            $currentyear = $nowdate->format("Y");
            $count = 0;
            $grids = "";
            if (count($workingmonths)) {
                foreach ($workingmonths as $tmp) {
                    //$oncount++;
                    $count++;
                    $block = "a";
                    switch ($count) {
                        case 1:
                            $block = "a";
                            break;
                        case 2:
                            $block = "b";
                            break;
                        case 3:
                            $block = "c";
                            break;
                        case 4:
                            $block = "d";
                            break;
                        case 5:
                            $block = "e";
                            $count = 0;
                            break;
                    }

                    $datestr = $tmp->format("Y-m");
                    $datestr1 = $tmp->format("Ym");

                    $year = $tmp->format("Y");
                    $month = $tmp->format("m");
                    if ($year == $currentyear && $month == $currentmonth) {
                        $button = '<button data-mini="true" onclick="openpage(' . $datestr1 . ')" data-theme="a">' . $datestr . "</button>";
                    } else {
                        $button = '<button data-mini="true" onclick="openpage(' . $datestr1 . ')">' . $datestr . "</button>";
                    }

                    $grid = '<div class="ui-block-' . $block . '">' . $button . "</div>\n";
                    $grids .= $grid;
                }
            }
            echo $grids;
            ?>
        </div>
    </fieldset>
    <h4>工地工人列表</h4>
    <?php
//echo 'workers no=' . count($workersonsite);
    echo $this->grid("Workersonsite", true)
            //->field('sn', 'SN')
            ->field('eeeno', 'Eee No')
            ->field('namechs', 'Name ')
            //->field('nameeng', 'Name Eng')
            ->field('site', '所在工地')
            ->field('begindate', '起始日期')
            ->field('enddate', '结束日期')
            //->field('enddate1','结束日期')
            //->field('site1', '所在工地') 
            //->field('payment1', '考勤方式')  
            //->actionField(':action', "", '&nbsp;|&nbsp;')
            ->paginatorEnabled(false)
            ->setSorting(false)
            //->helper(new GridHelper_Workeronsite())
            ->helper(new GridHelper_Workerdetails())
            ->data($workersonsite);
    ?>
</div>
<br><br>

