<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<script>
$(function () {
    //alert("scroller");
    $('.datepicker').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  
});

function addrecord()
{
    var site = $("#reason").val();
    //alert("addrecord site="+site);    
    if(site == 0)
    {
        alert("请选择一个事由");
        return;
    }    

    $("#addrecordform").submit();
}

function updaterecord(id)
{
    var begindate = $("#begindate" + id).val();
    var enddate = $("#enddate" + id).val();
    var days = $("#days" + id).val();
    var reason = $("#reason" + id).val();
    var remark = $("#remark" + id).val();    

    $.post("/worker/onsite/updateattendancerecord", 
        { id:id, begindate:begindate, enddate:enddate, days:days, reason:reason, remark:remark }, 
        function(data) {
            alert(data);
            //console.log(data);            
            window.location.reload();
    });
}

function deleterecord(id)
{
    $.post("/worker/onsite/deleteattendancerecord", 
        { id: id }, 
        function(data) {
            alert(data);
            //console.log(data); 
            window.location.reload();
    });    
}
</script>
<?php
$worker=$this->worker;
$nameeng=$worker->getNameeng();
$namechs=$worker->getNamechs();
$id=$this->id;

$reasons=$this->reasons;
?>

<h3>考勤记录 - <?php echo $namechs . "/" . $nameeng; ?></h3>
<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="false">
<h3>详细记录</h3>
<?
echo $this->grid("Recordedit", true)
          ->field('begindate1','起始日期')
          ->field('enddate1','结束日期')
          ->field('days1', '天数')
          ->field('reason1', '原因')
          ->field('remark1', '其他说明')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Workeronsite())
          ->data($this->records);
?>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>添加记录</h3>
<form method="post" action="/worker/onsite/addattendancerecord" id="addrecordform">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<table class="grid">
<tr>
<td>
<div data-role="fieldcontain">
<label for="begin">开始日期:</label>
<input type="text" name="begin" id="begin" class="datepicker" value="" data-mini="true" placeholder="点击选择日期"/>
</div>
</td>
<td>
<div data-role="fieldcontain">
<label for="end">结束日期:</label>
<input type="text" name="end" id="end" class="datepicker" value="" data-mini="true" placeholder="点击选择日期"/>
</div>
</td>
</tr>

<tr>
<td>
<div data-role="fieldcontain">
<label for="days">天数:</label>
<input type="text" name="days" id="days" value="" data-mini="true" placeholder="天数, 0.5,1,2..."/>
</div>
</td>
<td>
</td>
</tr>

<tr>
<td>
<div data-role="fieldcontain">
<label for="reason">选择事由:</label>
<select name="reason" id="reason">
<option value="0"></option>
<?php
$options="";
foreach($reasons as $tmp)
{
    if($tmp=="") 
    {
        continue;
    }
    $option = '<option value="' . $tmp . '">' . $tmp . '</option>';
    $options .= $option; 
}
echo $options;
?>
</select>
</div>
</td>
<td>
<div data-role="fieldcontain">
<label for="remark">其他说明:</label>
<input type="text" name="remark" id="remark" value="" data-mini="true" placeholder="填写补充说明"/>
</div>
</td>
</tr>

</table>
<input type="button" onclick="addrecord()" value="添加" data-mini="true" data-theme="a">
</form>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>编辑记录</h3>
<?
echo $this->grid("Recordedit", true)
          ->field('begindate','起始日期')
          ->field('enddate','结束日期')
          ->field('days', '天数')
          ->field('reason', '原因')
          ->field('remark', '其他说明')  
          ->field('update', '更新')
          ->field('delete', '删除')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Workeronsite())
          ->data($this->records);
?>
</div>

</div>

<br><br>
