<?
echo $this->grid("Workersdata", true)
          ->field('id','编号')
          ->field('nameeng','英名字')
          ->field('namechs','中文名')
          ->field('fin','准证号码')
          //->field('company', '所在公司')
          ->field('site', '所在工地')  
          ->field('passexp', '准证到期') 
          ->field('securityexp', '安全证到期')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Worker())
          ->data($this->workersdata)
          ->action(':action', '记录管理', array( 'url'=>array('action'=>'onsiterecord')));
?>
<br>
