<style>
    #Workersdata { table-layout: fixed; }
</style>
<script>
    $(function() {
        $('#Workersdata').dataTable({
            "iDisplayLength": 100,
            "bRetrieve": true,
            "aaSorting": [[0, "desc"]],
        });
    });

    $("#sheetselect").change(function() {
        var sheetname = $(this).val();
        var url = "/worker/onsite?sheet=" + sheetname;
        redirect(url);
    });

    function redirect(url) {
        window.location = url;
    }
</script>
<?php
$sheet = $this->sheet;
$sheetarr = $this->sheetarr;
$maindata = $this->maindata;

$options = "";
foreach ($sheetarr as $tmp) {
    if ($sheet == $tmp) {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    } else {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects = '<select data-mini="true" id="sheetselect" data-theme="a">';
$selects.=$options;
$selects.='</select>';
echo $selects;

$onswitches = array(
    "site" => "Site", "eeeno" => "E'ee No.", "namechs" => "Name", "nameeng" => "Name ", "wpno" => "WP No.",
    "ppno" => "PP No.", /* "rate" => "RATE", */);

$wdtab = $this->grid("Workersdata", true);
foreach ($onswitches as $key => $value) {
    $wdtab = $wdtab->field($key, $value);
}
$wdtab = $wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab = $wdtab->paginatorEnabled(false)->setSorting(false);
$wdtab = $wdtab->helper(new GridHelper_Workerdetails());
$wdtab = $wdtab->data($maindata)->action(':action', '工地', array('url' => array('action' => 'onsiterecord')));
$wdtab = $wdtab->action(':action', '缺勤', array('url' => array('action' => 'attendancerecord')));
echo $wdtab;
?>
<br><br>
