<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<script>
$(function () {
    //alert("scroller");
    $('.datepicker').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  
});

function addrecord()
{
    var site = $("#site").val();
    //alert("addrecord site="+site);    
    if(site == 0)
    {
        alert("请选择一个工地");
        return;
    }    

    $("#addrecordform").submit();
}

</script>
<?php
$worker=$this->worker;
$nameeng=$worker->getNameeng();
$namechs=$worker->getNamechs();

$sites=$this->sites;
$id=$this->id;
?>

<h3><strong>工人在岗记录 - <?php echo $namechs . "/" . $nameeng; ?></strong></h3>

<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="true">
<h3>添加记录</h3>
<form method="post" action="/worker/onsite/addrecord" id="addrecordform">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<div data-role="fieldcontain">
<label for="begin">开始日期:</label>
<input type="text" name="begin" id="begin" class="datepicker" value="" data-mini="true" placeholder="点击选择日期"/>
</div>
<div data-role="fieldcontain">
<label for="end">结束日期:</label>
<input type="text" name="end" id="end" class="datepicker" value="" data-mini="true" placeholder="点击选择日期"/>
</div>
<div data-role="fieldcontain">
	<label for="site" class="select">所在工地:</label>
	<select name="site" id="site" data-mini="true">
		<option value="0">选择工地</option>
<?php
$options="";
foreach($sites as $tmp)
{
    $id= $tmp->getId();
    $name=$tmp->getName();

    $option = "<option value=$id>$name</option>";
    $options .= $option;
}
echo $options;
?>
	</select>
</div>
<input type="button" onclick="addrecord()" value="添加" data-mini="true" data-theme="a">
</form>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>编辑记录</h3>
<?
echo $this->grid("Recordedit", true)
          ->field('begindate','起始日期')
          ->field('enddate','结束日期')
          //->field('company', '所在公司')
          ->field('site', '所在工地')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Workeronsite())
          ->data($this->records)
          ->action(':action', '记录管理', array( 'url'=>array('action'=>'onsiterecord')));
?>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>详细记录</h3>
<?
echo $this->grid("Recordedit", true)
          ->field('begindate','起始日期')
          ->field('enddate','结束日期')
          ->field('site', '所在工地')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Workeronsite())
          ->data($this->records);
?>
</div>
</div>

<br><br>
