<style>
#infoswitches { display: none; }
#datatable { text-align:center; display:none; }
#Workersdata { width:100%; }
#uploaddiv { display: none; }
/*#featuresdiv { display: none; }*/
</style>
<script>
$(document).ready(function() {
    $('#Workersdata').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    fnHideColumns();
    resizetable();
} );

function resizetable()
{
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
    $('#Workersdata').width('100%');
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
}

function fnHideColumns()
{
    var oncount = Number($('#oncount').val());
    var offcount = Number($('#offcount').val()) + oncount;
    //alert(oncount + "," + offcount);

    for(i=oncount; i<offcount; i++)
    {   //alert(i);
        fnHideColumn(i);
    }
}

function fnHideColumn( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, false );
}

function fnShowHide( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();
	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, bVis ? false : true );
}

function infoswitches()
{
    var sws = $("#infoswitches");    
    var display = sws.css("display");
    //alert(display);

    if(display == "none")
    {
        $("#infoswitches").show();
    }
    else
    {
        $("#infoswitches").hide();
    }
}

function redirect(url) {
    window.location = url;
}

$( "#sheetselect" ).change(function() {
    var sheetname = $(this).val();
    var url = "/worker/archive?sheet=" + sheetname;
    redirect(url);
});

function previewlist()
{
    var sheet = $("#sheetselect").val();
    var url = "/worker/archive/previewlist?sheet=" + sheet;
    window.open (url); 
}

</script>

<?php
$sheet=$this->sheet;
$sheetarr=$this->sheetarr;
$maindata=$this->maindata;
?>

<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="true">
<h3>列表操作</h3>
<button data-theme="a" data-mini="true" onclick="infoswitches()">数据筛选</button>
<div id="infoswitches">
<div class="ui-grid-d">
<?php
$onswitches=array(
"eeeno"=>"E'ee No.","namechs"=>"Name Chs","nameeng"=>"Name Eng","wpno"=>"WP No.", 
"ppno"=>"PP No.", "resignation"=>"Resignation");

$offswitches=array(
"sn"=>"S/N", "rate"=>"RATE", "wpexpiry"=>"WP Expiry","doa"=>"D.O.A","issuedate"=>"Date of Issue","finno"=>"Fin No.",
"dob"=>"D.O.B","ppexpiry"=>"PP Expiry","pano"=>"PA Reference  No.", "sbno"=>"Security Bond No.", 
"securityexp"=>"Security Exprity Date", "worktype"=>"主要工种","arrivaldate"=>"Arrival Date","medicaldate"=>"Medical Date", "csoc"=>"C.S.O.C", "medicalinsuranc"=>"Medical Insurance", "workingsite"=>"WORKING SITE", "dormitory"=>"Dormitory", 
"hometown"=>"区域", "education"=>"教育程度", "age"=>"年龄", "marital"=>"婚姻状况", 
"constructionworker"=>"建筑工", "applyfor"=>"Apply For", "goodat"=>"Good At", "contactno1"=>"Contact No.1", 
"contactno2"=>"Contact No.2", "remarks"=>"Remarks(Agent)",);

$customtitles=$this->customtitles;
$offswitches["custom1"]=$customtitles[0];
$offswitches["custom2"]=$customtitles[1];
$offswitches["custom3"]=$customtitles[2];
$offswitches["custom4"]=$customtitles[3];

$count=0;
$oncount=0;
$grids="";
foreach($onswitches as $key => $value)
{
    $oncount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" checked onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '</div><hr><div class="ui-grid-d">';
echo '<input type="hidden" id="oncount" value="'. $oncount . '">';

$offcount=0;
$count=0;
$grids="";
foreach($offswitches as $key => $value)
{
    $offcount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount+$offcount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '<input type="hidden" id="offcount" value="'. $offcount . '">';
echo '<hr>';
?>
</div><!-- /grid-d -->
<hr>
</div>
<!--<a href="/worker/manage/previewlist" target="_blank"><button data-theme="a" data-mini="true">预览打印</button></a>-->
<button data-theme="a" data-mini="true" onclick="previewlist()">预览打印</button>
</div>

</div> <!-- collapsible-set -->

<?php

$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;

if(count($maindata))
{
$wdtab=$this->grid("Workersdata", true);
foreach($onswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
foreach($offswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
$wdtab=$wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab=$wdtab->paginatorEnabled(false)->setSorting(false);
$wdtab=$wdtab->helper(new GridHelper_Workerdetails());
$wdtab=$wdtab->data($maindata)->action(':action', '详情', array( 'url'=>array('action'=>'edit')));
//$wdtab=$wdtab->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
echo $wdtab;
}
else
{
echo "No data found;";
} 
?>
<br><br>


