<?php
// this part is from Adverts module

// Global Defines for templates
$settings = Zend_Registry::get('settings');

$this->headScript()->prependFile('/common/js/jquery.mobile-1.2.0.min.js');
$this->headScript()->prependScript('
    // Disable AJAX jquerymobile handling for now (makes debugging easier)
    $(document).bind("mobileinit", function(){
		     $.mobile.ajaxEnabled = false;
    });
    ', $type='text/javascript');
$this->headScript()->prependFile('/common/js/jquery-1.8.2.min.js');

$this->headLink()->prependStylesheet('/common/css/jquery.mobile.structure-1.2.0.min.css');
$this->headLink()->prependStylesheet('/common/css/synrgic-hcs-jquerymb.css');
?>

<!DOCTYPE html> 
<html>
<head>
<title>HCS</title>
<meta name="viewport" content="width=device-width, initial-scale=1"> 
<meta charset="UTF-8">
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink()?>
<?php echo $this->headStyle() ?>
<?php echo $this->headScript() ?>
<?php
?>

<style type="text/css">
body,html {
	height: 100%;
    margin: 0;
    padding: 0;
    width: 100%;}

table {
    width: 100%;
    height: 720px;
	margin: 0;
	padding: 0;
	border-collapse: collapse;
}

div.synrgic-ads-board {
    position:relative;
}
.welcome-logolanguage img {
	text-align: center;
	width: 245px;
	border: none;
	display: block;
}

.welcome-logolanguage {
	text-align: center;
	width: 300px;
}

td.welcome-advertboard-td img {
	display: block;
}

.welcome-advertboard {
	text-align: center;
	width: 100%;
	height: 100;
	border-collapse: collapse; 
}
td.welcome-advertboard, th.welcome-advertboard {
	padding: 0;
}
.welcome-advertboard-block01 {
	text-align: center;
	padding: 0px;
	margin: 0px; 
	border-collapse: collapse;
	width: 517px;
	height: 376px;
}
.welcome-advertboard-block02 {
	text-align: center;
	padding: 0px;
	margin: 0px; 
	border-collapse: collapse;
	width: 517px;
	height: 376px;
}
.welcome-advertboard-block03 {
	text-align: center;
	padding: 0px;
	margin: 0px; 
	border-collapse: collapse;
	width: 517px;
	height: 376px;
}
.welcome-advertboard-block04 {
	text-align: center;
	padding: 0px;
	margin: 0px; 
	border-collapse: collapse;
	width: 517px;
	height: 376px;
}
</style>
</head>
<body>

<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="welcome-logolanguage" rowspan="2"  width="300" height="720"><?php echo $this->layout()->content; ?></td>
    <td class="welcome-advertboard-block01" width="517" height="376"><img src="<?=$settings->WelcomeAdverts->image1->value?>" width="100%" height="100%"/></td>
    <td class="welcome-advertboard-block02" width="517" height="376"><img src="<?=$settings->WelcomeAdverts->image2->value?>" width="100%" height="100%"/></td>
  </tr>
  <tr>
    <td class="welcome-advertboard-block03" width="517" height="376"><img src="<?=$settings->WelcomeAdverts->image3->value?>" width="100%" height="100%"/></td>
    <td class="welcome-advertboard-block04" width="517" height="376"><img src="<?=$settings->WelcomeAdverts->image4->value?>" width="100%" height="100%"/></td>
  </tr>
</table>



</body>
</html>
