<style>
#appinfotab { width:100%; }
</style>
<script>
function updaterow(id)
{
    var amount = $('#amount'+id).val();
    var remark = $('#remark'+id).val();
    var supplierid = $('#select'+id).val();   
    var price = $('#price'+id).val();
    price = (price=="") ? 0 : price;

    //alert('updaterow,id='+id+",amount="+amount+",remark="+remark+",supplierid="+supplierid+",price="+price);

    $.post("/material/appmanage/updatematapp", 
        { id: id, amount: amount, remark:remark, supplierid:supplierid, price:price  }, 
        function(data) {
            alert(data);
            console.log(data);            
    });
}

function submitmatapps()
{
    //alert("submitmatapps");
    var siteid = $('#site').val();
    var applicantid = $('#applicant').val();
    
    var appid = $("#appid").val();
    $.post("/material/appmanage/submitmatapps", { appid:appid, siteid:siteid, applicantid:applicantid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function rejectmatapps()
{
    //alert("rejectmatapps");
    var appid = $("#appid").val();
    $.post("/material/appmanage/rejectmatapps", { appid: appid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function reviewmatapps()
{
    //alert("reviewmatapps");
    var appid = $("#appid").val();
    $.post("/material/appmanage/reviewmatapps", { appid: appid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function approvematapps()
{
    //alert("approvematapps");

    var appid = $("#appid").val();
    $.post("/material/appmanage/approvematapps", { appid: appid }, 
        function(data) {
            alert(data);
            redirect();
    });
}

function redirect()
{
    window.location = "/material/appmanage/appmanage";
}
</script>
<?php
$appobj = $this->application;
$appid=$appobj->getId();
$create = $appobj->getCreatedate()->format("Y-m-d H:i:s");
$update = $appobj->getUpdatedate()->format("Y-m-d H:i:s");
$applicant = $appobj->getApplicant();
$applicantname = "";
$applicantid =0;
if($applicant)
{
    $applicantname = $applicant->getName();
    $applicantid = $applicant->getId();
}
$sitename = "";
$siteid=0;
$siteobj = $appobj->getSite();
if($siteobj)
{
    $sitename = $siteobj->getName();
    $siteid = $siteobj->getId();
} 
$sites=$this->sites;

$humanres = $this->humanres;

$role = $this->role;
$displayblk = 0;    
if($role=="manager")
{
    $displayblk = 1;
}

$matappsInSys=$this->matappsInSys;
$matappsNotInSys=$this->matappsNotInSys;
?>

<input type="hidden" id="appid" value="<?php echo $appid; ?>">
<p><strong>材料申请 - 上次更新时间 - <?php echo $update; ?></strong></p>

<div data-role="collapsible-set" >

<div data-role="collapsible" data-collapsed="<?php if($open==1) echo "false"; else {echo "true";} ?>">
<h3>第一步：选择申请工地 - <?php echo $sitename; ?></h3>
<select id="sites" data-mini="true" data-theme="a">
<option value="0">请选择申请工地</option>
<?php
$options = '';
foreach($sites as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();

    if($siteid == $id)
    {
        echo '<option value="' . $id . '" selected>' . $name . "</option>";
    }
    else
    {
        echo '<option value="' . $id . '" >' . $name . "</option>";
    }
}
echo $options;
?>
</select>
</div>

<!--按分类选择材料-->
<div data-role="collapsible" data-collapsed="<?php if($open==2) echo "false"; else {echo "true";} ?>">
<h3>第二步：分类选择材料</h3>
<div id="typechooser">
<table class="grid">
<tr>
<td>选择主要类型:</td>
<td>
<select name="maintype" id="maintype" data-mini="true" data-theme="a">
<?php
foreach($maintypes as $tmp)
{
    $id = $tmp->getId();
    $namechs = $tmp->getTypechs();
    $nameeng = $tmp->getTypeeng();

    if($id == $mainid)
    {
        echo "<option value='$id' selected>$namechs</option>";
    }
    else
    {
        echo "<option value='$id'>$namechs</option>";
    }
}
?>   
</select>

</td>
<td>选择子类型:</td>
<td>
<select name="subtype" id="subtype" data-mini="true" data-theme="a">
<?php
foreach($subtypes as $tmp)
{
    $id = $tmp->getId();
    $namechs = $tmp->getTypechs();
    $nameeng = $tmp->getTypeeng();

    if($id == $subid)
    {
        echo "<option value='$id' selected>$namechs</option>";
    }
    else
    {
        echo "<option value='$id'>$namechs</option>";
    }
}
?>   
</select>
</td>
</tr>

</table>

<table id="datatable" class="grid">
<thead><tr>
<th>材料名称</th><th>数量</th><th>单位</th><th>规格</th><th>工程部位</th><th>提交</th>
</tr></thead>
<tbody> 
<?php
/*
$dropdown = '<select data-mini="true"><option value="无定义">无定义</options>';
$options ="";
foreach($siteparts as $tmp)
{
    if($tmp != "")
    {        
        $options .= '<option value="' . $tmp . '">' . $tmp . '</option>';
    }
}
$dropdown .= $options;
$dropdown .= "</select>";
*/
$options='<option value="无定义">无定义</options>';
foreach($siteparts as $tmp)
{
    if($tmp != "")
    {        
        $options .= '<option value="' . $tmp . '">' . $tmp . '</option>';
    }
}

foreach($this->materials as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    $nameeng = $tmp->getNameeng();

    $body = "";
    $longname = '<tr><td class="tdname">' . $name . '/' . $nameeng . '</td>';
    $amount = '<td class="tdamount"><input type="number" name="slider" id="slider' . $id . '" value="" placeholder="0"></td>';
    $unit = "<td></td>";
    $spec = "<td></td>";    
    
    $dropdown = '<select id="sitepart' . $id . '" data-mini="true">';
    $dropdown .= $options;
    $dropdown .= '</select>';
    $td_dropdown = '<td>' . $dropdown . '</td>';    

    $body .= $longname . $amount . $unit . $spec . $td_dropdown;
    $gorightbutton = '<td class="tdchoose"><button onclick="addchoosen(' . $id . ')" data-icon="arrow-r" data-iconpos="bottom" data-inline="true" data-mini="true">提交</button></td>';

    $body .= $gorightbutton;
    $body .= "</tr>";    
    echo $body;
}
?>
</tbody> 
</table>
</div> <!-- typechooser -->
</div>

<!--手动输入材料信息-->
<div data-role="collapsible" data-collapsed="<?php if($open==3) echo "false"; else {echo "true";} ?>"  <?php echo $displaynone; ?> >
<h3>第三步：手动输入材料</h3>
<div id="manualinput">
    <form id="manuform">
    <div data-role="fieldcontain">
    <label for="manuname">输入名称:</label>
    <input type="text" name="manuname" id="manuname" placeholder="材料名称，比如钉子，水泥等" value=""  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuamount">输入数量:</label>
    <input type="text" name="manuamount" id="manuamount" placeholder="填写数量，比如要30包水泥，这里写30" value=""  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuremark">输入规格:</label>
    <textarea cols="40" rows="8" name="manuremark" id="manuremark" placeholder="填写规格说明，比如多大号的钉子，什么水泥等"></textarea>
    </div>
    </form> <!-- manuform -->					    
    <input type="submit" value="提交到选择列表" onclick="submitmanualinput()" data-theme="a">
</div>
</div>

<div id="selcollapsible" data-role="collapsible" data-collapsed="<?php if($open==4) echo "false"; else {echo "true";} ?>">
<h3>最后步：提交已选材料</h3>
<div id="selections">
    <div id="seltable">
    </div>
<input type="submit" value="提交至材料审核人员" onclick="submitselections()" data-theme="a">
</div>

</div>
</div> <!-- collapsible-set -->

<?php
if(count($matappsInSys)>0)
{
echo "<p>系统已有信息的材料</p>";
echo $this->grid("matappsInSys", true)
          ->field('longname','材料名称')
          ->field('amount','申请数量')
          //->field('remark','补充说明')
          ->field('sitepart', '工程部位')  
          ->field('supplier', '供应商')
          //->field('price', '单价')
          ->field('update', '更新')          
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Matapps())
          ->data($matappsInSys)
          ->action(':action', '删除', array( 'url'=>array('action'=>'appmatdel')));
}

if(count($matappsNotInSys)>0)
{
echo "<p>手动输入信息的材料</p>";
echo $this->grid("matappsNotInSys", true)
          ->field('longname','材料名称')
          ->field('amount','申请数量')
          //->field('remark','补充说明')
          ->field('sitepart', '工程部位')  
          ->field('supplier', '供应商')
          //->field('price', '单价')
          ->field('update', '更新')          
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Matapps())
          ->data($matappsNotInSys)
          ->action(':action', '删除', array( 'url'=>array('action'=>'appmatdel')));
}
?>

<input type="button" value="提交上级审核" onclick="submitmatapps()" data-theme="a" data-mini="true">




