<script>
$(function() {  
    $('#Applications').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
});
</script>
<h3>选择一个申请单进行更新</h3>
<?
echo $this->grid("Applications", true)
          ->field('site','工地')
          ->field('id','申请单号')
          ->field('applicant','申请人')
          ->field('createdate','创建日期')
          ->field('updatedate','更新日期')
          //->field('status0', '申请状态')
          //->field('status1', '办公人员评估')
          //->field('status2', '经理评估')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Application())
          ->data($this->maindata)
          ->action(':action', '更新申请', array( 'url'=>array('action'=>'appedit')))
          ->action(':action', '取消申请', array( 'url'=>array('action'=>'appdel')));
?>
<br><br>

