<style>
/*http://stackoverflow.com/questions/3148415/how-to-make-a-vertical-line*/
/*.verticalLine { border-left: 2px solid #000000; }*/
/*
table { width:100%; }
#datatable caption { text-align:left; }
#datatable thead th { text-align:center; border-bottom-width:1px; border-top-width:1px; }
#datatable th, td { text-align:center; padding:1px;} 
.tdname { width:100px; }
.tdnameeng { width:100px; }
.tdamount { width:200px; }
.tdchoose { width:50px; }
*/

#typechooser { width:100%; text-align:center; /*vertical-align:middle;float:left; padding-right: 2px; margin: 3px; */ }
#datatable { width:100%; }
#selected { display: none; text-align:center;}
#manualinput { display: none; text-align:center;}
</style>
<script>
$(function() {
    $('#macrotype').change(macroReload);
    $('#detailtype').change(detailReload);
});

function macroReload()
{
    //alert("reload!");
    var url = "/material/apply/applymaterials?macro=" + $('#macrotype').val();
    redirect(url);
}

function detailReload()
{
    //alert("reload!");
    var url = "/material/apply/applymaterials?macro=" + $('#macrotype').val() + "&detail=" + $('#detailtype').val();
    redirect(url);
}

function redirect(url) 
{
	window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function submitmaterials()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/apply/submit";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function addchoosen(id)
{
    //alert("id="+id);
    var amount = $('#slider'+id).val();
    if(amount==0)
    {
        alert("请选择数量");
        return;
    }

    alert("id="+id+", amount="+amount);

    // TODO: upload to server
    $.post("/material/apply/postdata", { id: id, amount: amount }, 
        function(data) {
            alert("Data Loaded: " + data);
            location.reload();
    });
                
}

//http://stackoverflow.com/questions/178325/testing-if-something-is-hidden-with-jquery
// http://stackoverflow.com/questions/4009524/change-button-text-jquery-mobile
function showselected()
{    
    //alert("showselected");
    //if($("#selected").is(":visible")) {
    //if ($("#selected").css("visibility") == "hidden") {
    if ($("#selected").css('display') == 'none') {    
        $("#selected").show();
        $("#btnSelectedText").html('隐藏已选材料'); 
    }
    else
    {
        $("#selected").hide();    
        $("#btnSelectedText").html('显示已选材料'); 
    }            
}

function showmanualinput()
{
    $("#typechooser").hide();
    $("#manualinput").show();
       
}

function showtypechooser()
{
    $("#manualinput").hide();
    $("#typechooser").show();
}

function submitselected()
{
    alert("submitselected");
}
</script>

<div data-role="navbar">
	<ul>
		<li><a href="#" class="ui-btn-active ui-state-persist" onclick="showtypechooser()">分类选择材料</a></li>
		<li><a href="#" onclick="showmanualinput()">手动输入材料信息</a></li>
		<li><a href="#">显示选择材料列表</a></li>		
	</ul>
</div><!-- /navbar -->

<!--<button onclick="submitselected()" data-mini="true">检查并提交已选材料</button>
<button id="btnSelected" onclick="showselected()" data-mini="true"><span id="btnSelectedText">检查已选材料</span></button>
<div id="selected">
<fieldset>
    <legend>已选择材料</legend>
    <p><strong>未选择任何材料</strong></p>
</fieldset>
</div>
<button id="btnSelected" onclick="showmanualinput()" data-mini="true"><span id="btnManualText">手动输入材料信息</span></button>
<div id="manualinput">
<fieldset>
    <legend>手动输入材料信息</legend>
    <p><strong>未选择任何材料</strong></p>
</fieldset>
</div>

<button id="btnSelected" onclick="showselected()" data-mini="true"><span id="btnSelectedText">按分类选择材料</span></button>
-->
<div id="manualinput">
<fieldset>
    <legend>手动输入材料信息</legend>
    <form id="manuform">
    <div data-role="fieldcontain">
    <label for="manuname">输入名称:</label>
    <input type="text" name="manuname" id="manuname" value="材料名称，比如钉子，水泥等"  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuamount">输入数量:</label>
    <input type="text" name="manuamount" id="manuamount" value="填写数量，比如要30包水泥，这里写30"  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuspec">输入规格:</label>
    <textarea cols="40" rows="8" name="manuspec" id="manuspec">填写规格说明，比如多大号的钉子，什么水泥等</textarea>
    </div>
    </form> <!-- manuform -->					    
    <input type="submit" value="提交到选择列表" >
</fieldset>
</div>

<div id="typechooser" style="clear:both">
<fieldset>
    <legend>按分类选择材料</legend>
<div data-role="fieldcontain">
   <label for="macrotype" class="select">主要分类：</label>
   <select name="macrotype" id="macrotype" data-mini="true">
<?php
$selected=$this->macro;
$macrotypes = $this->macrotypes;
//print_r($this->macrotypes);
foreach($this->macrotypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>   
   </select>
</div>

<div data-role="fieldcontain">
   <label for="detailtype" class="select">详细分类:</label>
   <select name="detailtype" id="detailtype" data-mini="true">
<?php
$selected=$this->detail;
$detailtypes = $this->detailtypes;
//print_r($this->detailtypes);
foreach($this->detailtypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>        
   </select>
</div>

<table id="datatable" border="3">
<thead><tr>
<th>材料名称</th>
<th>数量</th>
<th>单位</th>
<th>规格</th>
<th>选择</th>
</tr></thead>
<tbody> 
<?php
foreach($this->materials as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    $nameeng = $tmp->getNameeng();

    $body = "";
    $longname = '<tr><td class="tdname">' . $name . '/' . $nameeng . '</td>';
    $amount = '<td class="tdamount"><input type="number" name="slider" id="slider' . $id . '" value="0" min="0" max="100"></td>';
    $unit = "<td></td>";
    $spec = "<td></td>";
    $body .= $longname . $amount . $unit . $spec;
    $gorightbutton = '<td class="tdchoose"><button onclick="addchoosen(' . $id . ')" data-icon="arrow-r" data-iconpos="bottom" data-inline="true" data-mini="true">选中</button></td>';

    $body .= $gorightbutton;
    $body .= "</tr>";    
    echo $body;
}
?>
</tbody> 
</table>
</fieldset>
</div> <!-- typechooser -->




