<style>
/*http://stackoverflow.com/questions/3148415/how-to-make-a-vertical-line*/
/*.verticalLine { border-left: 2px solid #000000; }*/
/*
table { width:100%; }
#datatable caption { text-align:left; }
#datatable thead th { text-align:center; border-bottom-width:1px; border-top-width:1px; }
#datatable th, td { text-align:center; padding:1px;} 
.tdname { width:100px; }
.tdnameeng { width:100px; }
.tdamount { width:200px; }
.tdchoose { width:50px; }

table.grid {width:100%}
#datatable { width:100%; }

*/
#typechooser { width:100%; text-align:center; /*vertical-align:middle;float:left; padding-right: 2px; margin: 3px; */ }
#selected { display: none; text-align:center;}
#manualinput { display: none; text-align:center;}
#selections { display: none; text-align:center;}
</style>
<script>
$(function() {
    $('#macrotype').change(macroReload);
    $('#detailtype').change(detailReload);
});

function macroReload()
{
    //alert("reload!");
    var url = "/material/apply/applymaterials?macro=" + $('#macrotype').val();
    redirect(url);
}

function detailReload()
{
    //alert("reload!");
    var url = "/material/apply/applymaterials?macro=" + $('#macrotype').val() + "&detail=" + $('#detailtype').val();
    redirect(url);
}

function redirect(url) 
{
	window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function submitmaterials()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/apply/submit";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function addchoosen(id)
{
    //alert("id="+id);
    var amount = $('#slider'+id).val();
    if(amount==0)
    {
        alert("请选择数量");
        return;
    }

    var remark = $('#remark'+id).val();
    //alert("id="+id+",amount="+amount+",remark="+remark);
    $.post("/material/apply/postdata", { id: id, amount: amount, remark:remark }, 
        function(data) {
            alert("提交成功，请继续申请材料");
            console.log(data);
            //location.reload();
    });
                
}

//http://stackoverflow.com/questions/178325/testing-if-something-is-hidden-with-jquery
// http://stackoverflow.com/questions/4009524/change-button-text-jquery-mobile
function showselected()
{    
    //alert("showselected");
    //if($("#selected").is(":visible")) {
    //if ($("#selected").css("visibility") == "hidden") {
    if ($("#selected").css('display') == 'none') {    
        $("#selected").show();
        $("#btnSelectedText").html('隐藏已选材料'); 
    }
    else
    {
        $("#selected").hide();    
        $("#btnSelectedText").html('显示已选材料'); 
    }            
}

function showmanualinput()
{
    $("#typechooser").hide();
    $('#selections').hide();

    $("#manualinput").show();
       
}

function showtypechooser()
{
    $("#manualinput").hide();
    $('#selections').hide();

    $("#typechooser").show();
}

function showselections()
{
    //$('#selections').load('/material/apply/getselections');
    $('#seltable').load('/material/apply/getselections');
    $("#typechooser").hide();
    $("#manualinput").hide();
    $('#selections').show();
}

function submitmanualinput()
{
    var id = 0;    
    var name = $('#manuname').val();
    var amount = $('#manuamount').val();
    var remark = $('#manuremark').val();

    if(name=="" || amount=="" || remark=="")
    {
        alert("请填写完整，再提交");
    }

    $.post("/material/apply/postdata", { id:id, amount:amount, remark:remark, longname:name }, 
        function(data) {
            alert("提交成功，请继续申请材料");
            //console.log(data);
            //location.reload();
    });    
}

function submitselections()
{
    //alert("submitselections");
    $.post("/material/apply/submitselections", 
        function(data) {
            alert(data);
            //console.log(data);
            //location.reload();
            redirect("/material/apply/");    
    });    
}

function redirect(url) {
    window.location = url;
}

</script>
<?php
$sites = $this->sites;
?>

<select >
<option value="0">请选择申请工地</option>
<?php
foreach($sites as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    echo '<option value="' . $id . '">' . $name . "</option>";
}
?>
</select>
<div data-role="navbar">
	<ul>
		<li><a href="#" class="ui-btn-active ui-state-persist" onclick="showtypechooser()">分类选择材料</a></li>
		<li><a href="#" onclick="showmanualinput()">手动输入材料信息</a></li>
		<li><a href="#" onclick="showselections()">显示选择材料列表</a></li>		
	</ul>
</div><!-- /navbar -->

<div id="selections">
<div id="seltable">
</div>
<input type="submit" value="提交至材料审核人员" onclick="submitselections()">
</div>

<div id="manualinput">
<fieldset>
    <!--<legend>手动输入材料信息</legend>-->
    <form id="manuform">
    <div data-role="fieldcontain">
    <label for="manuname">输入名称:</label>
    <input type="text" name="manuname" id="manuname" placeholder="材料名称，比如钉子，水泥等" value=""  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuamount">输入数量:</label>
    <input type="text" name="manuamount" id="manuamount" placeholder="填写数量，比如要30包水泥，这里写30" value=""  />
    </div>
    <div data-role="fieldcontain">
    <label for="manuremark">输入规格:</label>
    <textarea cols="40" rows="8" name="manuremark" id="manuremark" placeholder="填写规格说明，比如多大号的钉子，什么水泥等"></textarea>
    </div>
    </form> <!-- manuform -->					    
    <input type="submit" value="提交到选择列表" onclick="submitmanualinput()">
</fieldset>
</div>

<div id="typechooser" style="clear:both">
<fieldset>
    <!--<legend>按分类选择材料</legend>-->
<div class="ui-grid-a">
<div class="ui-block-a"><div data-role="fieldcontain">
   <label for="macrotype" class="select">主要分类：</label>
   <select name="macrotype" id="macrotype" data-mini="true">
<?php
$selected=$this->macro;
$macrotypes = $this->macrotypes;
//print_r($this->macrotypes);
foreach($this->macrotypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>   
   </select>
</div></div> <!--ui-block-a-->

<div class="ui-block-b"><div data-role="fieldcontain">
   <label for="detailtype" class="select">详细分类:</label>
   <select name="detailtype" id="detailtype" data-mini="true">
<?php
$selected=$this->detail;
$detailtypes = $this->detailtypes;
//print_r($this->detailtypes);
foreach($this->detailtypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>        
   </select>
</div></div>	<!--ui-block-b-->
</div> <!--ui-grid-a-->

<table id="datatable" class="grid">
<thead><tr>
<th>材料名称</th><th>数量</th><th>单位</th><th>规格</th><th>工程部位</th><th>提交</th>
</tr></thead>
<tbody> 
<?php
foreach($this->materials as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    $nameeng = $tmp->getNameeng();

    $body = "";
    $longname = '<tr><td class="tdname">' . $name . '/' . $nameeng . '</td>';
    $amount = '<td class="tdamount"><input type="number" name="slider" id="slider' . $id . '" value="0" min="0" max="100"></td>';
    $unit = "<td></td>";
    $spec = "<td></td>";    
    $remark = '<td><textarea name="remark" id="remark' . $id . '" placeholder="选择工程部位"></textarea></td>';
    $body .= $longname . $amount . $unit . $spec . $remark;
    $gorightbutton = '<td class="tdchoose"><button onclick="addchoosen(' . $id . ')" data-icon="arrow-r" data-iconpos="bottom" data-inline="true" data-mini="true">提交</button></td>';

    $body .= $gorightbutton;
    $body .= "</tr>";    
    echo $body;
}
?>
</tbody> 
</table>
</fieldset>
</div> <!-- typechooser -->




