<script>
    $(function() {
        $('#Applications').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
            "aaSorting": [[ 0, "desc" ]],
        });
    });
</script>

<h3>更新申请</h3>
<?php
echo $this->grid("Applications", true)
        ->field('updatedate', '更新日期')
        ->field('site', '工地')
        ->field('id', '申请单号')
        ->field('applicant', '申请人')
        ->field('createdate', '创建日期')
        //->field('status0', '申请状态')
        //->field('status1', '办公人员评估')
        //->field('status2', '经理评估')  
        ->actionField(':action', "操作", '&nbsp;|&nbsp;')
        ->itemCountPerPage(30)
        ->paginatorEnabled(false)
        ->setSorting(false)
        ->helper(new GridHelper_Application())
        ->data($this->maindata)
        ->action(':action', '更新', array('url' => array('action' => 'appedit')))
        ->action(':action', '取消', array('url' => array('action' => 'appdel')));
?>
<br><br>

