<style>
#wizard { text-align:center; }
</style>

<!-- displaying rejected application, if none rejected, this div should be hide. -->
<div id="appmessage">

</div> <!-- appmessage -->

<div id="wizard">
<fieldset>
    <a href="/material/apply/applymaterials"><button>申请办公物品</button></a> 
    <p>点击，为办公室申请物品，比如文具等</p>
</fieldset><br> 

<fieldset>
    <!--<legend><strong>创建申请</strong></legend>-->
    <a href="/material/apply/applymaterials"><button>申请工地材料</button></a> 
    <p>点击，进入工地申请创建过程</p>
</fieldset><br> 

<fieldset>
    <!--<legend><strong>编辑申请</strong></legend>-->
    <button onclick="showeditapp()">更新申请</button>
    <p>点击，更新申请</p>
</fieldset>
</div>

