<style>
table { width:100%; }
#datatable caption { text-align:left;  }
#datatable thead th { text-align:left; border-bottom-width:1px; border-top-width:1px; }
#datatable th, td { text-align:left; padding:6px;} 
</style>
<script>
$(function() {
    $('#macrotype').change(macroReload);
    $('#detailtype').change(detailReload);
});

function macroReload()
{
    //alert("reload!");
    var url = "/material/apply/index?macro=" + $('#macrotype').val();
    redirect(url);
}

function detailReload()
{
    //alert("reload!");
    var url = "/material/apply/index?macro=" + $('#macrotype').val() + "&detail=" + $('#detailtype').val();
    redirect(url);
}

function redirect(url) 
{
	window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function submitmaterials()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/apply/submit";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}
</script>
<form id="dataform">
<div data-role="fieldcontain">
   <label for="macrotype" class="select">选择主要分类：</label>
   <select name="macrotype" id="macrotype" data-mini="true">
<?php
$selected=$this->macro;
$macrotypes = $this->macrotypes;
//print_r($this->macrotypes);
foreach($this->macrotypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>   
   </select>
</div>
<div data-role="fieldcontain">
   <label for="detailtype" class="select">选择具体分类:</label>
   <select name="detailtype" id="detailtype" data-mini="true">
<?php
$selected=$this->detail;
$detailtypes = $this->detailtypes;
//print_r($this->detailtypes);
foreach($this->detailtypes as $tmp)
{
    if($tmp == $selected)
    {
        echo "<option value='$tmp' selected>$tmp</option>";
    }
    else
    {
        echo "<option value='$tmp'>$tmp</option>";
    }
}
?>        
   </select>
</div>
<!--
</form >
<form name="dataform" id="dataform">
-->
<table id="datatable" border="5">
<thead><tr>
<th><input type="checkbox" name="toggleall" id="toggleall" onClick="checkall()" data-role="none"></th>
<th>Name</th>
<th>Date</th>
<th>Type</th>
<th>Detail</th>
<th>Warehouse</th>
<th>Price</th>
</tr></thead>
<tbody> 
<?php
foreach($this->materials as $tmp)
{
    $name = $tmp->getName();
    $date = $tmp->getOnlinedate()->format("Y-m-d H:i:s");
    $price = $tmp->getPrice();
    $warehouse = $tmp->getWarehouse();
    $type1 = $tmp->getMacrotype();
    $type2 = $tmp->getDetailtype();

    $checkbox = '<td><input type="checkbox" name="abc" id="abc" value="' . $tmp->getId() . '" data-role="none">';
    $body = "";
//    $body .= "<tr>" . $checkbox . "<td>" . $name . "</td><td>" . $date . "</td><td> </td>$type1  <td>" . $price . "</td></tr>";    
    $body .= "<tr>$checkbox<td>$name</td><td>$date</td><td>$type1</td><td>$type2</td><td>$warehouse</td><td>$price</td></tr>";    
    echo $body;
}
?>
</tbody> 
</table>
<div data-role="fieldcontain">
    <label for="applyselects">提交所选项目：</label>
    <input type="submit" id="applyselects" name="applyselects" value="提交" >    
</div>
</form><!-- dataform -->

<hr>
<table>
<caption>已申请材料</caption>



<table>

