<?php
$sheetsel = $this->sheetsel;
$yearsel = $this->yearsel;
$workersel = $this->workersel;

$worker = $this->worker;
if ($worker) {
    $workername = ($worker->getNamechs() == "") ? $worker->getNameeng() : $worker->getNamechs();
} else {
    $workername = "";
}
$records = $this->recordsbyyear;

$salarytabs = $this->salarytabs;
$salaryall = $this->salaryall;
$salaryallformat = $this->salaryallformat;

//$salaryreceiptsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$monthstr";
?>
<!DOCTYPE html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>工人历史工资</title> 
        <link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
        <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
        <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
        <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>
    </head> 

    <body> 
        <style>
            #headertab { width: 100%; table-layout:fixed; }
            #headertab td, table th { text-align:left; border:0px solid black; text-align: center; }
            table { width: 100%; border-collapse:collapse; /*table-layout:fixed;*/}
            table td, table th { text-align:center; border:1px solid black; }

            .ui-dialog-contain {
                width: 92.5%;
                max-width: 2500px;
                margin: 3% auto 15px auto;
                padding: 0;
                position: relative;
                top: -15px;
            }

            .attendsum  { background-color:#D0D0D0; }
            .fixwidthcol { width:45px; }
            .tdattendfood { width:150px; }
            .workerinfo { background: #D0D0D0 /*#6FACD5*/; 
                          /*linear-gradient(#6FACD5, #497BAE) repeat scroll 0 0 #5E87B0;*/
                          /*linear-gradient(#5F9CC5, #396B9E) repeat scroll 0 0 #396B9E*/ 
                          table-layout:fixed;
            }

            .workerpay { /*background: #ff5555; */
                background: linear-gradient(#6FACD5, #497BAE) repeat scroll 0 0 #5E87B0;
                border: 1px solid #456F9A;
                color: #FFFFFF;
                font-weight: bold;
                text-shadow: 0 1px 1px #3E6790;
            }

            .noborder td { border:0px; } 

            .workeronsite {
                table-layout: fixed;
            }
            .workeronsite td {
                word-break:break-all;
            }

            hr {
                color: #f00;
                background-color: #f00;
                height: 3px;
            }
        </style>
        <script>
            $(function() {
                $("#sheetsel").on("change", function() {
                    //alert("sheet change");
                    var sheetname = $(this).val();
                    var url = "/salary/worker/personal?sheet=" + sheetname;
                    redirect(url);
                });

                $("#workersel").on("change", function() {
                    //alert("change");
                    var id = $(this).val();
                    var url = "/salary/worker/personal?";
                    url += "id=" + id;
                    redirect(url);
                });

                $("#yearsel").on("change", function() {
                    //alert("year change");
                    var id = $("#workersel").val();
                    var year = $(this).val();
                    var url = "/salary/worker/personal?";
                    url += "id=" + id;
                    url += "&year=" + year;
                    redirect(url);
                });
            });

            function redirect(url) {
                window.location = url;
            }

            function opensalaryreceipts()
            {
                var sheet = $("#sheetsel").val();
                var year = $("#yearsel").val();
                var worker = $("#workersel").val();
                var url = "/salary/salary/salaryreceiptsbyworker?";
                url += "&year=" + year;
                url += "&id=" + worker;
                OpenInNewTab(url);
            }

            function OpenInNewTab(url)
            {
                var win = window.open(url, '_blank');
                win.focus();
            }
        </script>
        <div data-role="page">

            <div data-role="header" >
                <table id="headertab">
                    <tr>
                        <td>工人历史工资<?php if ($workername !== "") echo " - " . $workername; ?></td>                        
                    </tr>
                </table>
            </div><!-- /header -->

            <div data-role="content">
                <div id="error"><?= $this->error ?></div>

                <div class="ui-grid-c">
                    <div class="ui-block-a"><?= $sheetsel ?></div>
                    <div class="ui-block-b"><?= $workersel ?></div>                    
                    <div class="ui-block-c"><?= $yearsel ?></div>
                    <div class="ui-block-d">
                        <input type="button" value="工资收据" onclick="opensalaryreceipts()" 
                               data-mini="true" data-theme="b">
                    </div>
                </div>
                <hr>
                <span>净工资:&nbsp; <strong><?= $salaryallformat ?></strong></span>
                <hr>
                <?php
                $divno = 0;
                $alltabs = "";
                if (count($salarytabs)) {
                    foreach ($salarytabs as $tmp) {
                        $alltabs = "";

                        $tab0 = $tmp[0]; // worker
                        $tab1 = $tmp[1]; // salary
                        $tab2 = $tmp[2]; // attend
                        $alltabs .= $tab0;
                        $alltabs .= $tab1;
                        $alltabs .= $tab2;
                        $alltabs .= "<br>";

                        $tab3 = $tmp[3];
                        $alltabs .= $tab3;

                        $divno++;
                        echo "<div id=worker$divno>
                            " . $alltabs . "</div><hr>
                            ";
                    }
                }
                ?>
            </div><!-- /content -->

            <!--<div data-role="footer">
                <h4>Footer content</h4>
            </div>--><!-- /footer -->

        </div><!-- /page -->

    </body>
</html>

