<?php $this->headStyle()->captureStart();?>
.icon {
    width: 100px;
    height: 100px;
}

#filtertable { 
    background-color:black;
    font-size:215%; 
}

#maincategorytable {
    width: 100%;    
}

#maincategorytable td{
    width: 50%;
    text-align:center;
}
<?php $this->headStyle()->captureEnd();?>

<script>
$(document).ready(function() {
    //alert("ready");
    $("#searchmain").bind('keypress', keyevent);    
});

function keyevent(e)
{
    var code = (e.keyCode ? e.keyCode : e.which);
    if(code == 13) { //Enter pressed    
        //alert($("#searchmain").val());
        document.forms['searchform'].submit();              
    }
}
</script>

<div>
<table id="filtertable">
<tr>
<td><a href='#'>#</a></td>
<td><a href='#'>A</a></td>
<td><a href='#'>B</a></td>
<td><a href='#'>C</a></td>
<td><a href='#'>D</a></td>
<td><a href='#'>E</a></td>
<td><a href='#'>F</a></td>
<td><a href='#'>G</a></td>
<td><a href='#'>H</a></td>
<td><a href='#'>I</a></td>
<td><a href='#'>J</a></td>
<td><a href='#'>K</a></td>
<td><a href='#'>L</a></td>
<td><a href='#'>M</a></td>
<td><a href='#'>N</a></td>
<td><a href='#'>O</a></td>
<td><a href='#'>P</a></td>
<td><a href='#'>Q</a></td>
<td><a href='#'>R</a></td>
<td><a href='#'>S</a></td>
<td><a href='#'>T</a></td>
<td><a href='#'>U</a></td>
<td><a href='#'>V</a></td>
<td><a href='#'>W</a></td>
<td><a href='#'>X</a></td>
<td><a href='#'>Y</a></td>
<td><a href='#'>Z</a></td>
</tr>
</table>
</div>

<form id="searchform" action="/information/index/searchresult" method="post">
<input type="hidden" name="category" id="category" value="all" />
<input type="search" name="searchmain" id="searchmain" value="Search" />
</form>

<table id="maincategorytable">
<?php
$i = 0;
$html = "";
$data = $this->data;
for($i=0; $i< count($data); $i++)
{
    $tmp = $data[$i];
    //echo $tmp->getTitle();
    $title = $tmp->getTitle();
    // space in query part must be encoded - URI safe encoding
    $url = "/information/index/subcategory?category=" . urlencode($title);

    if($i % 2 == 0)
    {
        $html .= '<tr>';            
    }

    $html .= '<td><div><a href="' . $url . '"><img src="/tablet/images/icons/icon-home.png" class="icon" /></a>';
    $html .= '<br><a href="' . $url . '">' . $title . '</a></div></td>';

    if($i % 2 == 1)
    {
        $html .= '</tr>';  
    }
}
if( count($data) % 2 == 1)
{
    $html .= '</tr>';  
}

echo $html;
?>
</table>


