<?php $this->headStyle()->captureStart();?>
#filtertable { 
    background-color:black;
    font-size:215%; 
}
<?php $this->headStyle()->captureEnd();?>

<script>
$(document).ready(function() {
    //alert("ready");
    $("#searchmain").bind('keypress', keyevent);    
});

function keyevent(e)
{
    var code = (e.keyCode ? e.keyCode : e.which);
    if(code == 13) { //Enter pressed    
        //alert($("#searchmain").val());
        document.forms['searchform'].submit();              
    }
}

function previousinfo()
{    
    var infonum = Number($('#displayinfo').val());
    //alert(infonum);
    if(infonum>1)
    {
        var div = "div" + infonum;
        var ele = document.getElementById(div);
        ele.style.display = "none";
        infonum--;
        $('#displayinfo').val(infonum);
        div = "div" + infonum; 
        //alert(div);
        ele = document.getElementById(div);
        ele.style.display = "block";        
    }
}

function nextinfo()
{
    var infonum = Number($('#displayinfo').val());
    var totalinfo = Number($('#totalinfo').val());
    if(infonum < totalinfo)
    {
        var div = "div" + infonum;
        var ele = document.getElementById(div);
        ele.style.display = "none";
        infonum++;
        $('#displayinfo').val(infonum);
        div = "div" + infonum; 
        //alert(div);
        ele = document.getElementById(div);
        ele.style.display = "block";             
    }
}

function gotosub()
{
    var displayinfo = $('#displayinfo').val();      
    var div = "div" + displayinfo;
    var input = "#" + div + " input"
    var title =  $(input).val();
    //alert("title="+title);
    var url = "subcategory?category=" + title;
    redirect(url);
}

function redirect(url) {
    window.location = url;
}

</script>

<div>
<table id="filtertable">
<tr>
<td><a href='#'>#</a></td>
<td><a href='#'>A</a></td>
<td><a href='#'>B</a></td>
<td><a href='#'>C</a></td>
<td><a href='#'>D</a></td>
<td><a href='#'>E</a></td>
<td><a href='#'>F</a></td>
<td><a href='#'>G</a></td>
<td><a href='#'>H</a></td>
<td><a href='#'>I</a></td>
<td><a href='#'>J</a></td>
<td><a href='#'>K</a></td>
<td><a href='#'>L</a></td>
<td><a href='#'>M</a></td>
<td><a href='#'>N</a></td>
<td><a href='#'>O</a></td>
<td><a href='#'>P</a></td>
<td><a href='#'>Q</a></td>
<td><a href='#'>R</a></td>
<td><a href='#'>S</a></td>
<td><a href='#'>T</a></td>
<td><a href='#'>U</a></td>
<td><a href='#'>V</a></td>
<td><a href='#'>W</a></td>
<td><a href='#'>X</a></td>
<td><a href='#'>Y</a></td>
<td><a href='#'>Z</a></td>
</tr>
</table>
</div>
<form id="searchform" action="/information/index/searchresult" method="post">
<input type="hidden" name="category" id="category" value="all" />
<div data-role="fieldcontain">
<a href="/information" data-icon="grid" data-role="button" data-iconpos="notext" data-inline="true">Main</a>
<a href="javascript:gotosub();" data-icon="minus" data-role="button" data-iconpos="notext" data-inline="true">Sub</a>
<input type="search" name="searchmain" id="searchmain" value="<?php echo $this->search; ?>" data-inline="true" data-mini="true"/>
<a href="javascript:previousinfo();" data-icon="arrow-l" data-role="button" data-iconpos="notext" data-inline="true">Previous</a>
<a href="javascript:nextinfo();" data-icon="arrow-r" data-role="button" data-iconpos="notext" data-inline="true">Next</a>
</div>
</form>

<input type="hidden" name="displayinfo" id="displayinfo" value="<?php echo $this->displayinfo; ?>" />
<input type="hidden" name="totalinfo" id="totalinfo" value="<?php echo $this->totalinfo; ?>" />
<?php
$data = $this->data;
$count = 0;
foreach($data as $tmp)
{
    $count++;
    $content = $tmp->getContent();
    $title = $tmp->getTitle();

    $divid = "div" . $count;
    if($this->displayinfo == $count)
    {
        echo '<div data-role="collapsible" data-collapsed="false" data-mini="true" id="' . $divid . '">';            
    }
    else
    {
        $style = 'style="display: none;"';
        echo '<div data-role="collapsible" data-collapsed="false" data-mini="true" id="' . $divid . '" '. $style . '>';    
    }
    
    //echo '<div data-role="collapsible" data-collapsed="false" data-mini="true" id="' . $divid . '">';    
    echo '<h3>' . $title . '</h3>';        
    echo '<p>'. $content . '</p>';
    echo '<input type="hidden" name="category" id="category" value="' . $title  .'" />';
    echo '</div>';
    
}


?>

