<?php $this->headStyle()->captureStart();?>
#filtertable { 
    background-color:black;
    font-size:215%; 
}
<?php $this->headStyle()->captureEnd();?>

<script>
$(document).ready(function() {
    //alert("ready");
    $("#searchmain").bind('keypress', keyevent);    
});

function keyevent(e)
{
    var code = (e.keyCode ? e.keyCode : e.which);
    if(code == 13) { //Enter pressed    
        //alert($("#searchmain").val());
        document.forms['searchform'].submit();              
    }
}
</script>

<div>
<table id="filtertable">
<tr>
<td><a href='#'>#</a></td>
<td><a href='#'>A</a></td>
<td><a href='#'>B</a></td>
<td><a href='#'>C</a></td>
<td><a href='#'>D</a></td>
<td><a href='#'>E</a></td>
<td><a href='#'>F</a></td>
<td><a href='#'>G</a></td>
<td><a href='#'>H</a></td>
<td><a href='#'>I</a></td>
<td><a href='#'>J</a></td>
<td><a href='#'>K</a></td>
<td><a href='#'>L</a></td>
<td><a href='#'>M</a></td>
<td><a href='#'>N</a></td>
<td><a href='#'>O</a></td>
<td><a href='#'>P</a></td>
<td><a href='#'>Q</a></td>
<td><a href='#'>R</a></td>
<td><a href='#'>S</a></td>
<td><a href='#'>T</a></td>
<td><a href='#'>U</a></td>
<td><a href='#'>V</a></td>
<td><a href='#'>W</a></td>
<td><a href='#'>X</a></td>
<td><a href='#'>Y</a></td>
<td><a href='#'>Z</a></td>
</tr>
</table>
</div>

<form id="searchform" action="/information/index/searchresult" method="post">
<input type="hidden" name="category" id="category" value="all" />
<fieldset class="ui-grid-a">
    <div class="ui-block-a"><a href="/information" data-icon="grid" data-role="button" data-inline="true" data-iconpos="notext">Main</a></div>
	<div class="ui-block-b"><input type="search" name="searchmain" id="searchmain" value="<?php echo $this->search; ?>" /></div>	   
</fieldset>

<?php
$data=$this->searchresult;
$ids="";
foreach ($data as $tmp)
{
    $ids .= $tmp[1]->getId() . ",";
}
$params = "search=" . $this->search . "&ids=" . $ids;
//echo $params;

foreach ($data as $tmp)
{
    $txt = $tmp[0];
    $title = $tmp[1]->getTitle();
    $id = $tmp[1]->getId();
    $newparams = $params . "&id=" . $id;

    echo '<div data-role="collapsible" data-collapsed="false" data-mini="true">';    
    echo '<h3>' . $title . '</h3>';        
    echo '<a href="infodetail?' . $newparams . '"><p style="color:gray;>'. $txt . '</p></a>';
    echo '</div>';
}
?> 


