<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(function() {
    $('#allmaterials').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    $id = $("#id").val();
    $url = "/project/manage/siteinfo?id=" + $id;
    $("#siteinfodiv").load($url);
});

function gotolist()
{
    window.location = "/project/manage";        
}

function redirect(url) {
    window.location = url;
}
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;

$allmats=$this->allmats;
?>

<input type="hidden" id="id" value="<?php echo $id; ?>" >
<div id="siteinfodiv"></div>

<div data-role="navbar">
	<ul>
		<li><a href="/project/manage/workerlist?id=<?php echo $id; ?>" >工人列表</a></li>
		<li><a href="/project/manage/emachinery?id=<?php echo $id; ?>" >电动机具列表</a></li>
		<li><a href="/project/manage/applist?id=<?php echo $id; ?>" >申请单列表</a></li>
		<li><a href="#" class="ui-btn-active ui-state-persist">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<script>
$(document).ready(function() {
    $('#Applications').dataTable();
} );
</script>

<div data-role="collapsible-set" data-mini="true">
    <div data-role="collapsible" data-collapsed="true">
    <h3>按数量汇总</h3>
<?
echo $this->grid("allmaterials", true)
          ->field('materialid','材料编号')
          ->field('longname','材料名称')
          ->field('amount','数量')
          ->field('unit','单位')
          ->field('price', '单价')
          ->field('totalprice', '合计')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->setSorting(false) 
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Application())
          ->data($allmats);
?>
<br>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>按分类汇总</h3>
    </div>

    </div>
</div>
<br><br>




