<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(document).ready(function() {
    $('#Applications').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    $id = $("#id").val();
    $url = "/project/manage/siteinfo?id=" + $id;
    $("#siteinfodiv").load($url);
} );
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;

$applist=$this->applist;
?>

<input type="hidden" id="id" value="<?php echo $id; ?>" >
<div id="siteinfodiv"></div>

<div data-role="navbar">
	<ul>
		<li><a href="/project/manage/workerlist?id=<?php echo $id; ?>" >工人列表</a></li>
		<li><a href="/project/manage/emachinery?id=<?php echo $id; ?>" >电动机具列表</a></li>
		<li><a href="#" class="ui-btn-active ui-state-persist">申请单列表</a></li>
		<li><a href="/project/manage/allmaterials?id=<?php echo $id; ?>">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<?
echo $this->grid("Applications", true)
          //->field('id','申请单号')
          //->field('site','工地')
          ->field('updatedate','更新时间')
          ->field('applicant','申请人')
          //->field('createdate','创建日期')
          //->field('status0', '申请状态')
          ->field('status1', '办公人员评估')
          ->field('status2', '负责经理评估')
          ->field('details', '申请明细')    
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->setSorting(false) 
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Application())
          ->data($applist);
          //->action(':action', '详细信息', array( 'url'=>array('action'=>'appdetail')));
?>
<br><br>



