<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<style>
#maintable { width:100%; }
#Workers { width:100%; }
#workersdiv { display: none; }
</style>
<script>
$('#start').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  

$('#stop').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  

function submit()
{
    $name = $("#name").val();
    //$remark = $("#remark").val();
    
    if($name=="")
    {
        alert("请至少提供名称，其他信息可稍后提交");
    }    
    else
    {
        $("#mainform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/project/manage";        
}

function redirect(url) {
    window.location = url;
}

function showWorkers()
{
    //alert("showWorkers");
    $("#workersdiv").show();
}
</script>
<?php
$id = 0;
$mode = "Create";
$name="";
$address="";
$start = "";
$stop = "";
$leader="";
$manager="";
$workerno=0;
$remark="";
$leaders=$this->leaders;
$managers=$this->managers;

if($this->mode == "Edit")
{
$data = $this->maindata;
$mode = "Edit";
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();

}
     
?>

<?php
if($mode == "Create")
{
    echo "<h3>添加新工地</h3>";
}
else
{
    echo "<h3>编辑工地信息</h3>";    
}
?>

<form id="mainform" method="post" action="/project/manage/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<table id="maintable">
<tr>
<td><div data-role="fieldcontain">
    <label for="name">工地名称:</label>
    <input type="text" name="name" id="name" value="<?php echo $name; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="address">工地地址:</label>
    <input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true">
</div></td>
</tr>
<tr>
<td><div data-role="fieldcontain">
    <label for="leader">工长:</label>
    <select name="leader" id="leader">
    <?php
    foreach($leaders as $tmp)
    {
        $id = $tmp->getId();
        $name = $tmp->getName();
        if($name == $leader)
        {
        echo '<option value="' . $id . '" selected>' . $name . '</option>';
        }
        else
        {
        echo '<option value="' . $id . '">' . $name . '</option>';
        }
    }
    ?>
    </select>
</div></td>
<td><div data-role="fieldcontain">
    <label for="manager">经理:</label>
    <select name="manager" id="manager">
    <?php
    foreach($managers as $tmp)
    {
        $id = $tmp->getId();
        $name = $tmp->getName();
        echo '<option value="' . $id . '">' . $name . '</option>';
    }
    ?>
    </select>
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="start">开工日期:</label>
    <input type="text" name="start" id="start" value="<?php echo $start; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="stop">竣工日期:</label>
    <input type="text" name="stop" id="stop" value="<?php echo $stop; ?>" data-mini="true">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="remark">其他说明:</label>
    <input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="workerno">工人数量:</label>
 	<input type="range" name="workerno" id="workerno" value="<?php echo $workerno; ?>" min="0" max="200" data-highlight="true" data-mini="false" />
</div></td>
</tr>
<!---->
</table>
</form> <!--main form-->

<div id="workersdiv">
<?php
    echo $this->grid("Workers", true)
          ->field('companylabel', '公司编号')  
          ->field('nameeng', '姓名')
          ->field('namechs','中文名')
          ->field('fin', '准证号码')  
          ->field('worktype', '工种')
          ->field('worklevel', '等级')
          ->field('hwage', '小时工资')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          //->helper(new GridHelper_Worker())
          ->data($this->workers);
?>
</div>

<div class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><input type="button" onclick="cancel()" value="取消"></div>
</div>

