<style>
#maintable { width:100%; }
</style>
<script>
function submit()
{
    $name = $("#name").val();
    //$remark = $("#remark").val();
    
    if($name=="")
    {
        alert("请至少提供供应商名称，其他信息可稍后提交");
    }    
    else
    {
        $("#mainform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/project/manage";        
}

function redirect(url) {
    window.location = url;
}

function showWorkers()
{
    alert("showWorkers");
}
</script>
<?php
$id = 0;
$mode = "Create";
$name="";
$address="";
$start = "";
$stop = "";
$leader="";
$manager="";
$workerno="";
$remark="";

if($this->mode == "Edit")
{
$data = $this->maindata;
$mode = "Edit";
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
}
     
?>
<h3>工地添加与编辑</h3>
<form id="mainform" method="post" action="/project/manage/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">

<div class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><input type="button" onclick="cancel()" value="取消"></div>
</div>
<table id="maintable">
<tr>
<td><div data-role="fieldcontain">
    <label for="name">工地名称:</label>
    <input type="text" name="name" id="name" value="<?php echo $name; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="address">工地地址:</label>
    <input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true">
</div></td>
</tr>
<tr>
<td><div data-role="fieldcontain">
    <label for="leader">工长:</label>
    <input type="text" name="leader" id="leader" value="<?php echo $leader; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="manager">经理:</label>
    <input type="text" name="manager" id="manager" value="<?php echo $manager; ?>" data-mini="true">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="start">开工日期:</label>
    <input type="text" name="start" id="start" value="<?php echo $start; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="stop">停工日期:</label>
    <input type="text" name="stop" id="stop" value="<?php echo $stop; ?>" data-mini="true">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="remark">其他说明:</label>
    <input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="workerno">工人数量:</label>
    <input type="text" name="workerno" id="workerno" value="<?php echo $workerno; ?>" data-mini="true">
</div></td>
</tr>
<!---->
</table>
</form> <!--main form-->

<input type="button" onclick="showWorkers()" value="显示工人列表">
