<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<style>
#maintab { width:100%; }
</style>
<script>
$('#start').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  

$('#stop').mobiscroll().date({
    theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
    endYear: 2050,
});  

function submit()
{
    $name = $("#name").val();
    //$remark = $("#remark").val();
    
    if($name=="")
    {
        alert("请至少提供名称，其他信息可稍后提交");
    }    
    else
    {
        $("#mainform").submit();       
    }
    
}

function cancel()
{
    var r=confirm("放弃编辑信息，返回列表界面");
    if (r==true)
    {
        gotolist();
    }
}

function gotolist()
{
    window.location = "/project/manage";        
}

function redirect(url) {
    window.location = url;
}

function addpart()
{
    var id = $("#id").val();
    var partname= $("#partname").val();
    if(partname=="")
    {
        alert("请填写工程部位名称");
        return;
    }       
    //alert(partname);

    $.post("/project/manage/addpart", { id:id, partname: partname }, 
    function(data) {
        //console.log(data);
        alert(data);        
        window.location.reload();
    });
}

function delpart()
{
    var delpartval = $("#delpart").val();
    if(delpartval==0)
    {
        alert("请选择要删除的部位名称");
        return;
    }    

    var id = $("#id").val();
    var delpart= $("#delpart").find(":selected").text();
    //alert(delpart);
    $.post("/project/manage/delpart", { id:id, delpart:delpart }, 
    function(data) {
        //console.log(data);
        alert(data);        
        window.location.reload();
    });
    
}
</script>
<?php
$id = 0;
$mode = "Create";
$name="";
$address="";
$start = "";
$stop = "";
$manager="";
$workerno=0;
$remark="";
$companyid=0;
$parts="";

$leader="";
$selleaders=array();

$leaders=$this->leaders;
$managers=$this->managers;
$companyinfos=$this->companyinfos;

$contractor="";
$contractors=$this->contractors;
$siteproperties=$this->siteproperties;

$permission1=0;
$permission1arr=$this->permission1arr;

$status="";
$phone="";

if($this->mode == "Edit")
{
    $data = $this->maindata;
    $mode = "Edit";
    $id = $data->getId();
    $name = $data->getName();
    $address = $data->getAddress();
    $start = $data->getStart()->format("Y-m-d");
    $stop = $data->getStop()->format("Y-m-d");
    if($data->getLeader())
    {
        $leader = $data->getLeader()->getName();
    }
    if($data->getManager())
    {
        $manager = $data->getManager()->getName();
    }
    $workerno = $data->getWorkerno();
    $remark = $data->getRemark();
    $companyobj = $data->getCompany();
    if($companyobj) { $companyid = $companyobj->getId(); }
    $parts=$data->getParts();

    $contractor = $data->getContractor();
    $property = $data->getProperty();

    $selLeadersStr=$data->getLeaders() ? $data->getLeaders() : "";
    $selleaders = explode(";", $selLeadersStr);  

    $permission1 = $data->getPermission1() ? 1 : 0;
}
?>
<?php
if($mode == "Create")
{
    echo "<h3>添加工地信息</h3>";
}
else
{
    echo "<h3>编辑工地信息</h3>";    
}
?>
<form id="mainform" method="post" action="/project/manage/submit" enctype="multipart/form-data">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<table class="" id="maintab">
<tr>
<td><div data-role="fieldcontain">
    <label for="name">工地名称:</label>
    <input type="text" name="name" id="name" value="<?php echo $name; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="address">工地地址:</label>
    <input type="text" name="address" id="address" value="<?php echo $address; ?>" data-mini="true">
</div></td>

</tr>
<tr>
<td><div data-role="fieldcontain">
    <label for="contractor">总包单位:</label>
    <select name="contractor" id="contractor" data-mini="true">
    <option value="0"></option>
<?php
if(isset($contractors))
{
    foreach($contractors as $tmp)
    {
        if($tmp == "")
        {
            continue;
        }

        if($tmp == $contractor)
        {
            echo '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
        }
        else
        {
            echo '<option value="' . $tmp . '">' . $tmp . '</option>';    
        }
    }
}
?>
    </select>
</div></td>

<td><div data-role="fieldcontain">
    <label for="property">工地性质:</label>
    <select name="property" id="property" data-mini="true">
    <option value="0"></option>
<?php
if(isset($siteproperties))
{
    foreach($siteproperties as $tmp)
    {
        if($tmp == "")
        {
            continue;
        }

        if($tmp == $property)
        {
            echo '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
        }
        else
        {
            echo '<option value="' . $tmp . '">' . $tmp . '</option>';    
        }
    }
}
?>
    </select>
</div></td>

</tr>
<td><div data-role="fieldcontain">
    <label for="remark">承包公司:</label>    
    <select id="company" name="company" data-mini="true">
    <option value="0">未指定承包公司</option>
<?
$options="";    
foreach($companyinfos as $tmp)
{
    $id = $tmp->getId();
    $namechs = $tmp->getNamechs(); 

    if($companyid == $id)
    {       
        $options .= '<option value="' . $id . '" selected>' . $namechs . '</option>';    
    }
    else
    {
        $options .= '<option value="' . $id . '" >' . $namechs . '</option>';    
    }
}
echo $options;
?>
    </select>
</div></td>

<td><div data-role="fieldcontain">
    <label for="leaders">工长:</label>
    <!--http://stackoverflow.com/questions/13727127/submit-data-of-select-multiple-in-jquery-mobile-->
    <select name=leaders[] id="leaders" data-mini="true" data-native-menu="false" multiple="multiple">
    <option value=""></option>
    <?php
    foreach($leaders as $tmp)
    {
        $id = $tmp->getId();
        $name = $tmp->getName();
        //if($name == $leader)
        if(in_array($id, $selleaders))
        {
        echo '<option value="' . $id . '" selected>' . $name . '</option>';
        }
        else
        {
        echo '<option value="' . $id . '" >' . $name . '</option>';
        }
    }
    ?>
    </select>
</div>
</td>

<tr>
<td><div data-role="fieldcontain">
    <label for="start">开工日期:</label>
    <input type="text" name="start" id="start" value="<?php echo $start; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="stop">竣工日期:</label>
    <input type="text" name="stop" id="stop" value="<?php echo $stop; ?>" data-mini="true">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="workerno">工人数量:</label>
 	<input type="range" name="workerno" id="workerno" value="<?php echo $workerno; ?>" min="0" max="200" data-highlight="true" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="remark">其他说明:</label>
    <input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true">
</div></td>
<td></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="permission1">材料申请:</label>
    <select id="permission1" name="permission1" data-mini="true">
<?
$options="";
foreach($permission1arr as $key => $value)
{    
    if($key == $permission1)
    {       
        $options .= '<option value="' . $key . '" selected>' . $value . '</option>';    
    }
    else
    {
        $options .= '<option value="' . $key . '" >' . $value . '</option>';    
    }
}
echo $options;
?>
    </select>
</div></td>
<td><div data-role="fieldcontain">
    <label for="status">工程进度:</label>
    <select id="status" name="status" data-mini="true">
<?
$options="";
foreach($permission1arr as $key => $value)
{    
    if($key == $permission1)
    {       
        $options .= '<option value="' . $key . '" selected>' . $value . '</option>';    
    }
    else
    {
        $options .= '<option value="' . $key . '" >' . $value . '</option>';    
    }
}
echo "&nbsp;";//$options;
?>
    </select>
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="phone">联系电话:</label>    
    <input type="text" name="phone" id="phone" value="<?php echo $phone; ?>" data-mini="true">
</div></td>
<td></td>
</tr>

</table>
</form> <!--main form-->

<fieldset <?php if($mode=="Create") echo 'style=display:none'; ?>>
<legend>定义工程部位</legend>
<div data-role="collapsible-set" data-mini="true">
    <div data-role="collapsible" data-collapsed="true">
    <h3>增加工程部位</h3>
    <input type="text" value="" placeholder='填写部位名称不能含有;/"等符号，一次填写一个名称并提交' id="partname">
    <button data-mini="true" data-theme="a" onclick="addpart()">增加</button>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>删除工程部位</h3>
    <select data-mini="true" id="delpart">
    <option value="0">选择要删除的部位名称</option>
<?php
$partsArr=explode(";", $parts);
$i=0;
$options="";
foreach($partsArr as $tmp)
{
    $i++;
    $options .= '<option value="' . $i . '">' . $tmp . '</option>'; 
}
echo $options;
?>    
    </select>    
    <button data-mini="true" data-theme="a" onclick="delpart()">删除</button>
    </div>
</div> 
<hr>
<p><strong>
<?php if($parts=="") echo "尚未定义任何工程部位"; else echo $parts; ?>
</strong></p>
</fieldset>

<script>
$("#partsdefine").load("/project/manage/partsdefine"); 
</script>
<div class="ui-grid-a">
		<div class="ui-block-a"><button type="submit" data-theme="a" onclick="submit()">提交</button></div>
		<div class="ui-block-b"><input type="button" onclick="cancel()" value="取消"></div>
</div>

