<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(function() {
    $('#Emachinery').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    $id = $("#id").val();
    $url = "/project/manage/siteinfo?id=" + $id;
    $("#siteinfodiv").load($url);
});
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart() ? $data->getStart()->format("Y-m-d") : "";
$stop = $data->getStop() ? $data->getStop()->format("Y-m-d") : "";
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;

$emachineries=$this->emachineries;
?>

<input type="hidden" id="id" value="<?php echo $id; ?>" >
<div id="siteinfodiv"></div>

<div data-role="navbar">
	<ul>
		<li><a href="/project/manage/workerlist?id=<?php echo $id; ?>" >工人列表</a></li>
		<li><a href="#" class="ui-btn-active ui-state-persist">电动机具列表</a></li>
		<li><a href="/project/manage/applist?id=<?php echo $id; ?>">申请单列表</a></li>
		<li><a href="/project/manage/allmaterials?id=<?php echo $id; ?>">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<?
echo $this->grid("Emachinery", true)
          ->field('material','名称')
          ->field('purchasedate', '购买日期')  
          ->field('sn', '序列号')  
          ->field('status', '状态')  
          ->field('remark', '说明')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Emachinery())
          ->data($emachineries);
?>




