<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(function() {
    $('#Emachinery').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
});
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;

$emachineries=$this->emachineries;
?>

<fieldset>
<legend>工地详细信息</legend>
<table class="" id="sitetab">
<tr>
<td>工地名称:</td><td><strong><?php echo $name; ?></strong></td>
<td>工地地址:</td><td><strong><?php echo $address; ?></strong></td>
</tr>
<tr>
<td>总包单位:</td><td><strong><?php echo $contractor; ?></strong></td>
<td>工地性质:</td><td><strong><?php echo $property; ?></strong></td>
</tr>
<tr>
<td>承包公司:</td><td><strong><?php echo $company; ?></strong></td>
<td>工长:</td><td><strong><?php echo $leaders; ?></strong></td>
</tr>
<tr>
<td>开工日期:</td><td><strong><?php echo $start; ?></strong></td>
<td>竣工日期:</td><td><strong><?php echo $stop; ?></strong></td>
</tr>
</table>
</fieldset>

<div data-role="navbar">
	<ul>
		<li><a href="/project/manage/workerlist?id=<?php echo $id; ?>" >工人列表</a></li>
		<li><a href="#" class="ui-btn-active ui-state-persist">电动机具列表</a></li>
		<li><a href="/project/manage/applist?id=<?php echo $id; ?>">申请单列表</a></li>
		<li><a href="/project/manage/allmaterials?id=<?php echo $id; ?>">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<?
echo $this->grid("Emachinery", true)
          ->field('material','名称')
          ->field('purchasedate', '购买日期')  
          ->field('sn', '序列号')  
          ->field('status', '状态')  
          ->field('remark', '说明')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Emachinery())
          ->data($emachineries);
?>




