<style>
#Sites { width:100%; }
</style>
<div><a href="/project/manage/add"><button>添加新工地</button></a></div>
<div>
<?
echo $this->grid("Sites", true)
          ->field('name','工地名称')
          ->field('address', '地址')
          ->field('leader', '工长')  
          ->field('workerno', '工人数')  
          ->field('start', '开工日期')
          ->field('stop', '停工日期')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Project())
          ->data($this->maindata)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>

