<script>
    $(function() {
        $('#Sites').dataTable({
            "iDisplayLength": 100,
            "bRetrieve": true,
            "aaSorting": [[0, "desc"]],
        });
    });

</script>

<div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="false">
        <h3>工程工地</h3>
        <div>
            <a href="/project/manage/add"><button data-theme="a" data-mini="true">添加工地</button></a>
            <?php
            echo $this->grid("Sites", true)
                    ->field('name', '工地名称')
                    ->field('company', '承包公司')
                    ->field('contractor', '总包公司')
                    ->field('leaders', '工长')
                    ->field('start', '开工日期')
                    ->field('stop', '竣工日期')
                    ->field('postr', 'PO字串')
                    ->actionField(':action', "操作", '&nbsp;|&nbsp;')
                    ->paginatorEnabled(false)
                    ->setSorting(false)
                    ->helper(new GridHelper_Project())
                    ->data($this->workingsites)
                    ->action(':action', '详细', array('url' => array('action' => 'sitedetail')))
                    ->action(':action', '编辑', array('url' => array('action' => 'edit')))
                    ->action(':action', '工程结束', array('url' => array('action' => 'sitestatus')));
                    //->action(':action', '删除', array('url' => array('action' => 'delete')));
            ?>
        </div>
        <br>
    </div>

    <div data-role="collapsible" data-collapsed="true">
        <h3>竣工工地</h3>
        <div>
            <?php
            echo $this->grid("Sites", true)
                    ->field('name', '工地名称')
                    ->field('company', '承包公司')
                    ->field('contractor', '总包公司')
                    ->field('leaders', '工长')
                    ->field('start', '开工日期')
                    ->field('stop', '竣工日期')
                    ->field('postr', 'PO字串')
                    ->actionField(':action', "操作", '&nbsp;|&nbsp;')
                    ->paginatorEnabled(false)
                    ->setSorting(false)
                    ->helper(new GridHelper_Project())
                    ->data($this->completedsites)
                    ->action(':action', '详细', array('url' => array('action' => 'sitedetail')))
                    ->action(':action', '编辑', array('url' => array('action' => 'edit')))
                    ->action(':action', '工程继续', array('url' => array('action' => 'sitestatus')));
                    //->action(':action', '删除', array('url' => array('action' => 'delete')));
            ?>
        </div>    
    </div>

</div>
