<style>
#sitetab { width:100%; }
</style>
<script>
function gotolist()
{
    window.location = "/project/manage";        
}

function redirect(url) {
    window.location = url;
}
</script>
<?php
$id = 0;
$mode = "Create";
$name="";
$address="";
$start = "";
$stop = "";
$leader="";
$manager="";
$workerno=0;
$remark="";
$leaders=$this->leaders;
$managers=$this->managers;
$contractor="";
$property="";
$company="";
//$selleaders="";

if(1)
{
$data = $this->maindata;
$mode = "Edit";
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";

}   
?>

<!--<h4>工地详细信息</h4>-->
<table class="" id="sitetab">
<thead><strong>工地详细信息</strong></thead>
<tr>
<td>工地名称:</td><td><?php echo $name; ?></td>
<td>工地地址:</td><td><?php echo $address; ?></td>
</tr>
<tr>
<td>总包单位:</td><td><?php echo $contractor; ?></td>
<td>工地性质:</td><td><?php echo $property; ?></td>
</tr>
<tr>
<td>承包公司:</td><td><?php echo $company; ?></td>
<td>工长:</td><td><?php echo $leaders; ?></td>
</tr>
<tr>
<td>开工日期:</td><td><?php echo $start; ?></td>
<td>竣工日期:</td><td><?php echo $stop; ?></td>
</tr>
</table>

<div data-role="collapsible-set" data-mini="true">
    <div data-role="collapsible" data-collapsed="true">
    <h3>工人列表</h3>
<?php
    echo $this->grid("Workers", true)
          //->field('companylabel', '公司编号')  
          ->field('nameeng', '姓名')
          ->field('namechs','中文名')
          ->field('fin', '准证号码')  
          ->field('worktype', '工种')
          ->field('worklevel', '等级')
          ->field('hwage', '小时工资')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          //->helper(new GridHelper_Worker())
          ->data($this->workers);
?>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>机械列表</h3>
    <input type="text" value="" placeholder='填写部位名称不能含有;/"等符号，一次填写一个名称并提交' id="partname">
    <button data-mini="true" data-theme="a" onclick="addpart()">增加</button>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>申请单列表</h3>
<?
echo $this->grid("Applications", true)
          ->field('applicant','申请人')
          ->field('createdate','创建日期')
          ->field('updatedate','更新日期')
          ->field('status0', '申请状态')
          ->field('status1', '办公人员评估')
          ->field('status2', '负责经理评估')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Application())
          ->data($this->applications)
          ->action(':action', '详细信息', array( 'url'=>array('action'=>'appedit')));
?>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>总申请材料列表</h3>
    <input type="text" value="" placeholder='填写部位名称不能含有;/"等符号，一次填写一个名称并提交' id="partname">
    <button data-mini="true" data-theme="a" onclick="addpart()">增加</button>
    </div>

</div>

