<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;
?>
<fieldset>
<legend>工地详细信息</legend>
<table class="" id="sitetab">
<tr>
<td>工地名称:</td><td><strong><?php echo $name; ?></strong></td>
<td>工地地址:</td><td><strong><?php echo $address; ?></strong></td>
</tr>
<tr>
<td>总包单位:</td><td><strong><?php echo $contractor; ?></strong></td>
<td>工地性质:</td><td><strong><?php echo $property; ?></strong></td>
</tr>
<tr>
<td>承包公司:</td><td><strong><?php echo $company; ?></strong></td>
<td>工长:</td><td><strong><?php echo $leaders; ?></strong></td>
</tr>
<tr>
<td>开工日期:</td><td><strong><?php echo $start; ?></strong></td>
<td>竣工日期:</td><td><strong><?php echo $stop; ?></strong></td>
</tr>
</table>
</fieldset>

