<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(function() {
    $('#Workerlist').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    $id = $("#id").val();
    $url = "/project/manage/siteinfo?id=" + $id;
    $("#siteinfodiv").load($url);
});
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart() ? $data->getStart()->format("Y-m-d") : "";
$stop = $data->getStop() ? $data->getStop()->format("Y-m-d") : "";
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;
$records=$this->records;
?>

<input type="hidden" id="id" value="<?php echo $id; ?>" >
<div id="siteinfodiv"></div>

<div data-role="navbar">
	<ul>
		<li><a href="#" class="ui-btn-active ui-state-persist">工人列表</a></li>
		<li><a href="/project/manage/emachinery?id=<?php echo $id; ?>">电动机具列表</a></li>
		<li><a href="/project/manage/applist?id=<?php echo $id; ?>">申请单列表</a></li>
		<li><a href="/project/manage/allmaterials?id=<?php echo $id; ?>">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<?
echo $this->grid("Workerlist", true)
          ->field('worktype','工种')
          ->field('workername','工人名字')
          ->field('begindate1','开始日期')
          ->field('enddate1','结束日期')
          ->field('remark1','说明')
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->setSorting(false) 
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Workeronsite())
          ->data($records);
?>
<br><br>
