<style>
#sitetab { width:100%; }
#sitetab td { width:25%; }
</style>
<script>
$(function() {
    $('#Workerlist').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
});
</script>
<?php
$data = $this->maindata;
$id = $data->getId();
$name = $data->getName();
$address = $data->getAddress();
$start = $data->getStart()->format("Y-m-d");
$stop = $data->getStop()->format("Y-m-d");
if($data->getLeader())
{
    $leader = $data->getLeader()->getName();
}
if($data->getManager())
{
    $manager = $data->getManager()->getName();
}
$workerno = $data->getWorkerno();
$remark = $data->getRemark();
$contractor=$data->getContractor();
$property=$data->getProperty();
$cmyobj=$data->getCompany();
$company= $cmyobj ? $cmyobj->getNamechs(): "";
$leaders=$this->leaders;
$managers=$this->managers;
$records=$this->records;
?>

<fieldset>
<legend>工地详细信息</legend>
<table class="" id="sitetab">
<tr>
<td>工地名称:</td><td><strong><?php echo $name; ?></strong></td>
<td>工地地址:</td><td><strong><?php echo $address; ?></strong></td>
</tr>
<tr>
<td>总包单位:</td><td><strong><?php echo $contractor; ?></strong></td>
<td>工地性质:</td><td><strong><?php echo $property; ?></strong></td>
</tr>
<tr>
<td>承包公司:</td><td><strong><?php echo $company; ?></strong></td>
<td>工长:</td><td><strong><?php echo $leaders; ?></strong></td>
</tr>
<tr>
<td>开工日期:</td><td><strong><?php echo $start; ?></strong></td>
<td>竣工日期:</td><td><strong><?php echo $stop; ?></strong></td>
</tr>
</table>
</fieldset>

<div data-role="navbar">
	<ul>
		<li><a href="#" class="ui-btn-active ui-state-persist">工人列表</a></li>
		<li><a href="/project/manage/emachinery?id=<?php echo $id; ?>">电动机具列表</a></li>
		<li><a href="/project/manage/applist?id=<?php echo $id; ?>">申请单列表</a></li>
		<li><a href="/project/manage/allmaterials?id=<?php echo $id; ?>">材料汇总</a></li>
	</ul>
</div><!-- /navbar -->

<?
echo $this->grid("Workerlist", true)
          ->field('worktype','工种')
          ->field('workername','工人名字')
          ->field('begindate1','开始日期')
          ->field('enddate1','结束日期')
          ->field('remark1','说明')
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->setSorting(false) 
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Workeronsite())
          ->data($records);
?>
<br><br>
