<link rel="stylesheet"  href="/common/datebox/jqm-datebox-1.1.0.css" /> 
<script src="/common/datebox/jqm-datebox-1.1.0.core.js"></script>
<script src="/common/datebox/jqm-datebox-1.1.0.mode.calbox.js"></script>
<script src="/common/datebox/jqm-datebox-1.1.0.mode.datebox.js"></script>

<script>
    $(function() {
        $('#Workersdata').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
        });

   
    });

        $('#salarymonth').bind('datebox', function(e, passed) {
            if (passed.method === 'close') {
                //$('element').datebox('disable');
                var val = $(this).val();
                alert(val);
            }
        });
        $('#receiptdate').bind('datebox', function(e, passed) {
            if (passed.method === 'close') {
                //$('element').datebox('disable');
                var val = $(this).val();
                alert(val);
            }
        });     

    $("#sheetselect").change(function() {
        var sheetname = $(this).val();
        var url = "/salary/salary?sheet=" + sheetname;
        redirect(url);
    });

    function redirect(url) {
        window.location = url;
    }

    function gensalarydata(month)
    {
        //alert(month);

        var sheet = $("#sheetselect").val();
        $.post("/salary/salary/gensalaryrecords", {sheet: sheet, month: month},
        function(data) {
            alert("工资数据已生成");
            //console.log(data);
            //window.location.reload();
        })
    }
</script>
<?php
$sheetarr = $this->sheetarr;
$sheet = $this->sheet;
$maindata = $this->workerarr;

$nowdate = new Datetime("now");
$thismonth = $nowdate->format("Y-m");
$thismonth1 = $nowdate->format("Ym");
$lastmonth = date('Y-m', strtotime("last month"));
$lastmonth1 = date('Ym', strtotime("last month"));

$thismonthurl = "/salary/salary/salarybymonth?sheet=$sheet&month=$thismonth";
$lastmonthurl = "/salary/salary/salarybymonth?sheet=$sheet&month=$lastmonth";

$lastmonthpayslipsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$lastmonth";
$thismonthpayslipsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$thismonth";
?>

<div class="ui-grid-a">
    <div class="ui-block-a">
        <input id="salarymonth" placeholder="选择详细工资输出月份" 
               data-role="datebox" data-options='{"mode":"datebox"}'>
    </div>
    <div class="ui-block-b">
        <input id="receiptdate" placeholder="选择工资收据生成日期" 
               data-role="datebox" data-options='{"mode":"datebox"}'>
    </div>

    <div class="ui-block-a">
        <button data-mini="true" data-theme="a">详细工资</button>            
    </div>
    <div class="ui-block-b">        
        <button data-mini="true" data-theme="a">工资收据</button>        
    </div>

</div>
<hr>
<?php
$options = "";
foreach ($sheetarr as $tmp) {
    if ($sheet == $tmp) {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    } else {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects = '<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;

$onswitches = array(
    "sn" => "S/N", "eeeno" => "E'ee No.", "namechs" => "Name Chs", "nameeng" => "Name Eng", "wpno" => "WP No.",
    "ppno" => "PP No.", "rate" => "RATE",);

$wdtab = $this->grid("Workersdata", true);
foreach ($onswitches as $key => $value) {
    $wdtab = $wdtab->field($key, $value);
}
$wdtab = $wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab = $wdtab->paginatorEnabled(false)->setSorting(false);
//$wdtab=$wdtab->helper(new GridHelper_Worker());
$wdtab = $wdtab->data($maindata)->action(':action', '工资', array('url' => array('action' => 'personal')));
//$wdtab=$wdtab->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
echo $wdtab;
?>
<br><br>
