<script>
$(function() {
    $('#Workersdata').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
} );

$("#sheetselect").change(function() {
    var sheetname = $(this).val();
    var url = "/salary/salary?sheet=" + sheetname;
    redirect(url);
});

function redirect(url) {
    window.location = url;
}

function gensalarydata(month) 
{
    //alert(month);

    var sheet = $("#sheetselect").val();
    $.post("/salary/salary/gensalaryrecords", { sheet:sheet, month:month }, 
    function(data) {
        alert("工资数据已生成");
        //console.log(data);
        //window.location.reload();
    })   

}
</script>
<?php
$sheetarr=$this->sheetarr;
$sheet=$this->sheet;
$maindata=$this->workerarr;

$nowdate=new Datetime("now");
$thismonth=$nowdate->format("Y-m");
$thismonth1=$nowdate->format("Ym");
$lastmonth=date('Y-m', strtotime("last month"));
$lastmonth1=date('Ym', strtotime("last month"));

$thismonthurl="/salary/salary/salarybymonth?sheet=$sheet&month=$thismonth";
$lastmonthurl="/salary/salary/salarybymonth?sheet=$sheet&month=$lastmonth"; 

$lastmonthpayslipsurl="/salary/salary/salaryreceipts?sheet=$sheet&month=$lastmonth";
$thismonthpayslipsurl="/salary/salary/salaryreceipts?sheet=$sheet&month=$thismonth";
$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;

?>

<div class="ui-grid-a">
	<!--<div class="ui-block-a">
        <button data-mini="true" data-theme="a" onclick="gensalarydata(<?=$lastmonth1?>)">生成工资数据(<?=$lastmonth?>)</button>
    </div>-->
	<div class="ui-block-a"><a href="<?=$lastmonthurl?>" target="_blank">
<button data-mini="true" data-theme="a">查看详细工资(<?=$lastmonth?>)</button></a></div>
	<div class="ui-block-b"><a href="<?=$lastmonthpayslipsurl?>" target="_blank">
<button data-mini="true" data-theme="a">查看工资单(<?=$lastmonth?>)</button></a></div>

	<!--<div class="ui-block-a"><a href="<?=$genthismonthurl?>" target="_blank">
<button data-mini="true" data-theme="a">生成工资数据(<?=$thismonth?>)</button></a></div>-->
	<div class="ui-block-a"><a href="<?=$thismonthurl?>" target="_blank">
<button data-mini="true" data-theme="a">查看详细工资(<?=$thismonth?>)</button></a></div>
	<div class="ui-block-b"><a href="<?=$thismonthpayslipsurl?>" target="_blank">
<button data-mini="true" data-theme="a">查看工资单(<?=$thismonth?>)</button></a></div>

	<!--<div class="ui-block-a"><a href="#"><button data-mini="true" data-theme="a">&nbsp;</button></a></div>-->
	<div class="ui-block-a"><a href="#"><button data-mini="true" data-theme="a">查看详细工资历史</button></a></div>
	<div class="ui-block-b"><a href="#"><button data-mini="true" data-theme="a">查看工资单历史</button></a></div>
</div>

<?php
$onswitches=array(
"sn"=>"S/N","eeeno"=>"E'ee No.","namechs"=>"Name Chs","nameeng"=>"Name Eng","wpno"=>"WP No.", 
"ppno"=>"PP No.", "rate"=>"RATE",);

$wdtab=$this->grid("Workersdata", true);
foreach($onswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
$wdtab=$wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab=$wdtab->paginatorEnabled(false)->setSorting(false);
//$wdtab=$wdtab->helper(new GridHelper_Worker());
$wdtab=$wdtab->data($maindata)->action(':action', '工资', array( 'url'=>array('action'=>'personalsalary')));
//$wdtab=$wdtab->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
echo $wdtab;
?>
<br><br>
