<!DOCTYPE html> 
<html>
    <?php
    $sheetsel = $this->sheetsel;
    $yearsel = $this->yearsel;
    $workersel = $this->workersel;

    $worker = $this->worker;
    if ($worker) {
        $workername = ($worker->getNamechs() == "") ? $worker->getNameeng() : $worker->getNamechs();
    } else {
        $workername = "";
    }
    $records = $this->recordsbyyear;

    $salarytabs = $this->salarytabs;
    $salaryall = $this->salaryall;
    $salaryallformat = $this->salaryallformat;
    
    $salaryreceiptsurl = "/salary/salary/salaryreceipts?sheet=$sheet&month=$monthstr";
    ?>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>历史工资列表<?php if ($workername !== "") echo "-" . $workername; ?></title> 
        <link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
        <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
        <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
        <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>

        <!--<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
        <script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>-->
    </head> 

    <body> 
        <style>
            #headertab { width: 100%; table-layout:fixed; }
            #headertab td, table th { text-align:left; border:0px solid black; text-align: center; }
            table { width: 100%; border-collapse:collapse; /*table-layout:fixed;*/}
            table td, table th { text-align:center; border:1px solid black; }

            .ui-dialog-contain {
                width: 92.5%;
                max-width: 2500px;
                margin: 3% auto 15px auto;
                padding: 0;
                position: relative;
                top: -15px;
            }

            .attendsum  { background-color:#D0D0D0; }
            .fixwidthcol { width:45px; }
            .tdattendfood { width:150px; }
            .workerinfo { background: #D0D0D0 /*#6FACD5*/; 
                          /*linear-gradient(#6FACD5, #497BAE) repeat scroll 0 0 #5E87B0;*/
                          /*linear-gradient(#5F9CC5, #396B9E) repeat scroll 0 0 #396B9E*/ 
                          table-layout:fixed;
            }

            .workerpay { /*background: #ff5555; */
                background: linear-gradient(#6FACD5, #497BAE) repeat scroll 0 0 #5E87B0;
                border: 1px solid #456F9A;
                color: #FFFFFF;
                font-weight: bold;
                text-shadow: 0 1px 1px #3E6790;
            }

            .noborder td { border:0px; } 
        </style>
        <script>
            $(function() {
                $("#sheetsel").on("change", function() {
                    //alert("sheet change");
                    var sheetname = $(this).val();
                    var url = "/salary/salary/personal?sheet=" + sheetname;
                    redirect(url);
                });

                $("#workersel").on("change", function() {
                    //alert("change");
                    var id = $(this).val();
                    var url = "/salary/salary/personal?";
                    url += "id=" + id;
                    redirect(url);
                });

                $("#yearsel").on("change", function() {
                    //alert("year change");
                    var id = $("#workersel").val();
                    var year = $(this).val();
                    var url = "/salary/salary/personal?";
                    url += "id=" + id;
                    url += "&year=" + year;
                    redirect(url);
                });
            });

            function redirect(url) {
                window.location = url;
            }
        </script>
        <div data-role="page">

            <div data-role="header" >
                <table id="headertab">
                    <tr>
                        <td>历史工资列表</td>
                        <!--<td>工人:&nbsp;<?= $workername ?></td>-->
                    </tr>
                </table>
            </div><!-- /header -->

            <div data-role="content">
                <div id="error"><?= $this->error ?></div>

                <div class="ui-grid-c">
                    <div class="ui-block-a"><?= $sheetsel ?></div>
                    <div class="ui-block-b"><?= $workersel ?></div>                    
                    <div class="ui-block-c"><?= $yearsel ?></div>
                    <div class="ui-block-d">
                        <a href="<?= $salaryreceiptsurl ?>" data-mini="true" data-role="button" data-theme="b" target="_blank">
                            工资单
                        </a>
                    </div>
                </div>
                <hr>
                <span>总工资:&nbsp; <strong><?= $salaryallformat ?></strong></span>
                <hr>
<?php
$divno = 0;
$alltabs = "";
if (count($salarytabs)) {
    foreach ($salarytabs as $tmp) {
        $alltabs = "";

        $tab0 = $tmp[0]; // worker
        $tab1 = $tmp[1]; // salary
        $tab2 = $tmp[2]; // attend
        $alltabs .= $tab0;
        $alltabs .= $tab1;
        $alltabs .= $tab2;
        //$alltabs .= "<br>";

        $divno++;
        echo "<div id=worker$divno>
                            " . $alltabs . "</div><br>
                            ";
    }
}
?>
            </div><!-- /content -->

            <!--<div data-role="footer">
                <h4>Footer content</h4>
            </div>--><!-- /footer -->

        </div><!-- /page -->

    </body>
</html>

