<style>
#Humanres { width:100%; }
</style>
<div><a href="/humanresource/manage/add"><button>注册行政人员</button></a></div>
<div>
<?
echo $this->grid("Humanres", true)
          ->field('name', '中文名')
          ->field('nameeng', '英文名')
          ->field('role', '职位')
          ->field('phone1', '电话')
          ->field('email1', '电邮')
          ->field('date', '更新日期')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Humanres())
          ->data($this->humanres)
          ->action(':action', '更多信息', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>

