<script>
$(function() {
    $('#Humanres').dataTable();
});
</script>
<a href="/humanresource/manage/add"><button data-mini="true" data-theme="a">注册行政人员</button></a>
<div>
<?
echo $this->grid("Humanres", true)
          //->field('id', '序号')
          ->field('role', '职位')
          ->field('name', '中文名')
          ->field('nameeng', '英文名')
          ->field('phone1', '电话')
          ->field('email1', '电邮')
          ->field('date', '更新日期')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Humanres())
          ->data($this->humanres)
          ->action(':action', '更多信息', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>

