<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<script>
$(function () {
    //alert("scroller");
    $('.classupdate').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

});

function submitform()
{
    //alert("submitform");    
    $("#dataform").submit();
}

function redirect(url) {
    window.location = url;
}

$('.defsupplier').change( function() {
    var id = $(this).attr("id");
    //alert("defsupplier id="+id);
    $("#defsupplierid").val(id);
});
</script>
<?php
$data=$this->maindata;
$mode=$this->mode;//"Create";
$id=0;
$name="";
$nameeng="";
$spec="";
$description="";
$supplier="";
$date="";
$suppliers=$this->suppliers;
$pic="";
$usage="";
$typeid=0;
$defsupplierid=0;

if($mode==="Edit")
{
$id=$data->getId();
$name=$data->getName();
$nameeng=$data->getNameeng();
//$spec=$data->getSpec();
$description=$data->getDescription();
if($data->getSupplier()){ $supplier=$data->getSupplier()->getName(); }
$date=$data->getUpdate()->format('Y/m/d');
$pic=$data->getPic();
$usage="";
$typeobj=$data->getType();
if($typeobj) { $typeid=$typeobj->getId(); } 
$defsupplier=$data->getSupplier();
if($defsupplier)
{
    $defsupplierid=$defsupplier->getId(); 
}
}

$header="<h3>编辑电动机具信息</h3>";
if($mode=="Create")
{
    $header="<h3>注册电动机具</h3>";
}
echo $header;
?>

<form id="dataform" enctype="multipart/form-data" method="post" action="/material/emachinery/submit">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">
<input type="hidden" id="defsupplierid" name="defsupplierid" value="<?php echo $defsupplierid; ?>">

<table class="grid">
<tr>
<td style="width:50%"><div data-role="fieldcontain">
<label for="namechs">选择电动机具:</label>
<input type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" data-mini="true">
</div></td>
<td></td>
</tr>

<tr>
<td style="width:50%"><div data-role="fieldcontain">
<label for="namechs">中文名:</label>
<input type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
<label for="nameeng">英文名:</label>
<input type="text" name="nameeng" id="nameeng" value="<?php echo $nameeng; ?>" data-mini="true">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
<label for="purchasedate">购买日期:</label>
<input type="text" name="purchasedate" id="purchasedate" value="<?php echo $purchasedate; ?>" data-mini="true" placeholder="">
</div></td>
<td><div data-role="fieldcontain">
<label for="sn">序列号:</label>
<input type="text" name="sn" id="sn" value="<?php echo $sn; ?>" data-mini="true" placeholder="">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
<label for="site">所在工地:</label>
<input type="text" name="site" id="site" value="<?php echo $spec; ?>" data-mini="true" placeholder="">
</div></td>
<td><div data-role="fieldcontain">
<label for="status">设备状态:</label>
<input type="text" name="status" id="status" value="<?php echo $spec; ?>" data-mini="true" placeholder="">
</div></td>
</tr>

<tr><td>
<div data-role="fieldcontain">
<label for="remark">其他说明:</label>
<input type="text" name="remark" id="remark" value="" data-mini="true" placeholder="">
</div>
</td>
<td></td>
</tr>
</table>

</form> <!-- dataform -->
<button type="button" id="submitbutton" name="submitbutton" onclick="submitform()" data-theme="a" data-mini="true">提交</button>

