<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<script>
$(function () {
    //alert("scroller");
    $('.datepicker').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

});

function submitform()
{
    //alert("submitform"); 
    var materialid = $('#material').val();   
    if(materialid=="0")
    {
        alert("请选择电动机具");
        return;
    }

    $("#dataform").submit();
}

function redirect(url) {
    window.location = url;
}

</script>
<?php
$id=0;
$mode=$this->mode;
$materials=$this->materials;
$sites=$this->sites;
$purchasedate="";
$sn="";
$emstatus="";
$remark="";
$statusArr=$this->statusArr;
$scrapdate="";
$materialid=0;
$siteid=0;

if($mode==="Edit")
{
$data=$this->data;
$id=$data->getId();
$thedate=$data->getPurchasedate();
$purchasedate=$thedate ? $thedate->format("Y/m/d") : ""; 
$sn=$data->getSn();
$emstatus=$data->getStatus();
$remark=$data->getRemark();

$thedate=$data->getScrapdate();
$scrapdate=$thedate ? $thedate->format("Y/m/d") : ""; 

$materialid=$data->getMaterial()->getId();
$siteid=$data->getSite()->getId();
}

$header="<h3>编辑电动机具信息</h3>";
if($mode=="Create")
{
    $header="<h3>注册电动机具</h3>";
}
echo $header;
?>

<form id="dataform" enctype="multipart/form-data" method="post" action="/material/emachinery/submit">
<input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
<input type="hidden" id="id" name="id" value="<?php echo $id; ?>">

<table class="grid">
<tr>
<td style="width:50%"><div data-role="fieldcontain">
<label for="material">电动机具:</label>
<select id="material" name="material" data-mini="true">
<option value="0">请选择</option>
<?php
$options="";
foreach($materials as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    $nameeng = $tmp->getNameeng();
    $namelong = $name . "/" . $nameeng;

    if($materialid == $id)
    {
        $option = '<option value="'. $id . '" selected>' . $namelong . '</option>';
    }
    else
    {    
        $option = '<option value="'. $id . '">' . $namelong . '</option>';
    }
    $options .= $option;
}
echo $options;
?>
</select>
</div></td>
<td><div data-role="fieldcontain">
<label for="sn">序列号:</label>
<input type="text" name="sn" id="sn" value="<?php echo $sn; ?>" data-mini="true" placeholder="设备的唯一序列号">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
<label for="site">所在工地:</label>
<select id="site" name="site" data-mini="true">
<option value="0">请选择</option>
<?php
$options="";
foreach($sites as $tmp)
{
    $id = $tmp->getId();
    $name = $tmp->getName();
    //$nameeng = $tmp->getNameeng();
    $namelong = $name;

    if($siteid == $id)
    {
        $option = '<option value="'. $id . '" selected>' . $namelong . '</option>';
    }
    else
    {
        $option = '<option value="'. $id . '">' . $namelong . '</option>';
    }

    $options .= $option;
}
echo $options;
?>
</select>
</div></td>

<td><div data-role="fieldcontain">
<label for="purchasedate">购买日期:</label>
<input type="text" name="purchasedate" id="purchasedate" class="datepicker" value="<?php echo $purchasedate; ?>" data-mini="true" placeholder="点击选择日期">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
<label for="status">设备状态:</label>
<select id="status" name="status" data-mini="true">
<option value="0">请选择</option>
<?php
$options="";
foreach($statusArr as $tmp)
{
    if($tmp == $emstatus)
    {
        $option = '<option value="'. $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="'. $tmp . '">' . $tmp . '</option>';
    }
    $options .= $option;
}
echo $options;
?>
</select>
</div></td>

<td><div data-role="fieldcontain">
<label for="purchasedate">报废日期:</label>
<input type="text" name="scrapdate" id="scrapdate" class="datepicker" value="<?php echo $scrapdate; ?>" data-mini="true" placeholder="点击选择日期">
</div></td>
</tr>

<tr><td>
<div data-role="fieldcontain">
<label for="remark">其他说明:</label>
<input type="text" name="remark" id="remark" value="<?php echo $remark; ?>" data-mini="true" placeholder="">
</div>
</td>
<td></td>
</tr>
</table>
</form> <!-- dataform -->

<button type="button" id="submitbutton" name="submitbutton" onclick="submitform()" data-theme="a" data-mini="true">提交</button>
<br><br>
