<style>
</style>
<script>
$(function() {
    $('#Emachinery').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    $('#Scrapped').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
});
</script>
<?php
$workingarr=$this->workingarr;
$scraparr=$this->scraparr;

?>
<!--<h3>电动机具列表</h3>-->
<div data-role="collapsible-set" data-mini="true" data-theme="c">
<div data-role="collapsible" data-collapsed="false">
<h3>工具-使用中</h3>
<a href="/material/emachinery/add"><button data-theme="a" data-mini="true">注册一个电动机具</button></a>
<a href="#" ><button data-theme="a" data-mini="true">预览和打印</button></a>
<?
echo $this->grid("Emachinery", true)
          //->field('id', '编号')
          ->field('site', '所在工地')
          ->field('material','名称')
          ->field('purchasedate', '购买日期')
          ->field('sn', '序列号')
          ->field('status', '状态')
          ->field('remark', '说明')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Emachinery())
          ->data($this->workingarr)
          ->action(':action', '使用记录', array( 'url'=>array('action'=>'onsiterecord')))
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
<br>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>工具-已报废</h3>
<a href="#" ><button data-theme="a" data-mini="true">预览和打印</button></a>
<?
echo $this->grid("Scrapped", true)
          //->field('id', '编号')
          //->field('site', '所在工地')
          ->field('material','名称')
          ->field('sn', '序列号')
          ->field('purchasedate', '购买日期')
          ->field('scrapdate', '报废日期')
          //->field('status', '状态')
          ->field('remark', '说明')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Emachinery())
          ->data($scraparr)
          ->action(':action', '使用记录', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
<br>
</div>
</div>


