<style>
#uploaddiv { display: none; }
</style>
<script>
$(function() {
    $('#Maindata').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
} );

function showhideupload()
{
    var div = $("#uploaddiv");    
    var display = div.css("display");
    (display == "none") ? div.show() : div.hide();
}

function clearalldata()
{
    alert("清除所有数据，尚未实现，sorry");
}
</script>
<button data-mini="true" data-theme="a" onclick="showhideupload()">导入材料数据</button>
<div id="uploaddiv">
<fieldset>
<form action="/material/import/submit" method="post" enctype="multipart/form-data">
<label for="file" class="ui-input-text">上传材料数据文件(MS Excel file)：</label>
<input data-mini="true" type="file" name="file" id="file">
<input type="submit" value="上传" data-mini="true" data-theme="a">
</form>
</fieldset>
</div>
<button data-mini="true" data-theme="a" onclick="clearalldata()">清空材料数据</button>
<?
echo $this->grid("Maindata", true)
          ->field('sn','S/N')
          ->field('namechs','中文名')
          ->field('nameeng','英名字')
          ->field('wpno','WP No.')
          ->field('ppno','PP No.')
          ->field('rate','Rate')
          ->field('worktype', '主要工种')
          //->field('site', '所在工地')  
          //->field('passexp', '准证到期') 
          //->field('securityexp', '安全证到期')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          //->helper(new GridHelper_Worker())
          ->data($this->maindata)
          ->action(':action', '工地记录', array( 'url'=>array('action'=>'onsiterecord')))
          ->action(':action', '考勤记录', array( 'url'=>array('action'=>'attendancerecord')));
?>
<br><br>
