<script>
function updaterow(id)
{
    var amount = $('#amount'+id).val();
    var remark = $('#remark'+id).val();
    var supplierid = $('#select'+id).val();   
    var price = $('#price'+id).val();
    price = (price=="") ? 0 : price;

    //alert('updaterow,id='+id+",amount="+amount+",remark="+remark+",supplierid="+supplierid+",price="+price);

    $.post("/material/manage/updatedata", 
        { id: id, amount: amount, remark:remark, supplierid:supplierid, price:price  }, 
        function(data) {
            alert(data);
            console.log(data);            
    });
}

function submitmatapps()
{
    //alert("submitmatapps");
    var appid = $("#appid").val();
    $.post("/material/manage/submitmatapps", { appid: appid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function rejectmatapps()
{
    //alert("rejectmatapps");
    var appid = $("#appid").val();
    $.post("/material/manage/rejectmatapps", { appid: appid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function reviewmatapps()
{
    //alert("reviewmatapps");
    var appid = $("#appid").val();
    $.post("/material/manage/reviewmatapps", { appid: appid }, 
        function(data) {
            alert(data);
            console.log(data);            
            redirect();
    });
}

function approvematapps()
{
    //alert("approvematapps");

    var appid = $("#appid").val();
    $.post("/material/manage/approvematapps", { appid: appid }, 
        function(data) {
            alert(data);
            redirect();
    });
}

function redirect()
{
    window.location = "/material/manage/appmanage";
}
</script>
<?php
$appobj = $this->application;
$appid=$appobj->getId();
$create = $appobj->getCreatedate()->format("Y-m-d H:m:s");
$update = $appobj->getUpdatedate()->format("Y-m-d H:m:s");
$applicant = $appobj->getApplicant();
$applicantname = "";
if($applicant)
{
    $applicantname = $applicant->getName();
}
$sitename = "";
$siteobj = $appobj->getSite();
if($siteobj)
{
    $sitename = $siteobj->getName();
} 

$role = $this->role;
?>

<input type="hidden" id="appid" value="<?php echo $appid; ?>">

<table class="grid">
<tbody>
<tr>
<td><strong>申请时间:</strong></td><td><strong><?php echo $create; ?></strong></td>
<td><strong>更新时间:</strong></td><td><strong><?php echo $update; ?></strong></td>
</tr>
<tr>
<td><strong>申请工地:</strong></td>
<td><strong><?php echo $sitename; ?></strong></td>
<td><strong>申请人:</strong></td>
<td><strong><?php echo $applicantname; ?></strong></td>
</tr>
</tbody>
</table>

<?php
echo $this->grid("Matapps", true)
          ->field('longname','材料名称')
          ->field('amount','申请数量')
          ->field('remark','补充说明')
          ->field('supplier', '供应商')
          ->field('price', '单价')
          ->field('update', '更新')          
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Matapps())
          ->data($this->matapps)
          ->action(':action', '删除', array( 'url'=>array('action'=>'matdel')));

if($role == "manager")
{
    echo '<div style="display:none;">';
}
else
{
    echo '<div>';
}
?>
<input type="button" value="修改完毕提交上级审核" onclick="submitmatapps()">
<input type="button" value="取消提交重新审核" onclick="reviewmatapps()">
<input type="button" value="申请不合格退回修改" onclick="rejectmatapps()">
<?php
    echo '</div>';
?>

<?php
if($role != "manager")
{
    echo '<div style="display:none;">';
}
else
{
    echo '<div>';
}
?>
<input type="button" value="批准该申请" onclick="approvematapps()">
<input type="button" value="申请不合格退回修改" onclick="rejectmatapps()">
<?php
    echo '</div>';
?>


