<?php
$data = $this->maindata;
$mode = $this->mode; //"Create";
$mid = 0;
$namechs = "";
$nameeng = "";
$description = "";
$supplier = "";
$date = "";
$pic = "";
$usage = "";
$typeid = 0;
$defsupplierid = 0;
$supplypricearr = array();
//$units=$this->units;
//$unit="";
$suppliers = $this->suppliers;
$spareahide = "display:none;";
$_matsheet = "";

if ($mode === "Edit") {
    $mid = $data->getId();
    $namechs = $data->getName();
    $nameeng = $data->getNameeng();
    $description = $data->getDescription();
    if ($data->getSupplier()) {
        $supplier = $data->getSupplier()->getName();
    }
    $date = $data->getUpdate();
    $date = $date ? $date->format('Y/m/d') : "";
    $pic = $data->getPic();
    $usage = $data->getUsage();
    $typeobj = $data->getType();
    if ($typeobj) {
        $typeid = $typeobj->getId();
    }
    $defsupplier = $data->getSupplyprice();
    if ($defsupplier) {
        $defsupplierid = $defsupplier->getId();
    }

    $supplypricearr = $this->supplypricearr;
    $spareahide = "";

    $_matsheet = $data->getSheet();
}

$sheets = $this->sheets;
if ($mode === "Edit") {
    $options = "";
} else {
    $options = '<option value="0" >选择分类</option>';
}
foreach ($sheets as $sheet) {
    if ($_matsheet == $sheet) {
        $option = '<option value="' . $sheet . '" selected>' . $sheet . "</option>";
    } else {
        $option = '<option value="' . $sheet . '" >' . $sheet . "</option>";
    }

    $options .= $option;
}
$_sheetsels = '<select id="sheetsel" name="sheetsel" data-mini="true" data-theme="a">' . $options . "</select>";

/*
  $types = $this->types;
  $typeoptions = "";
  foreach ($types as $tmp) {
  $id = $tmp->getId();
  $main = $tmp->getMain();
  $maintypechs = $main->getTypechs();
  $maintypeeng = $main->getTypeeng();
  $typechs = $tmp->getTypechs();
  $typeeng = $tmp->getTypeeng();
  $typestr = "$maintypeeng($maintypechs)::$typeeng($typechs)";

  if ($id == $typeid) {
  $typeoptions .= '<option value="' . $id . '" selected>' . $typestr . '</option>';
  } else {
  $typeoptions .= '<option value="' . $id . '">' . $typestr . '</option>';
  }
  }
 */

$tabrows = "";
if (count($supplypricearr)) {
    foreach ($supplypricearr as $tmp) {
        $id = $tmp->getId();
        $supplier = $tmp->getSupplier();
        $suppliername = $supplier ? $supplier->getName() : "&nbsp;";
        $unit = $tmp->getUnit();
        $rate = $tmp->getRate();

        $row = "";

        if ($id == $defsupplierid) {
            $tdradio = '<td><input type="radio" name="defsupplier" class="defsupplier" id="' . $id . '" checked data-role="none"/></td>';
        } else {
            $tdradio = '<td><input type="radio" name="defsupplier" class="defsupplier" id="' . $id . '" data-role="none"/></td>';
        }

        $tdsupplier = "<td>$suppliername</td>";
        $tdunit = "<td>$unit</td>";

        $tdrate = '<td><input type="text" value="' . $rate . '" name="rate' . $id . '" id="rate' . $id . '" placeholder="0"></td>';
        $row .= "<tr>" . $tdradio . $tdsupplier . $tdunit . $tdrate . "</tr>";
        $tabrows .= $row;
    }
}

$selecthtml = "";
if (!count($suppliers)) {
    $selecthtml = "<strong>请导入材料列表或者手动添加供应商数据</strong>";
} else {
    $options = '<option value="0">选择供应商</option>';
    foreach ($suppliers as $tmp) {
        $id = $tmp->getId();
        $name = $tmp->getName();
        $options .= '<option value="' . $id . '">' . $name . '</option>';
    }
    $selecthtml.= '<select data-mini="true" id="suppliernew">' . $options . "</select>";
}

$unittd = '<td><input type="text" value="" id="unitnew" placeholder="单位，比如pair, box, etc."></td>';
$ratetd = '<td><input type="text" value="" id="ratenew" placeholder="rate, 比如5，表示5新元"></td>';
$tr = "<tr><td>$selecthtml</td> $unittd $ratetd </tr>";
$inputtab = '<table class="grid"><thead><tr><th>Supplier</th><th>Unit</th><th>Rate</th></tr></thead>'
        . '<tbody>' . $tr . "</tbody></table>";
?>
<script>
    $(function() {
        //alert("scroller");
        $('.classupdate').mobiscroll().date({
            theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
            endYear: 2050,
        });
    });

    function submitform()
    {
        //alert("submitform"); 
        var sheet = $("#sheetsel").val();
        var name = $("#name").val();
        var description = $("#description").val();
        if(sheet == "0" || name == "" || description == "")
        {
            alert("请填写分类，材料名称，和描述");
            return;
        }
        
        $("#dataform").submit();
    }

    function redirect(url) {
        window.location = url;
    }

    $('.defsupplier').change(function() {
        var id = $(this).attr("id");
        //alert("defsupplier id="+id);
        $("#defsupplierid").val(id);
    });

    $(function() {
        $('#Materials').dataTable({
            "iDisplayLength": 50,
            "bRetrieve": true,
        });
    });

    function supplypricenew()
    {
        //alert("supplypricenew");
        var supplier = $("#suppliernew").val();
        var unit = $("#unitnew").val();
        //var dodate = $("#dodatenew").val();
        var rate = $("#ratenew").val();
        //var quantity = $("#quantitynew").val();
        var material = $("#id").val();
        if (rate == "" || unit == "" || supplier == "0")
        {
            alert("请提供Supplier, Unit, Rate.");
            return false;
        }

        $.post("/material/manage/postsupplyprice", {supplier: supplier, unit: unit,
            rate: rate, /*dodate: dodate,  quantity: quantity,*/ material: material},
        function(data) {
            //console.log(data);
            alert(data);
            window.location.reload();
        })
    }

</script>
<form id="dataform" enctype="multipart/form-data" method="post" action="/material/manage/submit">
    <fieldset>
        <legend><strong>材料信息</strong></legend>
        <input type="hidden" id="mode" name="mode" value="<?php echo $mode; ?>">
        <input type="hidden" id="id" name="id" value="<?php echo $mid; ?>">
        <input type="hidden" id="defsupplierid" name="defsupplierid" value="<?php echo $defsupplierid; ?>">

        <table class="grid" id="supplypricetab">
            <tr>
                <td rowspan="5" style="width:50%">
                    <div data-role="fieldcontain">
                        <label for="file" class="ui-input-text">材料照片:</label>
                        <input type="file" name="file" id="file">
                        <img src="<?= $pic ?>" alt="" width="100%"  id="pic" name="pic">
                    </div>
                </td>
                <td>
                    <div data-role="fieldcontain">
                        <label for="sheetsel">分类:</label>
                        <?php
                        echo $_sheetsels;
                        ?>
                    </div>
                </td>
            </tr>
            <tr><td>
                    <div data-role="fieldcontain">
                        <label for="name">Name:</label>
                        <input type="text" name="name" id="name" value="<?php echo $namechs; ?>" data-mini="true">
                    </div>
                </td></tr>
            <tr><td>
                    <div data-role="fieldcontain">
                        <label for="description">Description:</label>
                        <input type="text" name="description" id="description" value="<?php echo $description; ?>" data-mini="true" placeholder="">
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div data-role="fieldcontain">
                        <label for="usage">材料用途:</label>
                        <input type="text" name="usage" id="usage" value="<?php echo $usage; ?>" data-mini="true" placeholder="材料用途，比如木类，金属类等">
                    </div>
                </td>
            </tr>
        </table>
    </fieldset>

    <fieldset id="supplypricearea" style="<?= $spareahide ?>">
        <legend><strong>价格信息</strong></legend>

        <div data-role="collapsible-set" data-mini="true" data-theme="c">
            <div data-role="collapsible" data-collapsed="false">
                <h3>已有价格信息</h3>
                <table class="grid">
                    <!--<thead><tr><th>抉择</th><th>Supplier</th><th>Unit</th><th>DO Date</th><th>Rate</th><th>Quantity</th><th>Amount</th></tr></thead>-->
                    <thead><tr><th>抉择</th><th>Supplier</th><th>Unit</th><th>Rate</th></tr></thead>
                    <tbody>
                        <?php
                        echo $tabrows;
                        ?>
                    </tbody>
                </table>
            </div>

            <div data-role="collapsible" data-collapsed="true">
                <h3>添加价格信息</h3>
                <?php echo $inputtab; ?>
                <input type="button" value="提交价格信息" onclick="supplypricenew()" data-mini="true" data-theme="a">
            </div>

        </div>

    </fieldset>
</form> <!-- dataform -->

<button type="button" id="submitbutton" name="submitbutton" onclick="submitform()" data-theme="a" data-mini="true">提交</button>
<br>

