<style>
#Materials { width:100%; }
</style>
<script>
$(function() {
    $('#Materials').dataTable();
});

function editfunc()
{
    var elmNo = 0; 
    var chkCount=0;
    var form = document.dataform;
    for (var i = 0; i < form.elements.length; i++) { 
        var element = form.elements[i];   
        if(element.type == 'checkbox' && element.id != 'toggleall' && element.checked)
        {
            chkCount++; 
            elmNo = i;    
        }    
    }
    
    if(chkCount != 1)
    {
        alert("Choose one to edit!");
        return;
    }   

    var url = "/material/manage/edit?id=" + $(form.elements[elmNo]).val();
    //alert(url);
    redirect(url);
}

function deletefunc()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/manage/delete";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function redirect(url) {
    window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function importexcel()
{
    alert("importexcel not implemented");
}


function exportexcel()
{
    alert("exportexcel not implemented");
}

</script>

<div class="ui-grid-b">
	<div class="ui-block-a"><a href="/material/manage/add"><button data-theme="a" data-mini="true">材料添加</button></a></div>
	<div class="ui-block-b"><button data-theme="a" data-mini="true" onclick="importexcel()">材料导入</button></div>
	<div class="ui-block-c"><button data-theme="a" data-mini="true" onclick="exportexcel()">材料导出</button></div>
</div><!-- /grid-b -->
<br>
<div>
<?
echo $this->grid("Materials", true)
          ->field('type', '分类')
          ->field('name','中文名称')
          ->field('nameeng', '英文名称')
          ->field('unit', '单位')
          ->field('spec', '规格')
          ->field('supplier', '优先供应商')
          ->field('price', '价格')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Material())
          ->data($this->materials)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>
<br><br>

