<style>
#Materials { width:100%; }
</style>
<script>
$(document).ready(function() {
    //alert("dataTable");
    $('#datatable').dataTable( {
        "bPaginate": false,
        "bLengthChange": false,
        "bFilter": false,
        "bSort": true,
        "bInfo": false,
        "bAutoWidth": false,
        "bRetrieve": true, /* to fix warning: "Cannot reinitialise DataTable." */
    } );
} );

function addfunc()
{
    alert("addfunc");
    var url="/material/manage/add";
    redirect(url);
}

function editfunc()
{
    var elmNo = 0; 
    var chkCount=0;
    var form = document.dataform;
    for (var i = 0; i < form.elements.length; i++) { 
        var element = form.elements[i];   
        if(element.type == 'checkbox' && element.id != 'toggleall' && element.checked)
        {
            chkCount++; 
            elmNo = i;    
        }    
    }
    
    if(chkCount != 1)
    {
        alert("Choose one to edit!");
        return;
    }   

    var url = "/material/manage/edit?id=" + $(form.elements[elmNo]).val();
    //alert(url);
    redirect(url);
}

function deletefunc()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/manage/delete";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function redirect(url) {
    window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}
</script>

<h3>材料列表</h3>
<div class="ui-grid-b">
	<div class="ui-block-a"><button onclick="addfunc()" data-theme="a">Add Tools</button></div>
	<div class="ui-block-b"><button onclick="editfunc()" data-theme="a">Edit Tools</button></div>	 
	<div class="ui-block-c"><button onclick="deletefunc()" data-theme="a">Delete Tools</button></div>  
</div><!-- /grid-a -->
<div>
<?
echo $this->grid("Materials", true)
          ->field('name','中文名称')
          ->field('nameeng', '英文名称')
          ->field('macrotype', '产品类别')
          ->field('detailtype', '详细类别')
          ->field('supplier', '供应商')
          ->field('price', '单价')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Material())
          ->data($this->materials)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
</div>

