<style>
#uploaddiv { display: none; }
</style>
<script>
$(function() {
    $('#Materials').dataTable({
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
});

$("#sheetselect").change(function() {
    var sheetname = $(this).val();
    var url = "/material/manage?sheet=" + sheetname;
    redirect(url);
});

function editfunc()
{
    var elmNo = 0; 
    var chkCount=0;
    var form = document.dataform;
    for (var i = 0; i < form.elements.length; i++) { 
        var element = form.elements[i];   
        if(element.type == 'checkbox' && element.id != 'toggleall' && element.checked)
        {
            chkCount++; 
            elmNo = i;    
        }    
    }
    
    if(chkCount != 1)
    {
        alert("Choose one to edit!");
        return;
    }   

    var url = "/material/manage/edit?id=" + $(form.elements[elmNo]).val();
    //alert(url);
    redirect(url);
}

function deletefunc()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/manage/delete";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function redirect(url) {
    window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function previewlist()
{
    var sheet = $("#sheetselect").val();
    var url = "/material/manage/previewlist?sheet=" + sheet;
    window.open (url); 
}

function showhideupload()
{
    var div = $("#uploaddiv");    
    var display = div.css("display");
    (display == "none") ? div.show() : div.hide();
}

</script>
<?php
$sheet=$this->sheet;
$sheetarr=$this->sheetarr;
$maindata=$this->maindata;
?>
<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="true">
<h3>功能列表</h3>
<div class="ui-grid-b">
	<div class="ui-block-a">
    <a href="/material/manage/add"><button data-mini="true" data-theme="a">注册一个材料</button></a>
    </div>
	<div class="ui-block-b">
    <button data-mini="true" data-theme="a" onclick="showhideupload()">导入材料数据</button>
    </div>
	<div class="ui-block-c">
    <button data-mini="true" data-theme="a" onclick="clearworkerdetails()">清空材料数据</button>
    </div>
</div><!-- /grid-b -->
    <div id="uploaddiv">
    <fieldset>
    <form action="/material/import/submit" method="post" enctype="multipart/form-data">
    上传材料列表(MS Excel file)：<input data-mini="true" type="file" name="file" id="file">
    <input type="submit" value="上传" data-mini="true" data-theme="a">
    </form>
    </fieldset>
    </div>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>列表操作</h3>
<button data-theme="a" data-mini="true" onclick="previewlist()">预览打印</button>
</div>
<hr>
<?php

$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;

echo $this->grid("Materials", true)
          //->field('type', '分类')
          ->field('nameeng', '英文名称')
          ->field('name','中文名称')
          ->field('description', '规格')
          ->field('unit', '单位')
          ->field('supplier', '优先供应商')
          ->field('price', '价格')  
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Material())
          ->data($maindata)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>

<br><br>

