<div data-role="navbar">
	<ul>
		<li><a href="/local/index/listview">List View</a></li>
		<li><a href="/local/index/mapview">Map View</a></li>
	</ul>
</div><!-- /navbar -->
<div class="wrap">
<!--<h3>Featured Items</h3>-->
<p>These featured items are our recommendations especially for you. <br/> 
Clicking list or map view on top, more amazing attractions are waiting for you...</p>
<hr>
</div>
<?php echo $this->featured; ?>

