<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<style> 
table { width: 100%; }
td { width: 50%; vertical-align:middle; }
</style>
<script type="text/javascript">
$(function () {
    $('.datepicker').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    }); 
});

function output()
{
    //alert("preview and print this bill");
    var url = "/worker/manage/output?no=" + $('#workerid').val();
    window.open (url);
}

</script>
<?php
$sn="";
$eeeno="";
$nameeng = ""; 
$namechs = "";
$wpno="";
$wpexpiry="";
$doa="";
$issuedate="";
$finno="";
$ppno="";
$dob="";
$ppexpiry="";
$rate="";
$pano="";
$sbno="";
$securityexp="";
$worktype="";
$arrivaldate="";
$medicaldate="";
$csoc="";
$medicalinsurance="";
$workingsite="";
$dormitory="";
$hometown="";
$education="";
$age="";
$marital="";
$constructionworker="";
$applyfor="";
$goodat="";
$contactno1="";
$contactno2="";
$certificate="";
$agent="";
$remarks="";
$company="";
$race="";

$pic = "";

// custom info
$customtitles=$this->customtitles;
$customtitle1=$customtitles[0];
$customtitle2=$customtitles[1];
$customtitle3=$customtitles[2];
$customtitle4=$customtitles[3];

$custom1="";
$custom2="";
$custom3="";
$custom4="";

if($this->mode == "Edit")
{
$worker=$this->worker;
$pic = $worker->getPic();
$sn=$worker->getSn();;
$eeeno=$worker->getEeeno();
$nameeng = $worker->getNameeng();
$namechs = $worker->getNamechs();
$wpno=$worker->getWpno();
$wpexpiry=$worker->getWpexpiry();
$wpexpiry=$wpexpiry? $wpexpiry->format("d-m-Y") : "";
$doa=$worker->getDoa();
$doa=$doa? $doa->format("d-m-Y") : "";
$issuedate=$worker->getIssuedate();
$issuedate=$issuedate? $issuedate->format("d-m-Y") : "";
$finno=$worker->getFinno();
$ppno=$worker->getPpno();
$dob=$worker->getDob();
$dob=$dob? $dob->format("d-m-Y") : "";
$ppexpiry=$worker->getPpexpiry();
$ppexpiry=$ppexpiry? $ppexpiry->format("d-M-Y") : "";
$rate=$worker->getRate();
$pano=$worker->getPano();
$sbno=$worker->getSbno();
$securityexp=$worker->getSecurityexp();
$securityexp=$securityexp? $securityexp->format("d-M-Y") : "";
$worktype=$worker->getWorktype();
$arrivaldate=$worker->getArrivaldate();
$arrivaldate=$arrivaldate? $arrivaldate->format("d-M-Y") : "";
$medicaldate=$worker->getMedicaldate();
$medicaldate=$medicaldate? $medicaldate->format("d-M-Y") : "";
$csoc=$worker->getCsoc();
$medicalinsurance=$worker->getMedicalinsurance();
$workingsite=$worker->getWorkingsite();
$dormitory=$worker->getDormitory();
$hometown = $worker->getHometown();
$education=$worker->getEducation();
$age = $worker->getAge();
$marital=$worker->getMarital();
$constructionworker=$worker->getConstructionworker();
$applyfor=$worker->getApplyfor();
$goodat=$worker->getGoodat();
$contactno1=$worker->getContactno1();
$contactno2=$worker->getContactno2();
$certificate=$worker->getCertificate();
$agent=$worker->getAgent();
$remarks=$worker->getRemarks();
$company=$worker->getCompany();
$race=$worker->getRace();

}


/*
$hometown = "";
$age = 18;
$birth = "";
$fin = "";
$passexp = "";
$passport = "";
$passportexp = "";
$marital = "";
$address = "";
$gender="";

$worktype = "";
$worklevel = "";
$skill1 = "";
$skill2 = "";
$securityexp = "";
$drvlic = "";
$education = "";
$pastwork = "";

//$companylabel = "";
$hwage = "";
$sitename = "";
$siteid=0;
$srvyears = "";
$yrsinsing = "";    

$homeaddr = "";
$member1 = "";
$member2 = "";
$member3 = "";
$contact1 = "";
$contact2 = "";
$contact3 = "";

$arrivesing="";
$leavesing="";

$companyid=0;

$worktypes=$this->worktypes;

// custom info
$customtitles=$this->customtitles;
$customtitle1=$customtitles[0];
$customtitle2=$customtitles[1];
$customtitle3=$customtitles[2];
$customtitle4=$customtitles[3];

$custom1="";
$custom2="";
$custom3="";
$custom4="";

if($this->mode == "Edit")
{
$worker=$this->worker;
$pic = $worker->getPic();
$nameeng = $worker->getNameeng();
$namechs = $worker->getNamechs();
$hometown = $worker->getHometown();
$age = $worker->getAge();
if($worker->getBirth())
{
    $birth = $worker->getBirth()->format("Y/m/d");
}
$fin = $worker->getFin();
if($worker->getPassexp())
{
    $passexp = $worker->getPassexp()->format("Y/m/d");
}
$passport = $worker->getPassport();
if($worker->getPassportexp())
{
    $passportexp = $worker->getPassportexp()->format("Y/m/d");
}
$marital = $worker->getMarital();
$address = $worker->getAddress();
$gender=$worker->getGender();

$arrivedate = $worker->getArrivesing();
$arrivesing = $arrivedate ? $arrivedate->format("Y/m/d") : "";
$leavedate = $worker->getLeavesing();
$leavesing = $leavedate ? $leavedate->format("Y/m/d"): "";

$skill=$this->skill;
    if($skill)
    {
    $worktype = $skill->getWorktype();
    $worklevel = $skill->getWorklevel();
    $skill1 = $skill->getSkill1();
    $skill2 = $skill->getSkill2();
    if($skill->getSecurityexp())
    {        
        $securityexp = $skill->getSecurityexp()->format("Y/m/d");
    }
    $drvlic = $skill->getDrvlic();
    $education = $skill->getEducation();
    $pastwork = $skill->getPastwork();
    }

$companyinfo=$this->companyinfo;
if($companyinfo)
{
    //$companylabel = $companyinfo->getCompanylabel();
    $hwage = $companyinfo->getHwage();

    $siteobj=$companyinfo->getSite();
    if($siteobj)
    {
        $sitename = $siteobj->getName();
        $siteid = $siteobj->getId();
    }
    $srvyears = $companyinfo->getSrvyears();
    $yrsinsing = $companyinfo->getYrsinsing();

    $companyobj = $companyinfo->getCompany();
    if($companyobj)
    {
        $companyid = $companyobj->getId();
    }
}

$family=$this->family;
if($family)
{
    $homeaddr = $family->getHomeaddr();
    $member1 = $family->getMember1();
    $member2 = $family->getMember2();
    $member3 = $family->getMember3();
    $contact1 = $family->getContact1();
    $contact2 = $family->getContact2();
    $contact3 = $family->getContact3();
}

$custominfos=$this->custominfos;
if($custominfos)
{
    $custom1 = $custominfos->getCustom1();
    $custom2 = $custominfos->getCustom2();
    $custom3 = $custominfos->getCustom3();
    $custom4 = $custominfos->getCustom4();
}

}
*/

$html="";
if($this->mode == "Create")
{
    $html .= '<h3>创建工人信息</h3>';    
}
else
{
    $html .= '<h3>编辑工人信息</h3>';    
    $html .= '<button data-mini="true" onclick="output()" data-mini="true" data-theme="a">预览和打印</button>';
}
echo $html;
?>

<form action="/worker/manage/submit" method="post" enctype="multipart/form-data">
<input data-mini="true" type="hidden" id="mode" name="mode" value="<?php echo $this->mode; ?>">
<input data-mini="true" type="hidden" id="workerid" name="workerid" value="<?php echo $this->workerid; ?>">

<table>
<tr>
<td><div data-role="fieldcontain">
    <label for="pic" class="ui-input-text"></label>
    <img src="<?php echo $pic; ?>" alt="无照片显示" width="40%"  id="pic" name="pic">
</div></td>
<td><div data-role="fieldcontain">
    <label for="file" class="ui-input-text">更新照片：</label>
    <input data-mini="true" type="file" name="file" id="file">
</div></td>
</tr>
</table>

<div data-role="fieldcontain">
    <label for="sn">S/N:</label>
    <input data-mini="true" type="text" name="sn" id="sn" value="<?php echo $sn; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="eeeno">E'ee No.:</label>
    <input data-mini="true" type="text" name="eeeno" id="eeeno" value="<?php echo $nameeng; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="namechs">Chinese Name:</label>
    <input data-mini="true" type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="nameeng">English Name:</label>
    <input data-mini="true" type="text" name="nameeng" id="nameeng" value="<?php echo $nameeng; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="wpno">WP No.:</label>
    <input data-mini="true" type="text" name="wpno" id="wpno" value="<?php echo $wpno; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="wpexpiry">WP Expiry:</label>
    <input data-mini="true" type="text" name="wpexpiry" id="wpexpiry" value="<?php echo $wpexpiry; ?>" class="datepicker"/>
</div>
<div data-role="fieldcontain">
    <label for="doa">D.O.A:</label>
    <input data-mini="true" type="text" name="doa" id="doa" value="<?php echo $doa; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="issuedate">Date of Issue:</label>
    <input data-mini="true" type="text" name="issuedate" id="issuedate" value="<?php echo $issuedate; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="finno">Fin No.:</label>
    <input data-mini="true" type="text" name="finno" id="finno" value="<?php echo $finno; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="ppno">PP No.:</label>
    <input data-mini="true" type="text" name="ppno" id="ppno" value="<?php echo $ppno; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="dob">D.O.B:</label>
    <input data-mini="true" type="text" name="dob" id="dob" value="<?php echo $dob; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="ppexpiry">PP Expiry:</label>
    <input data-mini="true" type="text" name="ppexpiry" id="ppexpiry" value="<?php echo $ppexpiry; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="rate">RATE:</label>
    <input data-mini="true" type="text" name="rate" id="rate" value="<?php echo $rate; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="pano">PA Reference No.:</label>
    <input data-mini="true" type="text" name="pano" id="pano" value="<?php echo $pano; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="sbno">Security Bond No.:</label>
    <input data-mini="true" type="text" name="sbno" id="sbno" value="<?php echo $sbno; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="securityexp">Security Exprity Date:</label>
    <input data-mini="true" type="text" name="securityexp" id="securityexp" value="<?php echo $securityexp; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="worktype">Work Type:</label>
    <input data-mini="true" type="text" name="worktype" id="worktype" value="<?php echo $worktype; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="arrivaldate">Arrival Date:</label>
    <input data-mini="true" type="text" name="arrivaldate" id="arrivaldate" value="<?php echo $arrivaldate; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="medicaldate">Medical Date:</label>
    <input data-mini="true" type="text" name="medicaldate" id="medicaldate" value="<?php echo $medicaldate; ?>" class="datepicker" />
</div>
<div data-role="fieldcontain">
    <label for="csoc">C.S.O.C:</label>
    <input data-mini="true" type="text" name="csoc" id="csoc" value="<?php echo $csoc; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="medicalinsurance">Medical Insurance:</label>
    <input data-mini="true" type="text" name="medicalinsurance" id="medicalinsurance" value="<?php echo $medicalinsurance; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="workingsite">WORKING SITE:</label>
    <input data-mini="true" type="text" name="workingsite" id="workingsite" value="<?php echo $workingsite; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="dormitory">Dormitory:</label>
    <input data-mini="true" type="text" name="dormitory" id="dormitory" value="<?php echo $dormitory; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="hometown">区域:</label>
    <input data-mini="true" type="text" name="hometown" id="hometown" value="<?php echo $hometown; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="education">教育程度:</label>
    <input data-mini="true" type="text" name="education" id="education" value="<?php echo $education; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="age">年龄:</label>
    <input data-mini="true" type="text" name="age" id="age" value="<?php echo $age; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="marital">婚姻状况:</label>
    <input data-mini="true" type="text" name="marital" id="marital" value="<?php echo $marital; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="constructionworker">建筑工:</label>
    <input data-mini="true" type="text" name="constructionworker" id="constructionworker" value="<?php echo $constructionworker; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="applyfor">Apply For:</label>
    <input data-mini="true" type="text" name="applyfor" id="applyfor" value="<?php echo $applyfor; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="goodat">Good At:</label>
    <input data-mini="true" type="text" name="goodat" id="goodat" value="<?php echo $goodat; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="contactno1">Contact No.1:</label>
    <input data-mini="true" type="text" name="contactno1" id="contactno1" value="<?php echo $contactno1; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="contactno2">Contact No.2:</label>
    <input data-mini="true" type="text" name="contactno2" id="contactno2" value="<?php echo $contactno2; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="certificate">Certificate:</label>
    <input data-mini="true" type="text" name="certificate" id="certificate" value="<?php echo $certificate; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="remarks">Remarks(Agent):</label>
    <input data-mini="true" type="text" name="remarks" id="remarks" value="<?php echo $remarks; ?>" />
</div>

<fieldset>
<legend>自定义信息</legend>
<div data-role="fieldcontain">
    <label for="custom1"><?php echo $customtitle1; ?>:</label>
    <input data-mini="true" type="text" name="custom1" id="custom1" value="<?php echo $custom1; ?>"  />
</div>
<div data-role="fieldcontain">
    <label for="custom2"><?php echo $customtitle2; ?>:</label>
    <input data-mini="true" type="text" name="custom2" id="custom2" value="<?php echo $custom2; ?>"  />
</div>
<div data-role="fieldcontain">
    <label for="custom3"><?php echo $customtitle3; ?>:</label>
    <input data-mini="true" type="text" name="custom3" id="custom3" value="<?php echo $custom3; ?>"  />
</div>
<div data-role="fieldcontain">
    <label for="custom4"><?php echo $customtitle4; ?>:</label>
    <input data-mini="true" type="text" name="custom4" id="custom4" value="<?php echo $custom4; ?>"  />
</div>
</fieldset>

<input data-mini="true" data-theme="a" type="submit" name="submit" value="提交">
</form>
<br>
<br>

