<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>

<h3>Add/Edit Worker</h3>
<form id="dataform" name="dataform">
<input type="hidden" id="data" name="data">
<input type="hidden" name="mode" id="mode" value="<?php echo $this->mode; ?>">
<input type="hidden" name="id" id="id" value="<?php echo $this->id; ?>">
<div data-role="fieldcontain">
<label for="name">Name:</label>
<input type="text" name="name" id="name" value="<?php echo $this->name; ?>" />
</div>
<div data-role="fieldcontain">
<label for="date">Date:</label>
<input type="text" name="date" id="date" value="<?php echo $this->date; ?>" />
</div>
<div data-role="fieldcontain">
<label for="price">Price:</label>
<input type="text" name="price" id="price" value="<?php echo $this->price; ?>" />
</div>
<div data-role="fieldcontain">
    <label for="description">Content:</label>
    <textarea id="description" name="description" rows="15" cols="60" style="width: 100%" data-role="none">
    <?php echo $this->description; ?>  
    </textarea>
</div>
<button type="button" id="submitbutton" name="submitbutton" onclick="submitform()">Submit</button>
</form>
