<link href="/common/mobiscroll.2.5.0.production/css/mobiscroll.custom-2.5.0.min.css" rel="stylesheet" type="text/css" />
<script src="/common/mobiscroll.2.5.0.production/js/mobiscroll.custom-2.5.0.min.js" type="text/javascript"></script>
<style> 
.infoarea
{
border:2px solid #a1a1a1;
/*padding:10px 40px; */
padding:10px;
background:#dddddd;
border-radius:10px;
-moz-border-radius:10px; /* Firefox 3.6 and earlier */
}

table { width: 100%; }
td { width: 50%; vertical-align:middle; }
</style>
<script type="text/javascript">
$(function () {
    //alert("scroller");
    $('#birth').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

    $('#passexp').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

    $('#passportexp').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

    $('#securityexp').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    });  

    $('#arrivesing').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    }); 

    $('#leavesing').mobiscroll().date({
        theme: 'android-ics', display: 'bottom', mode: 'scroller', dateOrder: 'yy mm dd', dateFormat: 'yy/mm/dd',
        endYear: 2050,
    }); 

});

function output()
{
    //alert("preview and print this bill");
    var url = "/worker/manage/output?no=" + $('#workerid').val();
    window.open (url);
}

</script>

<?php

$pic = "";
$nameeng = ""; 
$namechs = "";
$hometown = "";
$age = 18;
$birth = "";
$fin = "";
$passexp = "";
$passport = "";
$passportexp = "";
$marital = "";
$address = "";

$worktype = "";
$worklevel = "";
$skill1 = "";
$skill2 = "";
$securityexp = "";
$drvlic = "";
$education = "";
$pastwork = "";

$companylabel = "";
$hwage = "";
$sitename = "";
$srvyears = "";
$yrsinsing = "";    

$homeaddr = "";
$member1 = "";
$member2 = "";
$member3 = "";
$contact1 = "";
$contact2 = "";
$contact3 = "";

$arrivesing="";
$leavesing="";

if($this->mode == "Edit")
{
$worker=$this->worker;
    $pic = $worker->getPic();
    $nameeng = $worker->getNameeng();
    $namechs = $worker->getNamechs();
    $hometown = $worker->getHometown();
    $age = $worker->getAge();
    if($worker->getBirth())
    {
        $birth = $worker->getBirth()->format("Y/m/d");
    }
    $fin = $worker->getFin();
    if($worker->getPassexp())
    {
        $passexp = $worker->getPassexp()->format("Y/m/d");
    }
    $passport = $worker->getPassport();
    if($worker->getPassportexp())
    {
        $passportexp = $worker->getPassportexp()->format("Y/m/d");
    }
    $marital = $worker->getMarital();
    $address = $worker->getAddress();

$arrivesing = $worker->getArrivesing()->format("Y/m/d");
$leavesing = $worker->getLeavesing()->format("Y/m/d");

$skill=$this->skill;
    if($skill)
    {
    $worktype = $skill->getWorktype();
    $worklevel = $skill->getWorklevel();
    $skill1 = $skill->getSkill1();
    $skill2 = $skill->getSkill2();
    if($skill->getSecurityexp())
    {        
        $securityexp = $skill->getSecurityexp()->format("Y/m/d");
    }
    $drvlic = $skill->getDrvlic();
    $education = $skill->getEducation();
    $pastwork = $skill->getPastwork();
    }

$companyinfo=$this->companyinfo;
if($companyinfo)
{
    $companylabel = $companyinfo->getCompanylabel();
    $hwage = $companyinfo->getHwage();
    $sitename = $companyinfo->getSite()->getName();
    $srvyears = $companyinfo->getSrvyears();
    $yrsinsing = $companyinfo->getYrsinsing();
}

$family=$this->family;
if($family)
{
    $homeaddr = $family->getHomeaddr();
    $member1 = $family->getMember1();
    $member2 = $family->getMember2();
    $member3 = $family->getMember3();
    $contact1 = $family->getContact1();
    $contact2 = $family->getContact2();
    $contact3 = $family->getContact3();
}

}
?>

<!--<fieldset class="ui-grid-b">-->
<div class="ui-grid-b">
<?php
if($this->mode == "Create")
{
    echo '<div class="ui-block-a"><h3>创建工人信息</h3></div>';
    echo '<div class="ui-block-b"></div>';
    echo '<div class="ui-block-c"><button data-mini="true">放弃创建</button></div>';
}
else
{
    echo '<div class="ui-block-a"><h3>编辑工人信息</h3></div>';
    echo '<div class="ui-block-b"><button data-mini="true" onclick="output()">预览并打印</button></div>';
    echo '<div class="ui-block-c"><button data-mini="true">删除工人记录</button></div>';
}
?>
</div><!-- /grid-a -->
<!--</fieldset>-->

<form action="/worker/manage/submit" method="post" enctype="multipart/form-data">
<input data-mini="true" type="hidden" id="mode" name="mode" value="<?php echo $this->mode; ?>">
<input data-mini="true" type="hidden" id="workerid" name="workerid" value="<?php echo $this->workerid; ?>">

<fieldset>
<legend>个人信息栏:</legend>
<!--<div class="infoarea">-->
<!--<strong>个人信息栏:</strong><br>-->
<table>
<tr>
<td><div data-role="fieldcontain">
    <!--<label for="pic" class="ui-input data-mini="true"-text">工人照片：</label>-->
    <label for="pic" class="ui-input-text"></label>
    <img src="<?php echo $pic; ?>" alt="无照片显示" width="40%"  id="pic" name="pic">
</div></td>
<td><div data-role="fieldcontain">
    <label for="file" class="ui-input-text">更新照片：</label>
    <input data-mini="true" type="file" name="file" id="file">
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="nameeng">姓名:</label>
    <input data-mini="true" type="text" name="nameeng" id="nameeng" value="<?php echo $nameeng; ?>" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="namechs">中文姓名:</label>
    <input data-mini="true" type="text" name="namechs" id="namechs" value="<?php echo $namechs; ?>" />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="gender">性别:</label>
    <select data-mini="true" name="gender" id="gender">
       <option value="male">男</option>
       <option value="female">女</option>
    </select>  
</div></td>
<td><div data-role="fieldcontain">
    <label for="hometown">籍贯:</label>
    <input data-mini="true" type="text" name="hometown" id="hometown" value="<?php echo $hometown; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="age">年龄:</label>
    <input data-mini="true" type="range" name="age" id="age" value="<?php echo $age; ?>" min="18" max="70" data-highlight="true"  />  
</div></td>
<td><div data-role="fieldcontain">
    <label for="birth">出生日期:</label>
    <input data-mini="true" type="text" name="birth" id="birth" value="<?php echo $birth; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="fin">准证号码:</label>
    <input data-mini="true" type="text" name="fin" id="fin" value="<?php echo $fin; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="passexp">准证期限:</label>
    <input data-mini="true" type="text" name="passexp" id="passexp" value="<?php echo $passexp; ?>" />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="passport">护照号码:</label>
    <input data-mini="true" type="text" name="passport" id="passport" value="<?php echo $passport; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="passportexp">护照期限:</label>
    <input data-mini="true" type="text" name="passportexp" id="passportexp" value="<?php echo $passportexp; ?>" />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="marital">婚姻状况:</label>    
    <select data-mini="true" name="marital" id="marital">
<?php
$options=array("single"=>"单身", "married"=>"已婚",);
foreach($options as $key=>$value)
{
    if($marital == $key)
    {
        echo '<option value="'. $key . '" selected>' . $value . "</option>";
    }    
    else
    {
        echo '<option value="'. $key . '" >' . $value . "</option>";
    }
}
?>
    </select>        
</div></td>
<td><div data-role="fieldcontain">
    <label for="address">地址:</label>
    <input data-mini="true" type="text" name="address" id="address" value="<?php echo $address; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="birth">到新日期:</label>
    <input data-mini="true" type="text" name="arrivesing" id="arrivesing" value="<?php echo $arrivesing; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="birth">离新日期:</label>
    <input data-mini="true" type="text" name="leavesing" id="leavesing" value="<?php echo $leavesing; ?>"  />
</div></td>
</tr>

</table>
<!--</div>-->
</fieldset>
<br>

<fieldset>
<legend>技能信息栏:</legend>
<!--<div class="infoarea">
<strong>技能信息栏:</strong><br>-->
<table>
<tr>
<td><div data-role="fieldcontain">
    <label for="worktype">工种:</label>
    <input data-mini="true" type="text" name="worktype" id="worktype" value="<?php echo $worktype; ?>" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="worklevel">等级:</label>
    <select data-mini="true" name="worklevel" id="worklevel">
<?php
$options=array("normal"=>"普通","good"=>"好","excellent"=>"很好");
foreach($options as $key=>$value)
{
    if($worklevel == $key)
    {
        echo '<option value="' . $key . '" selected>' . $value . "</option>";
    }
    else
    {
        echo '<option value="' . $key . '" >' . $value . "</option>";
    }
} 
?>
    </select> 
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="skill1">技能1:</label>
    <input data-mini="true" type="text" name="skill1" id="skill1" value="<?php echo $skill1; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="skill2">技能2:</label>
    <input data-mini="true" type="text" name="skill2" id="skill2" value="<?php echo $skill2; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="securityexp">安全证期限:</label>
    <input data-mini="true" type="text" name="securityexp" id="securityexp" value="<?php echo $securityexp; ?>" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="drvlic">驾照种类:</label>
    <input data-mini="true" type="text" name="drvlic" id="drvlic" value="<?php echo $drvlic; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="education">教育程度:</label>
    <input data-mini="true" type="text" name="education" id="education" value="<?php echo $education; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="pastwork">国内从事职业:</label>
    <input data-mini="true" type="text" name="pastwork" id="pastwork" value="<?php echo $pastwork; ?>"  />
</div></td>
</tr>

</table>
<!--</div>-->
</fieldset>
<br>

<fieldset>
<legend>工作信息栏:</legend>
<!--<div class="infoarea">
<strong>工作信息栏:</strong><br>-->
<table>
<tr>
<td><div data-role="fieldcontain">
    <label for="companylabel">公司编号:</label>
    <input data-mini="true" type="text" name="companylabel" id="companylabel" value="<?php echo $companylabel; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="hwage">小时单价:</label>
    <input data-mini="true" type="text" name="hwage" id="hwage" value="<?php echo $hwage; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="site">所在工地:</label>
    <!--<input data-mini="true" type="text" name="site" id="site" value=""  /> -->
    <select data-mini="true" name="site" id="site">
<?php

foreach($this->sites as $tmp)
{
    $name = $tmp->getName();
    if($sitename == $name)
    {
        echo '<option value="' . $name .'" select data-mini="true"ed>'. $name .'</option>';
    }
    else
    {
        echo '<option value="' . $name .'" >'. $name .'</option>';
    }
}
?>
    </select data-mini="true">
</div></td>
<td><div data-role="fieldcontain">
    <label for="srvyears">服务年限:</label>
    <!--<input data-mini="true" type="text" name="srvyears" id="srvyears" value=""  /> -->
 	<input data-mini="true" type="range" name="srvyears" id="srvyears" value="<?php echo $srvyears; ?>" min="0" max="30" data-highlight="true"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="yrsinsing">在新年限:</label>
    <!-- <input data-mini="true" type="text" name="yrsinsing" id="yrsinsing" value=""  /> -->
    <input data-mini="true" type="range" name="yrsinsing" id="yrsinsing" value="<?php echo $yrsinsing; ?>" min="0" max="50" data-highlight="true"  />
</div></td>
</tr>

</table>
<!--</div>-->
</fieldset>
<br>

<fieldset>
<legend>家庭信息栏:</legend>
<!--<div class="infoarea">
<strong>家庭信息栏:</strong><br>-->
<table>
<tr>
<td><div data-role="fieldcontain">
    <label for="homeaddr">国内家庭地址:</label>
    <input data-mini="true" type="text" name="homeaddr" id="homeaddr" value="<?php echo $homeaddr; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="member1">家庭成员1:</label>
    <input data-mini="true" type="text" name="member1" id="member1" value="<?php echo $member1; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="contact1">联系电话1:</label>
    <input data-mini="true" type="text" name="contact1" id="contact1" value="<?php echo $contact1; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="member2">家庭成员2:</label>
    <input data-mini="true" type="text" name="member2" id="member2" value="<?php echo $member2; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="contact2">联系电话2:</label>
    <input data-mini="true" type="text" name="contact2" id="contact2" value="<?php echo $contact2; ?>"  />
</div></td>
</tr>

<tr>
<td><div data-role="fieldcontain">
    <label for="member3">家庭成员3:</label>
    <input data-mini="true" type="text" name="member3" id="member3" value="<?php echo $member3; ?>"  />
</div></td>
<td><div data-role="fieldcontain">
    <label for="contact3">联系电话3:</label>
    <input data-mini="true" type="text" name="contact3" id="contact3" value="<?php echo $contact3; ?>"  />
</div></td>
</tr>

</table>
<!--</div>-->
</fieldset>

<input data-mini="true" type="submit" name="submit" value="提交">
</form>

