<style>
#infoswitches { display: none; }
</style>
<script>
$(document).ready(function() {
    $('#datatable').dataTable();
} );

function fnShowHide( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#datatable').dataTable();
	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, bVis ? false : true );
}

function addfunc()
{
    //alert("addfunc");
    var url="/worker/manage/add";
    redirect(url);
}

function editfunc()
{
    var elmNo = 0; 
    var chkCount=0;
    var form = document.dataform;
    for (var i = 0; i < form.elements.length; i++) { 
        var element = form.elements[i];   
        if(element.type == 'checkbox' && element.id != 'toggleall' && element.checked)
        {
            chkCount++; 
            elmNo = i;    
        }    
    }
    
    if(chkCount != 1)
    {
        alert("Choose one to edit!");
        return;
    }   

    var url = "/material/manage/edit?id=" + $(form.elements[elmNo]).val();
    //alert(url);
    redirect(url);
}

function deletefunc()
{
    var r=confirm("Confirm to delete?");
    if (r==false) { return false; }          

    var formname = "dataform";

    var action = "/material/manage/delete";     
    var method = "post";

    var frm = $('#dataform');    
    var toServer = {};
    $('#datatable tbody tr td input').each(function(key, value) {
        toServer[$(this).val()] = $(this).is(':checked');
    });
    
    frm.submit(function () {
        $.ajax({
            type: method,
            url: action,
            data: toServer,
            success: function (data) {
                //alert(data);
                window.location.reload();
            }
        });

        return false;
    });
    
    frm.submit();
}

function redirect(url) {
    window.location = url;
}

function checkall()
{
    //alert("checkall");
    var checked = false;
    var form = document.dataform;
    
    for (var i = 0; i < form.elements.length; i++) {
        if(form.elements[i].id == 'toggleall')
        {
            checked = form.elements[i].checked;
            break;    
        }    
    }

    for (var i = 0; i < form.elements.length; i++) {    
        if(form.elements[i].type == 'checkbox'){
                form.elements[i].checked = checked;
            }    
    }
}

function infoswitches()
{
    var sws = $("#infoswitches");    

    var display = sws.css("display");
    //alert(display);

    if(display == "none")
    {
        $("#infoswitches").show();
    }
    else
    {
        $("#infoswitches").hide();
    }
}

</script>

<a href="/worker/manage/add"><button data-theme="a" data-mini="true"><?php echo $this->translate("Add Worker");?></button></a>
<button data-theme="a" data-mini="true" onclick="infoswitches()">信息列表开关</button>
<div id="infoswitches">
<!--
<a href="javascript:void(0);" onclick="fnShowHide(0);">开关序号栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(1);">开关公司栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(2);">开关工地栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(3);">开关姓名栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(4);">开关中文名栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(5);">开关准证栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(6);">开关工种栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(7);">开关等级栏</a>
<a href="javascript:void(0);" onclick="fnShowHide(8);">开关小时工资栏</a>
-->
<div class="ui-grid-d">
<?php
// http://stackoverflow.com/questions/8375625/jquery-select-table-column
$switches=array(
"namechs"=>"中文名","nameeng"=>"英文名","fin"=>"准证","passexp"=>"准证到期","passport"=>"护照",
"passportexp"=>"护照到期","age"=>"年龄","arrivesing"=>"到新日期","leavesing"=>"离新日期","site"=>"所在工地",
"company"=>"所在公司","hrwage"=>"时薪","srvyears"=>"服务年限","yrsinsing"=>"在新年限","worktype"=>"工种",
"worklevel"=>"水平","education"=>"教育程度","pastwork"=>"往日职业","skill1"=>"主要技能一","skill2"=>"主要技能二",
"drvlic"=>"驾照",);

$count=0;
$grids="";
foreach($switches as $key => $value)
{
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    //$checkbox = '<input type="checkbox" name="checkbox-2a" id="checkbox-2a" class="custom" value="' . $key . '" >' . $value;
    //$checkbox = '<input type="checkbox" name="' . $key . '" id="' . $key . '" class="custom" />';
    //$checkbox .= '<label for="' . $key  . '">' . $value . '</label>';
    $checkbox = '<label><input type="checkbox" name="' . $key . '" />' . $value . '</label>';
    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>";
    $grids .= $grid;  
}
echo $grids;
?>
</div><!-- /grid-d -->



</div>

<!--
<div data-role="fieldcontain" style="float:left">
<fieldset data-role="controlgroup" data-mini="true">
	<label for="checkbox-1a">Cheetos</label>
	<input type="checkbox" name="checkbox-1a" id="checkbox-1a" class="custom" />

	<input type="checkbox" name="checkbox-2a" id="checkbox-2a" class="custom" />
	<label for="checkbox-2a">Doritos</label>

	<input type="checkbox" name="checkbox-3a" id="checkbox-3a" class="custom" />
	<label for="checkbox-3a">Fritos</label>

	<input type="checkbox" name="checkbox-4a" id="checkbox-4a" class="custom" />
	<label for="checkbox-4a">Sun Chips</label>
</fieldset>
</div>
-->


<?
$wdtab=$this->grid("Workersdata", true);
$wdtab=$wdtab->field('id','编号');
$wdtab=$wdtab->field('nameeng','英名字');
//$wdtab=$wdtab->field('company', '所在公司');
$wdtab=$wdtab->data($this->workersdata);
echo $wdtab;
?>
<br>


<?
echo $this->grid("Workersdata", true)
          ->field('id','编号')
          ->field('nameeng','英名字')
          ->field('namechs','中文名')
          ->field('company', '所在公司')
          //->field('site', '所在工地')  
          ->field('passexp', '准证到期') 
          ->field('securityexp', '安全证到期')  
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->paginatorEnabled(false)
          ->setSorting(false)  
          ->helper(new GridHelper_Worker())
          ->data($this->workersdata)
          ->action(':action', '编辑', array( 'url'=>array('action'=>'edit')))
          ->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>
<br>

<table id="datatable">
<thead><tr>
<th>序号</th>
<th>服务公司</th>
<th>所在工地</th>
<th>姓名</th>
<th>中文名</th>
<th>准证号码</th>
<th>工种</th>
<th>等级</th>
<th>小时工资</th>
</tr></thead>
<tbody> 
<?php
$rows="";
foreach($this->result as $tmp)
{
    // worker
    $id = $tmp[0]['id'];
    $namechs = $tmp[0]['namechs'];
    $nameeng = $tmp[0]['nameeng'];;
    $fin = $tmp[0]['fin'];;

    // skills
    $worktype = $tmp["worktype"];
    $level = $tmp["worklevel"];
    // company
    $company = $tmp["companyname"];
    $site = $tmp["sitename"];
    $hrwage = $tmp["hwage"];

    $row = "<tr>";
    $row .= '<td><a data-role="button" data-mini="true" href="/worker/manage/edit?id=' . $id . '">' . $id . '</a></td>' ;
    $row .= "<td>$company</td>" ;
    $row .= "<td>$site</td>" ;
    $row .= "<td>$nameeng</td>" ;
    $row .= "<td>$namechs</td>" ;
    $row .= "<td>$fin</td>" ;
    $row .= "<td>$worktype</td>" ;
    $row .= "<td>$level</td>" ;
    $row .= "<td>$hrwage</td>" ;
    $row .= "</tr>";
    
    $rows .= $row;
}
echo $rows;
?>
</tbody> 
</table>
<br><br>
