<style>
#infoswitches { display: none; }
#datatable { text-align:center; display:none; }
#Workersdata { width:100%; }
#uploaddiv { display: none; }
/*#featuresdiv { display: none; }*/
</style>
<script>
$(document).ready(function() {
/*
    $('#datatable').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
*/
    $('#Workersdata').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });

    fnHideColumns();
    resizetable();
} );

function resizetable()
{
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
    $('#Workersdata').width('100%');
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
}

function fnHideColumns()
{
    var oncount = Number($('#oncount').val());
    var offcount = Number($('#offcount').val()) + oncount;
    //alert(oncount + "," + offcount);

    for(i=oncount; i<offcount; i++)
    {   //alert(i);
        fnHideColumn(i);
    }
}

function fnHideColumn( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, false );
}

function fnShowHide( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();
	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, bVis ? false : true );
}

function infoswitches()
{
    var sws = $("#infoswitches");    

    var display = sws.css("display");
    //alert(display);

    if(display == "none")
    {
        $("#infoswitches").show();
    }
    else
    {
        $("#infoswitches").hide();
    }
}

function redirect(url) {
    window.location = url;
}

function showhideupload()
{
    var div = $("#uploaddiv");    
    var display = div.css("display");
    (display == "none") ? div.show() : div.hide();
}

function clearworkerdetails()
{
    alert("清除所有工人数据，尚未实现，hold on...");
}
</script>

<?php
$sheet=$this->sheet;
$sheetarr=$this->sheetarr;
$maindata=$this->maindata;

?>

<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="true">
<h3>功能列表</h3>
<div class="ui-grid-b">
	<div class="ui-block-a">
    <a href="/worker/manage/add"><button data-mini="true" data-theme="a">注册一个工人</button></a>
    </div>
	<div class="ui-block-b">
    <button data-mini="true" data-theme="a" onclick="showhideupload()">导入工人数据</button>
    </div>
	<div class="ui-block-c">
    <button data-mini="true" data-theme="a" onclick="clearworkerdetails()">清空工人数据</button>
    </div>
</div><!-- /grid-b -->
    <div id="uploaddiv">
    <fieldset>
    <form action="/worker/import/submit" method="post" enctype="multipart/form-data">
    上传工人列表(MS Excel file)：
    <!--<label for="file" class="ui-input-text">上传工人列表(MS Excel file)：</label>-->
    <input data-mini="true" type="file" name="file" id="file">
    <input type="submit" value="上传" data-mini="true" data-theme="a">
    </form>
    </fieldset>
    </div>
</div>

<div data-role="collapsible" data-collapsed="true">
<h3>列表操作</h3>
<button data-theme="a" data-mini="true" onclick="infoswitches()">数据筛选</button>
<div id="infoswitches">
<div class="ui-grid-d">
<?php
// ob: http://stackoverflow.com/questions/8375625/jquery-select-table-column

$onswitches=array(
"id"=>"编号","namechs"=>"中文名","nameeng"=>"英文名","company"=>"所在公司", "worktype"=>"工种", 
"passexp"=>"准证到期",'securityexp'=>'安全证到期',);

$offswitches=array(
"fin"=>"准证","passport"=>"护照","passportexp"=>"护照到期","age"=>"年龄","arrivesing"=>"到新日期",
"leavesing"=>"离新日期","site"=>"所在工地","hwage"=>"时薪","srvyears"=>"服务年限","yrsinsing"=>"在新年限",
"worklevel"=>"技能水平","education"=>"教育程度","pastwork"=>"往日职业","skill1"=>"主要技能一","skill2"=>"主要技能二",
"drvlic"=>"驾照",);

$customtitles=$this->customtitles;
$offswitches["custom1"]=$customtitles[0];
$offswitches["custom2"]=$customtitles[1];
$offswitches["custom3"]=$customtitles[2];
$offswitches["custom4"]=$customtitles[3];

$count=0;
$oncount=0;
$grids="";
foreach($onswitches as $key => $value)
{
    $oncount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" checked onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '</div><hr><div class="ui-grid-d">';
echo '<input type="hidden" id="oncount" value="'. $oncount . '">';

$offcount=0;
$count=0;
$grids="";
foreach($offswitches as $key => $value)
{
    $offcount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount+$offcount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '<input type="hidden" id="offcount" value="'. $offcount . '">';
echo '<hr>';
?>
</div><!-- /grid-d -->
<hr>
</div>
</div>

</div> <!-- collapsible-set -->

<?php

$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true">';
$selects.=$options;
$selects.='</select>';
echo $selects;



/*
$wdtab=$this->grid("Workersdata", true);
foreach($onswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
foreach($offswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
$wdtab=$wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab=$wdtab->paginatorEnabled(false)->setSorting(false);
$wdtab=$wdtab->helper(new GridHelper_Worker());
$wdtab=$wdtab->data($this->workersdata)->action(':action', '编辑', array( 'url'=>array('action'=>'edit')));
echo $wdtab;
*/
?>
<br>
<table id="datatable">
<thead><tr>
<th>序号</th>
<th>服务公司</th>
<!--<th>所在工地</th>-->
<th>中文名</th>
<th>英文名</th>
<th>准证号码</th>
<th>工种</th>
<th>业务水平</th>
<!--<th>小时工资</th>-->
</tr></thead>
<tbody> 
<?php
/*
$rows="";
foreach($this->result as $tmp)
{
    // worker
    $id = $tmp[0]['id'];
    $namechs = $tmp[0]['namechs'];
    $nameeng = $tmp[0]['nameeng'];;
    $fin = $tmp[0]['fin'];;

    // skills
    $worktype = $tmp["worktype"];    
    $level = $tmp["worklevel"];
    // company
    $company = $tmp["companyname"];
    $site = $tmp["sitename"];
    $hrwage = $tmp["hwage"];

    $row = "<tr>";
    //$row .= '<td><a data-role="button" data-theme="a" data-mini="true" href="/worker/manage/edit?id=' . $id . '">' . $id . '</a></td>' ;
    $row .= '<td><a href="/worker/manage/edit?id=' . $id . '"><button data-mini="true" data-theme="a">' . $id . '</button></a></td>' ;

    $row .= "<td>$company</td>";
    //$row .= "<td>$site</td>" ;
    $row .= "<td>$namechs</td>";
    $row .= "<td>$nameeng</td>";
    $row .= "<td>$fin</td>";
    $row .= "<td>$worktype</td>";
    $row .= "<td>$level</td>";
    //$row .= "<td>$hrwage</td>";
    $row .= "</tr>";
    
    $rows .= $row;
}
echo $rows;
*/
?>
</tbody> 
</table>

<br><br>

