<?php
$onswitches = array(
    "eeeno" => "E'ee No.", "name" => "Name ", "wpno" => "WP No.",
    "wpexpiry" => "WP Expiry", "doa" => "D.O.A", "issuedate" => "Date of Issue",
    "finno" => "Fin No.", "ppno" => "PP No.", "dob" => "D.O.B",
    "ppexpiry" => "PP Expiry", "rate" => "RATE", "csoc" => "C.S.O.C",);

$sheet = $this->sheet;
$sheetarr = $this->sheetarr;
$maindata = $this->maindata;

$options = "";
foreach ($sheetarr as $tmp) {
    if ($sheet == $tmp) {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    } else {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects = '<select data-mini="true" id="sheetselect" data-theme="a">';
$selects.=$options;
$selects.='</select>';

$wdtab = $this->grid("Workersdata", true);
foreach ($onswitches as $key => $value) {
    $wdtab = $wdtab->field($key, $value);
}
$wdtab = $wdtab->field("actions", "Action");
$wdtab = $wdtab->paginatorEnabled(false)->setSorting(false);
$wdtab = $wdtab->helper(new GridHelper_Workerdetails());
$wdtab = $wdtab->data($maindata);

//$renewtabs = $this->rewtabs;
?>
<link rel="stylesheet" href="/common/css/jquery.ui.theme.css" /> 
<link rel="stylesheet" href="/common/css/jquery.ui.datepicker.css" />
<script src="/common/js/jQuery.ui.datepicker.js"></script>
<link rel="stylesheet" href="/common/css/jquery.bpopup.css" />
<script type="text/javascript" src="/common/js/jquery.bpopup.min.js"></script>
<style>
    /* states and images */
    .ui-icon {
        display: block;
        text-indent: -99999px;
        overflow: hidden;
        background-repeat: no-repeat;
    }

    #infoswitches { display: none; }
    #datatable { text-align:center; display:none; }

    #Workersdata {  
        text-shadow: 0 1px #FFFFFF;
        table-layout: fixed;
    }

    #Workersdata, thead, tr {
        font-size:small; 
        text-shadow: 0 1px #FFFFFF;                       
    }

    #Workersdata tr.row_selected td {
        background-color: #FFBED9;
    }

    #Workersdata td {
        font-size: 120%;
        padding: 8px;
    }

    table.grid tr.odd {
        color: #000000;
    }    

    table.grid tr.even {
        color: #000000;
    } 

    #uploaddiv { display: none; }

    #workerdetails { display: none; }
    .bMulti { display: none;  }
    #divresign { display: none; }    
    #divrenews { 
        display: none; 
    }
    .divrenew {
        width: 60%;
        font-size: medium;
    }
    .renewtab {
        table-layout: fixed;
    }
    .renewtab,th,td {
        border:1px solid black;
        border-collapse:collapse;
        padding: 3px;
    }
    #renewinfotab {
        width: 100%;
    }
    #renewinfotab, #renewinfotab td{
        border:0px;
        text-align: left;
    }    
</style>
<script>
    var oTable;
    $(document).ready(function() {
        oTable = $('#Workersdata').dataTable({
            "iDisplayLength": 100,
            "bRetrieve": true,
            /*
             "sScrollX": "100%",
             "sScrollXInner": "100%",                         
             "bScrollCollapse": true,            
             */
        });

        //fnHideColumns();
        //resizetable();

        $("#resigndate").datepicker();

        // add bMulti to popup class
        $("div[id^='renew']").attr("class", "bMulti divrenew");
        $("table[id^='renew']").attr("class", "grid renewtab");

        $(".dateclass").datepicker();
    });

    $("#Workersdata tbody").click(function(event) {
        //alert("click");
        $(oTable.fnSettings().aoData).each(function() {
            $(this.nTr).removeClass('row_selected');
        });
        $(event.target.parentNode).addClass('row_selected');
    });

    function resizetable()
    {
        //var width = $('#Workersdata').css("width");
        //alert("width="+width);
        $('#Workersdata').width('100%');
        //var width = $('#Workersdata').css("width");
        //alert("width="+width);
    }

    function fnHideColumns()
    {
        var oncount = Number($('#oncount').val());
        var offcount = Number($('#offcount').val()) + oncount;
        //alert(oncount + "," + offcount);

        for (i = oncount; i < offcount; i++)
        {   //alert(i);
            fnHideColumn(i);
        }
    }

    function fnHideColumn(iCol)
    {
        /* Get the DataTables object again - this is not a recreation, just a get of the object */
        var oTable = $('#Workersdata').dataTable();
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis(iCol, false);
    }

    function fnShowHide(iCol)
    {
        /* Get the DataTables object again - this is not a recreation, just a get of the object */
        var oTable = $('#Workersdata').dataTable();

        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis(iCol, bVis ? false : true);
    }

    function infoswitches()
    {
        var sws = $("#infoswitches");

        var display = sws.css("display");
        //alert(display);

        if (display == "none")
        {
            $("#infoswitches").show();
        }
        else
        {
            $("#infoswitches").hide();
        }
    }

    function redirect(url) {
        window.location = url;
    }

    function showhideupload()
    {
        var div = $("#uploaddiv");
        var display = div.css("display");
        (display == "none") ? div.show() : div.hide();
    }

    $("#sheetselect").change(function() {
        var sheetname = $(this).val();
        var url = "/worker/manage?sheet=" + sheetname;
        redirect(url);
    });

    function previewlist()
    {
        var sheet = $("#sheetselect").val();
        var url = "/worker/manage/previewlist?sheet=" + sheet;
        window.open(url);
    }

    function clearworkerdetails()
    {
        var r = confirm("确认删除工人数据? 其他相关数据，比如工资，考勤一并会消除");
        if (r == false)
        {
            return false;
        }

        $.post("/worker/import/truncateworkerdetails", {},
                function(data) {
                    //console.log(data);
                    //$('#attensheet').load("/project/attendance/attendsheet?wid=" + wid + "&month="+month + "&sid="+siteid);
                    alert("删除成功");
                    window.location.reload();
                })
    }

    function fnShowHideAll()
    {
        //alert("fnShowHideAll");
        var oTable = $('#Workersdata').dataTable();
        for (var i = 0; i < 34; i++)
        {
            var bVis = oTable.fnSettings().aoColumns[i].bVisible;
            oTable.fnSetColumnVis(i, true);
        }
    }

    function workerResign(wid, name, eeeno)
    {
        $("#sheetres").val($("#sheetselect").val());
        $("#wid").val(wid);
        $("#wname").text("离职 - " + eeeno + " - " + name);
        $("#divresign").bPopup();

        /*
         var r = confirm("确认工人离职? " + name + " " + eeeno);
         if (r == false)
         {
         return false;
         }
         
         $.post("/worker/manage/resign", {id: wid},
         function(data) {
         //console.log(data);
         window.location.reload();
         })
         */
    }

    function workerRenewinfo(wid, name, eeeno)
    {
        /*
        $('#renew' + wid + "").bPopup({
            follow: [true, true], //x, y
            position: [200, 100] //x, y
        });
        */
       var url = "/worker/manage/renewlist/wid/" + wid;
        $('#divrenews').bPopup({
            //contentContainer:'.content',
            loadUrl: url
        });
                      
    }

    function postrenewinfo(wid)
    {
        var wpexpiry = $("#wpexpiry" + wid).val();
        var issuedate = $("#issuedate" + wid).val();
        var ppexpiry = $("#ppexpiry" + wid).val();
        var rate = $("#rate" + wid).val();
        var medicaldate = $("#medicaldate" + wid).val();
        var csoc = $("#csoc" + wid).val();
        var securityexp = $("#securityexp" + wid).val();
        var renewdate = $("#renewdate" + wid).val();

        //alert(wpexpiry + " - " + issuedate + " - " +ppexpiry + " - " +rate + " - " +medicaldate + " - " +csoc + " - " +securityexp + " - " +renewdate);    
        //return;

        $.post("/worker/manage/renew", {wid: wid, wpexpiry: wpexpiry, issuedate: issuedate, ppexpiry: ppexpiry,
            rate: rate, medicaldate: medicaldate, csoc: csoc, securityexp: securityexp, renewdate: renewdate},
        function(data) {
            console.log(data);
            alert("Refresh page to see the updated records.");
        }
        );
    }

    function deleteRenew(rid)
    {
        //alert("deleteRenew - " + rid);
        $.post("/worker/manage/deleterenew", {rid: rid},
        function(data) {
            console.log(data);
            alert("Refresh page to see the updated records.");
        }
        );
    }
</script>

<div data-role="collapsible-set" data-mini="true" data-theme="a">
    <div data-role="collapsible" data-collapsed="true">
        <h3>数据操作</h3>
        <div class="ui-grid-b">
            <div class="ui-block-a">
                <a href="/worker/manage/add" target="_blank"><button data-mini="true" data-theme="a">注册工人</button></a>
            </div>
            <div class="ui-block-b">
                <button data-mini="true" data-theme="a" onclick="showhideupload()">导入工人列表Excel</button>
            </div>
            <div class="ui-block-c">                
                <button data-mini="true" data-theme="a" onclick="clearworkerdetails()">清空工人数据</button>
            </div>
        </div><!-- /grid-b -->
        <div id="uploaddiv">
            <fieldset>
                <form action="/worker/import/submit" method="post" enctype="multipart/form-data">
                    上传工人列表(MS Excel file)：                    
                    <input data-mini="true" type="file" name="file" id="file">
                    <input type="submit" value="上传" data-mini="true" data-theme="a">
                </form>
            </fieldset>
        </div>
    </div>

</div> <!-- collapsible-set -->

<?php
echo $selects;

if (count($maindata)) {
    echo $wdtab;
} else {
    echo "<strong>没有记录，请导入或者编辑工人数据</strong>";
}
?>
<br><br>
<div id="divresign" class="bMulti">
    <h3 id="wname"></h3>
    <form method="post" action="/worker/manage/resign">
        <input type="hidden" id="wid" name="wid" value="0">
        <input type="hidden" id="sheetres" name="sheetres" value="HC.C">

        <input type="text" id="resigndate" name="resigndate" placeholder="点击选择离职日期" />
        <textarea rows="8" cols="50" placeholder="输入离职相关说明" id="resignremark" name="resignremark"></textarea>
        <input type="submit" value="提交" data-mini="true">
    </form>
</div>

<div id="divrenews" class="bMulti">
    
    <?php
    if (0) {
        foreach ($renewtabs as $tmp) {
            echo $tmp . "
";
        }
    }
    ?>
</div>    