<!DOCTYPE html> 
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>工人清单</title> 
	<link rel="stylesheet" href="/common/css/jquery.mobile-1.2.0.min.css" />
    <link href="/DataTables-1.9.4/media/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css" />        
    <script type="text/javascript" src="/common/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <script type="text/javascript" src="/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>
</head> 

<body> 
<style>
#infoswitches { display: none; }
#Workersdata { width:100%; border-collapse:collapse;}
#Workersdata td { text-align:center; border:1px solid black;}
</style>
<script>
$(document).ready(function() {
    $('#Workersdata').dataTable({ 
        //"iDisplayLength": 50,
        //"bRetrieve": true,
        "bPaginate": false,
        "bFilter": false,
        "bInfo": false,
        "bSort": true,
    });

    fnHideColumns();
    resizetable();
} );

function resizetable()
{
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
    $('#Workersdata').width('100%');
    //var width = $('#Workersdata').css("width");
    //alert("width="+width);
}

function fnHideColumns()
{
    var oncount = Number($('#oncount').val());
    var offcount = Number($('#offcount').val()) + oncount;
    //alert(oncount + "," + offcount);

    for(i=oncount; i<offcount; i++)
    {   //alert(i);
        fnHideColumn(i);
    }
}

function fnHideColumn( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, false );
}

function fnShowHide( iCol )
{
	/* Get the DataTables object again - this is not a recreation, just a get of the object */
	var oTable = $('#Workersdata').dataTable();
	
	var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
	oTable.fnSetColumnVis( iCol, bVis ? false : true );
}

function infoswitches()
{
    var sws = $("#infoswitches");    

    var display = sws.css("display");
    //alert(display);

    if(display == "none")
    {
        $("#infoswitches").show();
    }
    else
    {
        $("#infoswitches").hide();
    }
}

function redirect(url) {
    window.location = url;
}

function showhideupload()
{
    var div = $("#uploaddiv");    
    var display = div.css("display");
    (display == "none") ? div.show() : div.hide();
}

function clearworkerdetails()
{
    alert("清除所有工人数据，尚未实现，hold on...");
}

$( "#sheetselect" ).change(function() {
    var sheetname = $(this).val();
    var url = "/worker/manage?sheet=" + sheetname;
    redirect(url);
});

function previewlist()
{
    var sheet = $("#sheetselect").val();
    var url = "/worker/manage/previewlist?sheet=" + sheet;
    window.open (url); 
}
</script>

<div data-role="page">
    <!--
	<div data-role="header">
		<h1>工人清单</h1>
	</div>--><!-- /header -->

	<div data-role="content">	

<?php
$sheet=$this->sheet;
$sheetarr=$this->sheetarr;
$maindata=$this->maindata;

/*
$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;
*/
?>

<button data-theme="a" data-mini="true" onclick="infoswitches()">数据筛选</button>
<div id="infoswitches">
<?php
echo '<div class="ui-grid-d">';

$onswitches=array(
"sn"=>"S/N","eeeno"=>"E'ee No.","namechs"=>"Name","nameeng"=>"Name Eng","wpno"=>"WP No.", 
"ppno"=>"PP No.", "rate"=>"RATE",);

$offswitches=array(
"wpexpiry"=>"WP Expiry","doa"=>"D.O.A","issuedate"=>"Date of Issue","finno"=>"Fin No.",
"dob"=>"D.O.B","ppexpiry"=>"PP Expiry","pano"=>"PA Reference  No.", "sbno"=>"Security Bond No.", 
"securityexp"=>"Security Exprity Date", "worktype"=>"主要工种","arrivaldate"=>"Arrival Date","medicaldate"=>"Medical Date", "csoc"=>"C.S.O.C", "medicalinsuranc"=>"Medical Insurance", "workingsite"=>"WORKING SITE", "dormitory"=>"Dormitory", 
"hometown"=>"区域", "education"=>"教育程度", "age"=>"年龄", "marital"=>"婚姻状况", 
"constructionworker"=>"建筑工", "applyfor"=>"Apply For", "goodat"=>"Good At", "contactno1"=>"Contact No.1", 
"contactno2"=>"Contact No.2", "remarks"=>"Remarks(Agent)",);

$customtitles=$this->customtitles;
$offswitches["custom1"]=$customtitles[0];
$offswitches["custom2"]=$customtitles[1];
$offswitches["custom3"]=$customtitles[2];
$offswitches["custom4"]=$customtitles[3];

$count=0;
$oncount=0;
$grids="";
foreach($onswitches as $key => $value)
{
    $oncount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" checked onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '</div><hr><div class="ui-grid-d">';
echo '<input type="hidden" id="oncount" value="'. $oncount . '">';

$offcount=0;
$count=0;
$grids="";
foreach($offswitches as $key => $value)
{
    $offcount++;
    $count++;
    $block="a";
    switch ($count) {
        case 1:
            $block = "a";
            break;
        case 2:
            $block = "b";
            break;
        case 3:
            $block = "c";
            break;
        case 4:
            $block = "d";
            break;
        case 5:
            $block = "e";
            $count = 0;
            break;
    }

    $colnum = $oncount+$offcount-1;
    $checkbox  = '<input type="checkbox" name="' . $key . '" id="' . $key . '" data-mini="true" onclick="fnShowHide(' . $colnum .');">'; 
    $checkbox .= '<label for="' . $key . '">' . $value . '</label>'  ;

    $grid = '<div class="ui-block-' . $block . '">' . $checkbox . "</div>\n";
    $grids .= $grid;  
}
echo $grids;
echo '<input type="hidden" id="offcount" value="'. $offcount . '">';
echo '<hr></div></div>';

$wdtab=$this->grid("Workersdata", true);
foreach($onswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
foreach($offswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
$wdtab=$wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab=$wdtab->paginatorEnabled(false)->setSorting(false);
//$wdtab=$wdtab->helper(new GridHelper_Worker());
$wdtab=$wdtab->data($maindata);
echo $wdtab;

?>


	</div><!-- /content -->
	<!--
	<div data-role="footer">
		<h4>Footer content</h4>
	</div>--><!-- /footer -->
	
</div><!-- /page -->

</body>
</html>
