<?php
$wpexpiryarr=$this->wpexpiryarr;
$ppexpiryarr=$this->ppexpiryarr;
$securityexparr=$this->securityexparr;
?>
<div data-role="collapsible-set" data-mini="true" data-theme="c">

<div data-role="collapsible" data-collapsed="true">
<h3>安全证/Security Expiry Date</h3>
<a href="/worker/manage/previewexpiry?expiry=securityexp" target="_blank"><button data-mini="true" data-theme="a">预览和打印列表</button></a>
    <div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="true">
    <h3>30天到期</h3>
    <div>
<?php
echo $this->grid("workers0", false)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('securityexp', 'Security Expiry Date')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($securityexparr[0])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));;
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>60天到期</h3>
    <div>
<?php
echo $this->grid("workers1", true)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('securityexp', 'Security Expiry Date')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($securityexparr[1])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));;
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>已到期</h3>
    <div>
<?php
echo $this->grid("workers2", true)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('securityexp', 'Security Expiry Date')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($securityexparr[2])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));;
?>
    </div>
    </div>

    </div>

</div>
<!-- wpexpiryarr -->
<div data-role="collapsible" data-collapsed="true">
<h3>工作准证/WP Expiry</h3>
<a href="/worker/manage/previewexpiry?expiry=wpexpiry" target="_blank"><button data-mini="true" data-theme="a">预览和打印列表</button></a>
    <div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="true">
    <h3>30天到期</h3>
    <div>
<?php
echo $this->grid("workers0", false)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('wpno', 'WP No.')
          ->field('wpexpiry', 'WP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($wpexpiryarr[0])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>60天到期</h3>
    <div>
<?php
echo $this->grid("workers1", true)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('wpno', 'WP No.')
          ->field('wpexpiry', 'WP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($wpexpiryarr[1])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));;
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>已到期</h3>
    <div>
<?php
echo $this->grid("workers2", true)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('wpno', 'WP No.')
          ->field('wpexpiry', 'WP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($wpexpiryarr[2])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));
?>
    </div>
    </div>
    </div>
</div>

<!-- ppexpiryarr -->
<div data-role="collapsible" data-collapsed="true">
<h3>护照/PP Expiry</h3>
<a href="/worker/manage/previewexpiry?expiry=ppexpiry" target="_blank"><button data-mini="true" data-theme="a">预览和打印列表</button></a>
    <div data-role="collapsible-set" data-mini="true" data-theme="c">
    <div data-role="collapsible" data-collapsed="true">
    <h3>30天到期</h3>
    <div>
<?php
echo $this->grid("workers0", false)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('ppno', 'PP No.')
          ->field('ppexpiry', 'PP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($ppexpiryarr[0])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>60天到期</h3>
    <div>
<?php
echo $this->grid("workers1", false)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('ppno', 'PP No.')
          ->field('ppexpiry', 'PP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($ppexpiryarr[1])
          ->actionField(':action', "", '&nbsp;|&nbsp;')
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));;
?>
    </div>
    </div>

    <div data-role="collapsible" data-collapsed="true">
    <h3>已到期</h3>
    <div>
<?php
echo $this->grid("workers2", false)
          ->field('eeeno','E\'ee No.')
          ->field('namechs','中文名称')
          ->field('nameeng', '英文名称')
          ->field('ppno', 'PP No.')
          ->field('ppexpiry', 'PP Expiry')
          ->setSorting(false)  
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Worker())
          ->data($ppexpiryarr[2])
          ->actionField(':action', "", '&nbsp;|&nbsp;')  
          ->action(':action', '详细', array( 'url'=>array('action'=>'edit')));
?>
    </div>
    </div>
    </div>
</div>


</div>


