<style>
#mainselect { display:none; }
</style>
<script>
$(function() {
/*
    var type = $('#type').val();
    //alert("type="+type);
    var prop = (type=="0") ? true : false;
    //$('#maintype').prop("disabled", prop);
    $('mainselect').hide();
*/
});

$("#type").change(function() {
    var type = $(this).val();
    //alert("type="+type);
    var prop = (type=="0") ? true : false;
    //$('#maintype').prop("disabled", prop);
    if(prop == true)
    {    
        $('#mainselect').hide();
    }
    else
    {
        $('#mainselect').show();
    }    
});
</script>

<div data-role="collapsible-set" >

<div data-role="collapsible" data-collapsed="true">
<h3>添加材料类型定义</h3>
<form method="post" action="/material/type/add">
<table class="grid">
<thead></thead>
<tbody>
<tr>
<td><div data-role="fieldcontain">
    <label for="typechs">中文类型:</label>
    <input type="text" name="typechs" id="typechs" value="" data-mini="true" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="typeeng">英文类型:</label>
    <input type="text" name="typeeng" id="typeeng" value="" data-mini="true" />
</div></td>
</tr>
<tr>
<td><div data-role="fieldcontain">
        <label for="type">类型定义:</label>
        <select name="type" id="type">
        <option value="0">这是主要类型</option>
        <option value="1">这是细分类型</option>
        </select>
</div></td>
<td><div data-role="fieldcontain" id="mainselect">
        <label for="name">主要类型:</label>
        <select name="maintype" id="maintype">
        <?php
        $mains=$this->mains;
        foreach($mains as $tmp)
        {
            $id = $tmp->getId();
            $typechs = $tmp->getTypechs();
            $typeeng = $tmp->getTypeeng();
            $options = "";
            $options .= '<option value="' . $id . '">' . $typechs . "/" . $typeeng . '</option>';
            echo $options;
        }
        ?>
        </select>                
</div></td>
</tr>
</tbody>
</table>
<button data-mini="true">添加</button>
</form>
</div> <!--addtype-->

<div data-role="collapsible">
<h3>更改材料类型定义</h3>
<div id="edittype">

<form method="post" action="/material/type/add">
<table class="grid">
<thead></thead>
<tbody>
<tr><td><div data-role="fieldcontain">
    <label for="anytype">选择类型:</label>
    <select name="anytype" id="anytype">
    <?php
    $alltypes=$this->alltypes;
    $options = '<option value="0"></option>';
    foreach($alltypes as $tmp)
    {
        $id = $tmp->getId();
        $typechs = $tmp->getTypechs();
        $typeeng = $tmp->getTypeeng();
        $options .= '<option value="' . $id . '">' . $typechs . "/" . $typeeng . '</option>';
    }
    echo $options;
    ?>
    </select>                
</div></td>
<td></td></tr>
<tr>
<td><div data-role="fieldcontain">
    <label for="typechs">中文类型:</label>
    <input type="text" name="typechs" id="typechs" value="" data-mini="true" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="typeeng">英文类型:</label>
    <input type="text" name="typeeng" id="typeeng" value="" data-mini="true" />
</div></td>
</tr>
<tr>
<td><div data-role="fieldcontain">
        <label for="type">类型定义:</label>
        <select name="type" id="type">
        <option value="0">这是主要类型</option>
        <option value="1">这是细分类型</option>
        </select>
</div></td>
<td><div data-role="fieldcontain" id="mainselect">
        <label for="name">主要类型:</label>
        <select name="maintype" id="maintype">
        <?php
        $mains=$this->mains;
        foreach($mains as $tmp)
        {
            $id = $tmp->getId();
            $typechs = $tmp->getTypechs();
            $typeeng = $tmp->getTypeeng();
            $options = "";
            $options .= '<option value="' . $id . '">' . $typechs . "/" . $typeeng . '</option>';
            echo $options;
        }
        ?>
        </select>                
</div></td>
</tr>
</tbody>
</table>
<button data-mini="true">更新</button>
</form>
</div><!-- edittype -->

</div>
<!--
<div data-role="collapsible">
<h3>删除材料类型定义</h3>
<div id="edittype">
bbb
</div>
</div>	
-->
</div>

<?php
echo $this->grid("Materialtypes", true)
          //->field('id','序号')            
          ->field('main','主要类型')
          ->field('typechs', '细分类型')
          ->actionField(':action', "操作", '&nbsp;|&nbsp;')
          ->itemCountPerPage(30)
          ->paginatorEnabled(false)
          ->helper(new GridHelper_Materialtype())
          ->data($this->alltypes)
          //->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
?>

