<style>
</style>
<script>
$(function() {
    var type = $('#types').val();
    //alert("type="+type);
    var prop = (type=="0") ? true : false;
    $('#maintypes').prop("disabled", prop);
});

$("#types").change(function() {
    var type = $(this).val();
    //alert("type="+type);
    var prop = (type=="0") ? true : false;
    $('#maintypes').prop("disabled", prop);

});
</script>

<div data-role="collapsible-set" >
	<div data-role="collapsible" data-collapsed="true">
	<h3>添加材料类型定义</h3>
<table class="grid">
<thead></thead>
<tbody>
<tr>
<td><div data-role="fieldcontain">
        <label for="name">中文名:</label>
        <input type="text" name="name" id="name" value="" data-mini="true" />
</div></td>
<td><div data-role="fieldcontain">
    <label for="name">英文名:</label>
    <input type="text" name="name" id="name" value="" data-mini="true" />
</div></td>
</tr>
<tr>
<td><div data-role="fieldcontain">
        <label for="types">选择类型:</label>
        <select name="types" id="types">
        <option value="0">这是主要类型</option>
        <option value="1">这是细分类型</option>
        </select>
</div></td>
<td><div data-role="fieldcontain">
        <label for="name">选择主要类型:</label>
        <select name="maintypes" id="maintypes">
        <?php
        $mains=$this->mains;
        foreach($mains as $tmp)
        {
            $id = $tmp->getId();
            $typechs = $tmp->getTypechs();
            $typeeng = $tmp->getTypeeng();

            $options = "";
            $options .= '<option id="' . $id . '>' . $typechs . "/" . $typeeng . '</option>';
            echo $options;
        }
        ?>
        </select>                
</div></td>
</tr>
</tbody>
</table>
<input type="button" value="添加该类型" data-mini="true" data-theme="a">
</div>

	<div data-role="collapsible">
	<h3>更改材料类型定义</h3>
	<div id="edittype">
    bbb
    </div>
	</div>

	<div data-role="collapsible">
	<h3>删除材料类型定义</h3>
	<div id="edittype">
    bbb
    </div>
	</div>	
</div>

