<style>
/*#addtype, #edittype, #deltype {display:none;}*/
</style>
<script>
function showadd()
{
    $("#edittype").hide();
    $("#deltype").hide();    
    $("#addtype").show();
}

function showedit()
{
    $("#edittype").hide();
    $("#deltype").hide();    
    $("#addtype").show();

}

function showdel()
{
    $("#edittype").hide();
    $("#deltype").hide();    
    $("#addtype").show();

}
</script>

<!--
<div data-role="navbar">
	<ul>
		<li><a href="#" onclick="showadd()">添加材料类型定义</a></li>
		<li><a href="#" onclick="showedit()">更改材料类型定义</a></li>
		<li><a href="#" onclick="showdel()">删除材料类型定义</a></li>		
	</ul>
</div>
<div id="addtype">aaa</div>
<div id="edittype">bbb</div>
<div id="deltype">ccc</div>
-->
<div data-role="collapsible-set" >
	<div data-role="collapsible" data-collapsed="true">
	<h3>添加材料类型定义</h3>

<div class="ui-grid-a">
	<div class="ui-block-a">
		<div data-role="fieldcontain">
         <label for="name">中文名:</label>
         <input type="text" name="name" id="name" value="" data-mini="true" />
		</div>
    </div>
	<div class="ui-block-b">
		<div data-role="fieldcontain">
         <label for="name">英文名:</label>
         <input type="text" name="name" id="name" value="" data-mini="true" />
		</div>
    </div>
</div><!-- /grid-a -->

<div class="ui-grid-a">
	<div class="ui-block-a">
		<div data-role="fieldcontain">
        <label for="types">选择类型:</label>
        <select name="types" id="types">
        <option>这是主要类型</option>
        <option>这是细分类型</option>
        </select>
		</div>
    </div>
	<div class="ui-block-b">
		<div data-role="fieldcontain">
        <label for="name">选择主要类型:</label>
        <select name="types" id="types">
<?php
$mains=$this->mains;
foreach($mains as $tmp)
{
    $id = $tmp->getId();
    $typechs = $tmp->getTypechs();
    $typeeng = $tmp->getTypeeng();

    $options = "";
    $options .= '<option id="' . $id . '>' . $typechs . "/" . $typeeng . '</option>';
    echo $options;
}
?>
        </select>
        
		</div>
    </div>
</div><!-- /grid-a -->
<input type="button" value="添加该类型" data-mini="true" data-theme="a">
    </div>
	
	<div data-role="collapsible">
	<h3>更改材料类型定义</h3>
	<div id="edittype">
    bbb
    </div>
	</div>

	<div data-role="collapsible">
	<h3>删除材料类型定义</h3>
	<div id="edittype">
    bbb
    </div>
	</div>	
</div>

