<h1><?php echo $this->translate("Add/Edit Information"); ?></h1>

<script>
function reload(eventObject)
{
    //alert("reload!");
    $("#content").load('/information/manage?category=' + 
$('#select-category').val() + "&language=" + $('#select-language').val()); 
}

$('#select-category').change(reload);
$('#select-language').change(reload);
/*
$('#select-category').change(function(event){ 
    alert($(this).val()); 
    $("#content").load('/information/manage?category=' + $(this).val()); 
});

$('#select-language').change(function(event){ 
    alert($(this).val()); 
    $("#content").load('/information/manage?language=' + $(this).val()); 
});
*/ 
</script> 

<form id="tinymceform" method="post" action="/information/manage/tinymcesubmit">
<label for="select-category" class="select">Category:</label>
<select name="select-category" id="select-category">
<?php echo $this->cateSels; ?> 
<!--
<?php foreach($this->cateSelections as $r): ?>
   <option value=<?php echo $r['title'];?>><?php echo $r['title'];?></option>
<?php endforeach;?>
-->
</select>
<br/>
<br/>

<label for="select-language" class="select">Language:</label>
<select id="select-language" name="select-language">
<!--
    <option value="en_US">en_US</option>
    <option value="zh_CN">zh_CN</option>
-->
    <?php echo $this->langSels; ?> 
</select>
<br/>
<br/>

<script type="text/javascript">
// TODO - these are from tinyMCE full example
	tinyMCE.init({
		// General options
		mode : "textareas",
		theme : "advanced",
		plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

		// Theme options
		theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>
<script> 
// http://stackoverflow.com/questions/1960240/jquery-ajax-submit-form
    var frm = $('#tinymceform');
    frm.submit(function () {
        /*
        var r=confirm("Confirm to submit?");
        if (r==false)
          {
            return false;
          }     
        */
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                //alert('ok');
                alert(data);
            }
        });

        return false;
    });
</script>

<textarea id="elm1" name="elm1" rows="15" cols="80" style="width: 100%">
<?php echo $this->content; ?>  
</textarea>
<input type="submit" name="save" value="Submit" />
</form>
