<script type="text/javascript">
// TODO - re-check these options which are from tinyMCE full example
	tinyMCE.init({
		// General options
		mode : "exact",
		elements: "elm1",
		theme : "advanced",
		plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

		// Theme options
		theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
		theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>
<script>
function submitform()
{
    // http://stackoverflow.com/questions/2122085/problem-jquery-and-tinymce-textarea-value-doesnt-submit
    // save data before post
    tinyMCE.triggerSave();

    $('#data').val(tinyMCE.activeEditor.getContent());

    $("#langhidden").val($("#language").val());
    $("#catehidden").val($("#category").val());         

    document.forms['tinymceform'].submit();
}
</script>

<h3><?php echo $this->translate("Information"); ?><?php echo " " . $this->mode; ?></h3>
<a data-role="button" data-inline="true" href="/information/manage/pageedit?id=<?echo $this->pageid;?>">&lt; Return to
list</a>

<form id="tinymceform" method="post" action="/information/manage/tinymcesubmit">
<input type="hidden" name="modehidden" id="modehidden" value="<?php echo $this->mode; ?>">
<input type="hidden" id="pageid" name="pageid" value="<?php echo $this->pageid; ?>">
<input type="hidden" id="infoid" name="infoid" value="<?php echo $this->id; ?>">
<input type="hidden" id="data" name="data">
<input type="hidden" name="redirect" value="/information/manage/pageedit?id=<?echo $this->pageid;?>">
<div data-role="fieldcontain">
    <label for="language"><?php echo $this->translate('Language');?>:</label>
    <label name="language" id="language"><?php echo $this->language; ?></label>
</div>
<input type="hidden" name="langhidden" id="langhidden" value="">
    <div data-role="fieldcontain">
        <label for="category" ><?php echo $this->translate('Category');?>:</label>
        <input type="text" name="category" id="category" value="<?php echo $this->category; ?>" >
    </div>
<input type="hidden" name="catehidden" id="catehidden" value="">

<textarea id="elm1" name="elm1" data-role="nojs" rows="15" cols="80" style="width: 100%">
<?php echo $this->content; ?>  
</textarea>
<button type="button" id="submitbutton" name="submitbutton" onclick="submitform()">Submit</button> 
</form>

