<?
    $settings = Zend_Registry::get('settings');
?>
<table style="text-align:left; width:400px">
<tr>
<td style="text-align:right;"><img src='/images/gssvgabstract234.png' alt="InfoX"></td>
<td style="text-align:left;"><span style="font-size:60px;font-family: 'Open Sans',sans-serif,Arial; color:#3379ac">InfoX</span></td>
</tr>            
</table>
<?php if($this->errorMessage != ""): ?>  
<p class="error"><?= $this->errorMessage; ?></p>  
<?php endif; ?>  
<?= $this->form; ?>
