<?
    $settings = Zend_Registry::get('settings');
?>
<!--<table width="70%" border="0" cellspacing="0" cellpadding="0" style="margin-left: 150px; margin-top: 95px;">-->
<table border="0" cellspacing="0" cellpadding="0" >
  <tr>
    <td id="mgmtlogin-col1"><!--<img src="<?=$settings->General->Logo->Value?>">-->
    <img src='/example/images/ted_logo_small.png' alt="Ted" height="250" width="250">
    </td>
    <td id="mgmtlogin-col2">
Access to this area requires authentication. Please enter your details below.<br>请输入授权的用户名和密码，登录系统。
<?php if($this->errorMessage != ""): ?>  
<p class="error"><?= $this->errorMessage; ?></p>  
<?php endif; ?>  
  
<?= $this->form; ?> </td>
  </tr>
</table>
