<?php $this->headStyle()->captureStart();?>
form table, form table tr, form table td {
    border: none;
    border-collapse: collapse;
}
form table {
}
.label {
    width: 200px;
}
<?php $this->headStyle()->captureEnd();?>
<form id="<?php echo $this->element->getFormId();?>" 
     enctype="multipart/form-data" method="post" 
     action="<?php echo $this->element->getAction();?>">
     <table>
         <tr>
             <td class="label"><?php echo $this->translate('Nearby Zoom');?></td>
             <td><?php echo $this->element->nearbyzoom;?></td>
         </tr>
         <tr>
             <td class="label"><?php echo $this->translate('Nearby Distance');?></td>
             <td><?php echo $this->element->nearbydistance;?></td>
         </tr>
         <tr>
             <td class="label"><?php echo $this->translate('City Center Address');?></td>
             <td><?php echo $this->element->centeraddress;?></td>
         </tr>
         <tr>
             <td class="label"><?php echo $this->translate('City Zoom');?></td>
             <td><?php echo $this->element->cityzoom;?></td>
         </tr>

         <tr>
             <td colspan="2">
                 <?php echo $this->element->save; ?>
                 <?php echo $this->element->cancel; ?>
             </td>
         </tr>
     </table>
</form>

