<?php
$cotmultiple="";
$botmultiple="";
$workerfood="";
$leaderfood="";
?>
<form method="post" action="/salary/settings/submit">
<div data-role="fieldcontain">
    <label for="cotmultiple">华人加班倍率:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $cotmultiple; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="cotmultiple">孟加拉人加班倍率:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $botmultiple; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="workerfood">工人伙食价格:</label>
    <input data-mini="true" type="text" name="workerfood" id="workerfood" value="<?php echo $workerfood; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="leaderfood">工长伙食价格:</label>
    <input data-mini="true" type="text" name="leaderfood" id="leaderfood" value="<?php echo $leaderfood; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="cotmultiple">旷工天数界限:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $cotmultiple; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="cotmultiple">低于界限扣款:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $cotmultiple; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="cotmultiple">高于界限扣款:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $cotmultiple; ?>" class=""/>
</div>

<div data-role="fieldcontain">
    <label for="cotmultiple">扣款上限:</label>
    <input data-mini="true" type="text" name="cotmultiple" id="cotmultiple" value="<?php echo $cotmultiple; ?>" class=""/>
</div>
<input type="submit" value="提交" data-mini="true" data-theme="a">
