<!DOCTYPE html> 
<html>
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>工资数据输入</title> 
	<link rel="stylesheet"  href="/common/css/jquery.mobile-1.2.0.css" />  
	<script src="/common/js/jquery-1.8.2.min.js"></script>
	<script src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <!--
    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
	-->
    </head> 
<body> 

<style>
table {width: 100%; border-collapse:collapse;}
table td, table th { text-align:center; border:1px solid gray; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}
.noborder td { border:0px; }
</style>	
<script>

</script>
<?php
//$site=$this->site;
//$sitename=$site->getName();
//$siteid=$site->getId();
 
$attendance=$this->attendance;

$date=$this->date;
$monthstr=$this->monthstr;

$workerarr=$this->workerarr;
$attendancearr=$this->attendancearr;

$alltabs=$this->alltabs;
?>

<div data-role="dialog">
    <div data-role="header" data-theme="d">
	    <h1>输入相关数据以计算工资</h1>
    </div>

    <div data-role="content" data-theme="c">
<?
$tabs="";
foreach($alltabs as $tab)
{
    $tabs .= $tab;
}
echo $tabs;
?>
<form action="/project/attendance/quicksubmit" method="post" name="quickform" id="quickform">

<table class="noborder">
<tr>
<td>工作单价:</td><td><input type="text" name="rate" id="rate" value="" data-mini="true" /></td>
<td>其他补扣:</td><td><input type="text" name="otherfee" id="otherfee" value="" data-mini="true" /></td>
<td>提前结帐:</td><td><input type="text" name="inadvance" id="inadvance" value="" data-mini="true" /></td>
</tr>
<tr>
<td>缺勤天数:</td><td><input type="text" id="absencedays" name="absencedays" value=""></td>
<td>缺勤金额:</td><td><input type="text" id="absencefines" name="absencefines" value=""></td>
</tr>
<tr>
<td>预扣税当月:</td><td><input type="text" id="rtmonthpay" name="rtmonthpay" value=""></td>
<td>预扣税月数:</td><td><input type="text" id="rtmonths" name="rtmonths" value=""></td>
<td>预扣税累计:</td><td><input type="text" id="rtall" name="rtall" value=""></td>
</tr>
<tr>
<td>水电费扣款:</td><td><input type="text" id="utfee" name="utfee" value=""></td>
<td>水电费补助:</td><td><input type="text" id="utallowance" name="utallowance" value=""></td>
</tr>
</table>
</form>

<div class="ui-grid-a">
	<div class="ui-block-a"><button onclick="quicksubmit()">提交数据</button></div>
	<div class="ui-block-b"><input type="button" value="关闭本页" onclick="attendialogclose()"></div>
</div><!-- /grid-a -->

	</div> <!-- dialog -->

</body>
</html>

