<!DOCTYPE html> 
<html>
	<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<title>工资数据输入</title> 
	<link rel="stylesheet"  href="/common/css/jquery.mobile-1.2.0.css" />  
	<script src="/common/js/jquery-1.8.2.min.js"></script>
	<script src="/common/js/jquery.mobile-1.2.0.min.js"></script>
    <!--
    <link rel="stylesheet" href="/common/css/jquery.ui.datepicker.mobile.css" /> 
    <script src="/common/js/jQuery.ui.datepicker.js"></script>
    <script src="/common/js/jquery.ui.datepicker.mobile.js"></script>
	<script>
		//reset type=date inputs to text
		$( document ).bind( "mobileinit", function(){
			$.mobile.page.prototype.options.degradeInputs.date = true;
		});	
	</script>
	-->
    </head> 
<body> 

<style>
table {width: 100%; border-collapse:collapse;}
table td, table th { text-align:center; border:1px solid gray; }
.ui-dialog-contain {
	width: 92.5%;
	max-width: 2500px;
	margin: 3% auto 15px auto;
	padding: 0;
	position: relative;
	top: -15px;
}
</style>	
<script>

</script>
<?php
//$site=$this->site;
//$sitename=$site->getName();
//$siteid=$site->getId();
 
$attendance=$this->attendance;

$date=$this->date;
$monthstr=$this->monthstr;

$workerarr=$this->workerarr;
$attendancearr=$this->attendancearr;

$alltabs=$this->alltabs;
?>

<div data-role="dialog">
    <div data-role="header" data-theme="d">
	    <h1>输入相关数据以计算工资</h1>
    </div>

    <div data-role="content" data-theme="c">
<?
$tabs="";
foreach($alltabs as $tab)
{
    $tabs .= $tab;
}
echo $tabs;
?>

    <div style="float:left;">&nbsp;</div>

    <!--<div style="margin: 10px auto 15px auto; max-width:65%;">-->
    <div style="float:left; width:65%;">
<form action="/project/attendance/quicksubmit" method="post" name="quickform" id="quickform">
</form>
<button onclick="quicksubmit()">提交考勤</button>
<br>
<input type="button" value="关闭本页" onclick="attendialogclose()">
    </div>

	</div>
	</div> <!-- dialog -->

</body>
</html>

