<script>
$(function() {
    $('#Workersdata').dataTable({ 
        "iDisplayLength": 50,
        "bRetrieve": true,
    });
} );

$("#sheetselect").change(function() {
    var sheetname = $(this).val();
    var url = "/worker/salary?sheet=" + sheetname;
    redirect(url);
});

function redirect(url) {
    window.location = url;
}
</script>
<?php
$sheetarr=$this->sheetarr;
$sheet=$this->sheet;
$maindata=$this->workerarr;

$nowdate=new Datetime("now");
$thismonth=$nowdate->format("Y-m");
$lastmonth = date('Y-m', strtotime("last month"));

$thismonthurl="/worker/salary/salarybymonth?sheet=$sheet&month=$thismonth";
$lastmonthurl="/worker/salary/salarybymonth?sheet=$sheet&month=$lastmonth"; 
?>

<div class="ui-grid-b">
	<div class="ui-block-a"><a href="<?=$lastmonthurl?>" target="_blank">
<button data-mini="true" data-theme="a">上月工资(<?=$lastmonth?>)</button></a></div>
	<div class="ui-block-b"><a href="<?=$thismonthurl?>" target="_blank">
<button data-mini="true" data-theme="a">本月工资(<?=$thismonth?>)</button></a></div>
	<div class="ui-block-c"><a href="#"><button data-mini="true" data-theme="a">历史记录</button></a></div>
</div>

<?php
$options="";
foreach($sheetarr as $tmp)
{
    if($sheet == $tmp)
    {
        $option = '<option value="' . $tmp . '" selected>' . $tmp . '</option>';
    }
    else
    {
        $option = '<option value="' . $tmp . '" >' . $tmp . '</option>';
    }

    $options .= $option;
}
$selects='<select data-mini="true" id="sheetselect">';
$selects.=$options;
$selects.='</select>';
echo $selects;


$onswitches=array(
"sn"=>"S/N","eeeno"=>"E'ee No.","namechs"=>"Name Chs","nameeng"=>"Name Eng","wpno"=>"WP No.", 
"ppno"=>"PP No.", "rate"=>"RATE",);

$wdtab=$this->grid("Workersdata", true);
foreach($onswitches as $key=>$value)
{
    $wdtab=$wdtab->field($key,$value);
}
$wdtab=$wdtab->actionField(':action', "", '&nbsp;|&nbsp;');
$wdtab=$wdtab->paginatorEnabled(false)->setSorting(false);
//$wdtab=$wdtab->helper(new GridHelper_Worker());
$wdtab=$wdtab->data($maindata)->action(':action', '工资', array( 'url'=>array('action'=>'personalsalary')));
$wdtab=$wdtab->action(':action', '删除', array( 'url'=>array('action'=>'delete')));
echo $wdtab;
?>
<br><br>
