<form id="<?php echo $this->element->getFormId();?>" 
     enctype="multipart/form-data" method="post" 
     action="<?php echo $this->element->getAction();?>">

    <p>
    	Name: <?php echo $this->element->name; ?>
    </p>
    <p>
        Displayed: <?php echo $this->element->is_display; ?>
    </p>
    <p>
        Icon: <?php echo $this->element->icon; ?>
    </p>
    <p>
       	<label>&nbsp;</label>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>

