<script language="javascript">

function handlePasswordType()
{
    var $this = $(this);
    if($this.val() == "auto" || $this.val() == "" ){
	$('#password').hide();
	$('#passwordConfirm').hide();
	$('#passwordLabel').hide();
	$('#passwordConfirmLabel').hide();
    } else {
	$('#password').show();
	$('#passwordConfirm').show();
	$('#passwordLabel').show();
	$('#passwordConfirmLabel').show();
    }
};

$('#passwordType').live('change', handlePasswordType);
$(document).ready(handlePasswordType);
</script>
<form id="<?php echo $this->element->getFormId();?>" 
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <p>
    	<label for="username" class="required"><?=$this->translate("Username");?></label>
        <?php echo $this->element->username; ?>
    </p>
    <p>
        <label for="name" class="required"><?=$this->translate("Name");?></label>
	    <?php echo $this->element->name; ?>
    </p>
	
    <p>
        <label for="email" class="required"><?=$this->translate("Email");?></label>
	    <?php echo $this->element->email; ?>
    </p>
	<p>
        <label for="provider" class="required"><?=$this->translate("Provider");?></label>
	    <?php echo $this->element->provider; ?>
    </p>
    <p>
        <label for="preferredLanguage" class="required"><?=$this->translate("Preferred Language");?></label>
	    <?php echo $this->element->preferredLanguage; ?>
    </p>
		
    <p>
        <label for="password" class="required" id="passwordLabel"><?=$this->translate("Password");?></label>
	    <?php echo $this->element->passwordType; ?>
	    <?php echo $this->element->password; ?>
    </p>
    <p>
        <label for="passwordConfirm"
		class="required" id="passwordConfirmLabel"><?=$this->translate("Confirm Password");?></label>
	    <?php echo $this->element->passwordConfirm; ?>
    </p>
    <p>
        <label for="diabled" class="required"><?=$this->translate("Disabled");?></label>
	    <?php echo $this->element->disabled; ?>
    </p>
    <p>
        <label for="role" class="required"><?=$this->translate("Role");?></label>
	    <?php echo $this->element->role; ?>
    </p>
	
    <p>
       	<label>&nbsp;</label>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>

