<form id="<?php echo $this->element->getFormId();?>" 
     enctype="application/x-www-form-urlencoded" method="post" 
     action="<?php echo $this->element->getAction();?>">
    <p>
    	<label for="password" class="required"><?=$this->translate("password:");?></label>
        <?php echo $this->element->password; ?>
    </p>
    <p>
        <label for="passwordConfirm" class="required"><?=$this->translate("confirm:");?></label>
	    <?php echo $this->element->passwordConfirm; ?>
    </p>
    <p>
       	<label>&nbsp;</label>
        <?php echo $this->element->save; ?>&nbsp;&nbsp;<?php echo $this->element->cancel; ?>
    </p>
</form>

