<?php

$this->headScript()->captureStart();
?>

function checkYesNo(val)
{
    $('#userlink').attr('href',val);
    $('#userlink').attr('data-rel',val);
    $('#popupDialog').popup('open');
}

<?
$this->headScript()->captureEnd();

?>


<h1><?php echo $this->translate('User List');?></h1>

<p><a href="<?php echo $this->url(array('action'=>'add'));?>"><? echo $this->translate('Add A User'); ?></a>

<?
   echo $this->grid("Users", true)
              ->field('username','Username')
              ->field('name', 'Name')
              ->field('email', 'Email')
              ->field('role', 'Role')
              ->field('disabled', 'Disabled')
              ->actionField(':modify', null, '&nbsp;|&nbsp;')
	      ->actionField(':delete',null)
              ->itemCountPerPage(5)
              ->paginatorEnabled(false) // disable internal paginator, use dataTable's
              ->data($this->data)
              ->emptyMessage('No Accounts Exist <a href="'.$this->url(array('action'=>'add')).'">here</a> to register one.')
              ->action(':modify', 'Edit', array( 'url'=>array('action'=>'edit')))
              ->action(':delete', 'Delete', array( 'url'=>array('action'=>'delete')))
              ->action(':modify', 'Reset Password', array( 'url'=>array('action'=>'resetpasswd')))
	      ->helper(new GridHelper_Accounts());
?>

<div data-role="popup" id="popupDialog" data-overlay-theme="a" data-theme="c" style="max-width:400px" class="ui-corner-all">
    <div data-role="header" data-theme="a" class="ui-corner-top">
	<h1><?php echo $this->translate('Confirm Delete User'); ?></h1>
    </div>
    <div data-role="content" data-theme="d" class="ui-corner-bottom ui-content">
	<h3 class="ui-title"><?php echo $this->translate('Are you sure you want to delete this user?');
	?></h3>
	<p><?php echo $this->translate('This action cannot be undone');?>.</p>
	<a href="#" data-role="button" data-inline="true" data-rel="back" data-theme="c"><?php echo $this->translate('Cancel');?></a> 
	<a href="" id="userlink" data-role="button" data-inline="true" data-rel="back" data-theme="c"><?php echo $this->translate('Delete'); ?></a> 
    </div>
</div>
