<script language=javascript>
function checkform()
{
	if(document.getElementById("quantity").value.length<1)
	{
		document.getElementById("quantity").focus();
		alert("Please input quantity");
		return false;   
	}
}

function back()
{
	var page="<?php echo $this->curPage;?>";
	if(page=="")
		page=0;
	window.location ="/management/orders/index/confid/<?php echo $this->orderId;?>/page/"+page;
}

</script>

<h2><?php echo $this->translate('Add Food/Drink');?></h2>

<form onSubmit="return checkform();" method="post" id="add_order">
<p>
<?php echo $this->translate('Service name');?>:<select name="service_id" id="list">
			<?php foreach($this->services as $r): ?>
			<option value="<?php echo $r->getId();?>"><?php echo $r->getTranslateName($this->lang);?></option>
			<?php endforeach;?>
		</select>
</p>
<p><?php echo $this->translate('Quantity');?>:<input id="quantity" name="quantity" type="text"/></p>

<p><?php echo $this->translate('Remark');?>:<textarea cols="70" rows="5" id="remark" name="remark"></textarea></p>

<p>	
	<input type="submit" name="submitButton" id="submitButton" value="<?php echo $this->translate('submit');?>" />
	&nbsp;&nbsp;
	<input type="button" name="cancelCutton" id="cancelCutton" value="<?php echo $this->translate('cancel');?>" onClick="back() " />
</p>

<input name="page" type="hidden" value="<?php echo $this->curPage;?>" />
<input name="confid" type="hidden" value="<?php echo $this->orderId;?>"/>

</form>
